//
//     Generated by private class-dump
//

@interface __RTVStateTransferEventKey : NSObject {
    long long _fromState;
    long long _toState;
}

@property (readonly, nonatomic) long long fromState;
@property (readonly, nonatomic) long long toState;

- (id)initWithFromState:(long long)arg0 toState:(long long)arg1;
- (unsigned long long)hash;
- (long long)fromState;
- (BOOL)isEqual:(id)arg0;
- (id)description;
- (long long)toState;

@end
