//
//     Generated by private class-dump
//

@interface _AFURLSessionTaskSwizzling : NSObject

+ (void)swizzleResumeAndSuspendMethodForClass:(Class)arg0;
+ (void)load;

- (void)af_resume;
- (void)af_suspend;
- (long long)state;

@end
