//
//     Generated by private class-dump
//

@class NSMutableArray;

@interface _BDPObserver : NSObject {
    BOOL _isObserving;
    int _context;
    id _observe;
    NSMutableArray *_keyPaths;
    id _task;
}

@property id observe;
@property (retain) NSMutableArray *keyPaths;
@property (retain) id task;
@property int context;

- (void)_stopObservingLocked;
- (id)initWithObservee:(id)arg0 keyPaths:(id)arg1 context:(int)arg2 task:(id)arg3;
- (void)setObserve:(id)arg0;
- (void)stopObserving;
- (void)startObservingWithOptions:(unsigned long long)arg0;
- (void).cxx_destruct;
- (id)keyPaths;
- (void)setContext:(int)arg0;
- (void)setKeyPaths:(id)arg0;
- (int)context;
- (void)setTask:(id)arg0;
- (void)dealloc;
- (id)task;
- (void)observeValueForKeyPath:(id)arg0 ofObject:(id)arg1 change:(id)arg2 context:(void *)arg3;
- (id)observe;
- (void)stopObservingKeyPath:(id)arg0;

@end
