//
//     Generated by private class-dump
//

@class NSString, NSDictionary, NSMutableArray, NSObject;
@protocol OS_dispatch_queue, ACCPerfReportDelegate;

@interface ACCCreativePerfCompoundPlugin : NSObject <ACCCreativePerfPlugin> {
    id<ACCPerfReportDelegate> reportDelegate;
    NSString *scene;
    NSString *actionName;
    NSDictionary *monitorParams;
    NSObject<OS_dispatch_queue> *sampleQueue;
    NSMutableArray *_plugins;
}

@property (retain, nonatomic) NSMutableArray *plugins;
@property (weak, nonatomic) id<ACCPerfReportDelegate> reportDelegate;
@property (copy, nonatomic) NSString *scene;
@property (copy, nonatomic) NSString *actionName;
@property (copy, nonatomic) NSDictionary *monitorParams;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *sampleQueue;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)compoundPlugin;

- (id)monitorParams;
- (void)setSampleQueue:(id)arg0;
- (id)sampleQueue;
- (void)setMonitorParams:(id)arg0;
- (void)setReportDelegate:(id)arg0;
- (void)prepareWithConfig:(id)arg0;
- (id)reportDelegate;
- (void)setScene:(id)arg0;
- (void).cxx_destruct;
- (void)setPlugins:(id)arg0;
- (void)stop;
- (id)actionName;
- (void)setActionName:(id)arg0;
- (void)clear;
- (void)start;
- (id)scene;
- (id)plugins;
- (void)addPlugin:(id)arg0;

@end
