//
//     Generated by private class-dump
//

@protocol ACCDRPublishSubscription <NSObject>

- (void)publishStart;
- (void)publishProgressChangedTo:(double)arg0;
- (void)publishSucceed;
- (void)publishFailed;

@end
