//
//     Generated by private class-dump
//

@protocol ACCEditPreviewMessageProtocolD <ACCEditPreviewMessageProtocol>

@optional

- (void)updateVideoDataBegin:(id)arg0 updateType:(long long)arg1 multiTrack:(BOOL)arg2;
- (void)updateVideoDataFinished:(id)arg0 updateType:(long long)arg1 multiTrack:(BOOL)arg2;
- (void)willEnterSingleMode:(BOOL)arg0;
- (void)didExitSingleMode;
- (void)handleEffectMessage:(id)arg0;

@end
