//
//     Generated by private class-dump
//

@class NSString;

@interface ACCNLEImageDownloaderParamsConfig : NSObject {
    NSString *_appID;
    NSString *_appVersion;
    NSString *_sdkVersion;
    NSString *_accessKey;
    NSString *_platform;
    NSString *_deviceID;
    NSString *_deviceType;
    NSString *_region;
    NSString *_appLanguage;
    NSString *_effectCacheDir;
    NSString *_effectHost;
    NSString *_modelCacheDir;
    NSString *_artistCacheDir;
    NSString *_artistHost;
    NSString *_imuseCacheDir;
    NSString *_imuseHost;
    NSString *_resolution;
}

@property (copy, nonatomic) NSString *appID;
@property (copy, nonatomic) NSString *appVersion;
@property (copy, nonatomic) NSString *sdkVersion;
@property (copy, nonatomic) NSString *accessKey;
@property (copy, nonatomic) NSString *platform;
@property (copy, nonatomic) NSString *deviceID;
@property (copy, nonatomic) NSString *deviceType;
@property (copy, nonatomic) NSString *region;
@property (copy, nonatomic) NSString *appLanguage;
@property (copy, nonatomic) NSString *effectCacheDir;
@property (copy, nonatomic) NSString *effectHost;
@property (copy, nonatomic) NSString *modelCacheDir;
@property (copy, nonatomic) NSString *artistCacheDir;
@property (copy, nonatomic) NSString *artistHost;
@property (copy, nonatomic) NSString *imuseCacheDir;
@property (copy, nonatomic) NSString *imuseHost;
@property (copy, nonatomic) NSString *resolution;

- (id)effectHost;
- (void)setEffectHost:(id)arg0;
- (id)modelCacheDir;
- (void)setModelCacheDir:(id)arg0;
- (id)effectCacheDir;
- (void)setEffectCacheDir:(id)arg0;
- (id)artistCacheDir;
- (void)setArtistCacheDir:(id)arg0;
- (id)artistHost;
- (void)setArtistHost:(id)arg0;
- (id)imuseCacheDir;
- (void)setImuseCacheDir:(id)arg0;
- (id)imuseHost;
- (void)setImuseHost:(id)arg0;
- (id)region;
- (void)setResolution:(id)arg0;
- (void)setAppID:(id)arg0;
- (void)setDeviceID:(id)arg0;
- (void)setRegion:(id)arg0;
- (id)deviceType;
- (id)resolution;
- (void)setAppVersion:(id)arg0;
- (void).cxx_destruct;
- (id)deviceID;
- (void)setPlatform:(id)arg0;
- (id)platform;
- (id)appVersion;
- (id)appID;
- (void)setDeviceType:(id)arg0;
- (id)sdkVersion;
- (id)accessKey;
- (void)setAccessKey:(id)arg0;
- (void)setSdkVersion:(id)arg0;
- (id)appLanguage;
- (void)setAppLanguage:(id)arg0;

@end
