//
//     Generated by private class-dump
//

@class NSString;
@protocol ACCRecordSwitchModeService, ACCRecorderViewContainer, CKBeautyService, ACCFeatureComponent;

@interface ACCRecorderBeautyComponentSwitchModePlugin : ACCFeatureComponent <ACCRecordSwitchModeServiceSubscriber, ACCServiceBindable, ACCFeatureComponentPlugin> {
    id<ACCFeatureComponent> _component;
    id<ACCRecordSwitchModeService> _switchModeService;
    id<ACCRecorderViewContainer> _viewContainer;
    id<CKBeautyService> _beautyService;
}

@property (class, readonly, nonatomic) id hostIdentifier;

@property (weak, nonatomic) id<ACCRecordSwitchModeService> switchModeService;
@property (weak, nonatomic) id<ACCRecorderViewContainer> viewContainer;
@property (weak, nonatomic) id<CKBeautyService> beautyService;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<ACCFeatureComponent> component;

+ (id)hostIdentifier;

- (void)bindServices:(id)arg0;
- (id)switchModeService;
- (void)switchModeServiceDidChangeMode:(id)arg0 oldMode:(id)arg1;
- (void)setSwitchModeService:(id)arg0;
- (id)beautyService;
- (void)setBeautyService:(id)arg0;
- (void).cxx_destruct;
- (id)component;
- (void)setComponent:(id)arg0;
- (id)viewContainer;
- (void)setViewContainer:(id)arg0;

@end
