//
//     Generated by private class-dump
//

@protocol ACCRecorderViewContainerItemsHideShowObserver <NSObject>

- (void)shouldItemsShow:(BOOL)arg0 animated:(BOOL)arg1;

@optional

- (void)updateItemsHiddenWithAnimation:(BOOL)arg0;
- (void)viewContainerDidLayout;

@end
