//
//     Generated by private class-dump
//

@class ACCMBCircularProgressBarView;

@interface ACCSideslipPropPickCell : ACCSideslipPropBaseCell {
    BOOL _loading;
    ACCMBCircularProgressBarView *_progressView;
    id /* block */ _accessibilityTextPrefixBlock;
}

@property (nonatomic, getter=isLoading) BOOL loading;
@property (retain, nonatomic) ACCMBCircularProgressBarView *progressView;
@property (copy, nonatomic) id /* block */ accessibilityTextPrefixBlock;
@property (readonly, nonatomic, getter=isShowProgress) BOOL showProgress;
@property (nonatomic) double progress;

- (void)showProgress:(BOOL)arg0 animated:(BOOL)arg1;
- (void)setAccessibilityTextPrefixBlock:(id /* block */)arg0;
- (id /* block */)accessibilityTextPrefixBlock;
- (BOOL)isShowProgress;
- (id)accessibilityLabel;
- (BOOL)isLoading;
- (void)setLoading:(BOOL)arg0;
- (void).cxx_destruct;
- (id)progressView;
- (void)setProgressView:(id)arg0;
- (double)progress;
- (void)layoutSubviews;
- (void)setProgress:(double)arg0;
- (void)setupUI;
- (void)setShowProgress:(BOOL)arg0;

@end
