//
//     Generated by private class-dump
//

@class NSString;
@protocol ACCSideslipPropPanelDownloadService, ACCSideslipPropPanelService, ACCSideslipPropService, IESServiceProvider;

@interface ACCSideslipPropPanelPrefetchServiceImpl : NSObject <ACCSideslipPropPanelPrefetchService> {
    id<IESServiceProvider> _serviceProvider;
    id<ACCSideslipPropService> _sideslipPropService;
    id<ACCSideslipPropPanelService> _sideslipPropPanelService;
    id<ACCSideslipPropPanelDownloadService> _sideslipDownloadService;
    long long _prefetchFocusIndex;
}

@property (weak, nonatomic) id<IESServiceProvider> serviceProvider;
@property (weak, nonatomic) id<ACCSideslipPropService> sideslipPropService;
@property (weak, nonatomic) id<ACCSideslipPropPanelService> sideslipPropPanelService;
@property (weak, nonatomic) id<ACCSideslipPropPanelDownloadService> sideslipDownloadService;
@property (nonatomic) long long prefetchFocusIndex;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)sideslipPropService;
- (void)setSideslipPropService:(id)arg0;
- (id)sideslipPropPanelService;
- (void)setSideslipPropPanelService:(id)arg0;
- (id)sideslipDownloadService;
- (void)setSideslipDownloadService:(id)arg0;
- (long long)prefetchFocusIndex;
- (void)setPrefetchFocusIndex:(long long)arg0;
- (void)prefetchIconsWithIndexesIfNeeded:(id)arg0;
- (void)prefetchFocusIndex:(long long)arg0 sencondaryIndexes:(id)arg1;
- (void).cxx_destruct;
- (void)setServiceProvider:(id)arg0;
- (id)initWithServiceProvider:(id)arg0;
- (id)serviceProvider;

@end
