//
//     Generated by private class-dump
//

@protocol ACCStoryFusionMomentService <NSObject>

- (BOOL)isEnableCloseFriendsFeature;
- (void)guideDidShow;
- (BOOL)isEnableFusion;
- (BOOL)isEnableRecordPhotoM;
- (BOOL)isEnableReportShootCameraSource;
- (BOOL)isEnableExtendHookSinglePhoto;
- (BOOL)isEnableHookUploadSinglePhotoByCapture4_3:(BOOL)arg0;
- (BOOL)isEnableHookUploadSingleAssetBySize4_3:(id)arg0 assetModel:(id)arg1;
- (BOOL)isEnableFusionTitleBySinglePhoto;
- (unsigned long long)isEnableHookUploadByTab;
- (BOOL)needShowEditGuide:(BOOL)arg0;
- (unsigned long long)fusionGuideShowedCount;
- (id)guideTipsTitle;
- (id)guideTipsSubtitle;

@end
