//
//     Generated by private class-dump
//

@class NSString;

@interface ACCVdetectAlogSerivce : NSObject <IESVdetectAlogProtocol>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)doLog:(id)arg0 level:(long long)arg1 tag:(id)arg2;

@end
