//
//     Generated by private class-dump
//

@class CAGradientLayer;

@interface ACFFeedMomentContainerMaskView : UIView {
    CAGradientLayer *_centerMaskLayer;
}

@property (retain, nonatomic) CAGradientLayer *centerMaskLayer;

- (void)setupGradientLayer;
- (id)centerMaskLayer;
- (void)setCenterMaskLayer:(id)arg0;
- (id)init;
- (void).cxx_destruct;

@end
