//
//     Generated by private class-dump
//

@class NSString;

@interface AFDAwemeViewedService : HTSService <AFDAwemeViewedService>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)awemeDiggListManager;
- (Class)videoAnalysisPanelManagerClass;
- (id)awemeViewedManager;

@end
