//
//     Generated by private class-dump
//

@interface AFDClipPagingInfo : AWEBaseApiModel {
    BOOL _hasMore;
    long long _nextCursor;
    long long _direction;
}

@property (nonatomic) BOOL hasMore;
@property (nonatomic) long long nextCursor;
@property (nonatomic) long long direction;

+ (id)JSONKeyPathsByPropertyKey;

- (long long)nextCursor;
- (void)setNextCursor:(long long)arg0;
- (long long)direction;
- (void)setHasMore:(BOOL)arg0;
- (BOOL)hasMore;
- (void)setDirection:(long long)arg0;

@end
