//
//     Generated by private class-dump
//

@class AFDCustomMorePopoverSheetControllerContext, DUXPopover, NSObject, NSString, AWEPopoverActionSheet, NSMutableArray, UITableView;
@protocol AWEProfileMenuSectionViewModelProtocol, AFDFriendsListMoreSettingsDelegate;

@interface AFDCustomMorePopoverSheetController : NSObject <UITableViewDelegate, UITableViewDataSource, AWEUserMessage, DUXPopoverCoverViewDelegate, AFDCustomMorePopoverSheetControllerProtocol> {
    BOOL _isNeedConfirmAlwaysReceivePush;
    BOOL _isCloseFriendInit;
    BOOL _hadChangedCloseFriendRelation;
    id<AFDFriendsListMoreSettingsDelegate> _delegate;
    id /* block */ _updateStatusBlock;
    AWEPopoverActionSheet *_popoverView;
    DUXPopover *_duxPopover;
    id /* block */ _dismissBlock;
    UITableView *_tableView;
    NSMutableArray *_itemArray;
    AFDCustomMorePopoverSheetControllerContext *_context;
    NSObject<AWEProfileMenuSectionViewModelProtocol> *_viewModel;
    double _padding;
    double _width;
}

@property (retain, nonatomic) AWEPopoverActionSheet *popoverView;
@property (retain, nonatomic) DUXPopover *duxPopover;
@property (copy, nonatomic) id /* block */ dismissBlock;
@property (retain, nonatomic) UITableView *tableView;
@property (retain, nonatomic) NSMutableArray *itemArray;
@property (retain, nonatomic) AFDCustomMorePopoverSheetControllerContext *context;
@property (retain, nonatomic) NSObject<AWEProfileMenuSectionViewModelProtocol> *viewModel;
@property (nonatomic) double padding;
@property (nonatomic) double width;
@property (nonatomic) BOOL isNeedConfirmAlwaysReceivePush;
@property (nonatomic) BOOL isCloseFriendInit;
@property (nonatomic) BOOL hadChangedCloseFriendRelation;
@property (weak, nonatomic) id<AFDFriendsListMoreSettingsDelegate> delegate;
@property (copy, nonatomic) id /* block */ updateStatusBlock;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)itemArray;
- (void)setItemArray:(id)arg0;
- (void)p_adaptiveLowVersionSystemWithVC:(id)arg0 withView:(id)arg1;
- (BOOL)isPopoverReplaceABTestOn;
- (void)dismissPopoverView;
- (void)setPopoverView:(id)arg0;
- (void)constructItemArray;
- (void)setIsCloseFriendInit:(BOOL)arg0;
- (BOOL)shouldSettingsShowIcon;
- (id /* block */)updateStatusBlock;
- (BOOL)isNeedConfirmAlwaysReceivePush;
- (id /* block */)confirmAlwaysReceivePush;
- (BOOL)hadChangedCloseFriendRelation;
- (BOOL)isCloseFriendInit;
- (double)p_fixedContentHeight;
- (id)duxPopover;
- (void)enterSendMessgaPage;
- (void)modifyAlias;
- (void)configCloseFriendCell:(id)arg0 ForUserStatus:(long long)arg1;
- (void)setIsNeedConfirmAlwaysReceivePush:(BOOL)arg0;
- (void)setHadChangedCloseFriendRelation:(BOOL)arg0;
- (void)blockUser;
- (void)p_constructItemArrayWithTypeSections;
- (void)p_constructItemArray;
- (id)p_allowedItemTypes;
- (BOOL)canShowRemindFollowBackCell;
- (BOOL)canShowMarkCloseFriendCell;
- (BOOL)canShowTAIsFriendCell;
- (BOOL)canShowSendMessageCell;
- (BOOL)canShowHideMyPostCell;
- (BOOL)canShowHideHerPostCell;
- (BOOL)canShowRemoveFriendCell;
- (BOOL)canShowUnFollowCell;
- (BOOL)__isSystemPushOn;
- (void)__presentHalfScreenVC:(id)arg0 withView:(id)arg1;
- (void)coverViewDidHit;
- (void)showCustomPopoverSheetViewWithContext:(id)arg0 showForView:(id)arg1 parentView:(id)arg2 sourceRect:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg3;
- (void)setUpdateStatusBlock:(id /* block */)arg0;
- (void)setDuxPopover:(id)arg0;
- (void)setPadding:(double)arg0;
- (id)popoverView;
- (id)init;
- (id)tableView:(id)arg0 viewForHeaderInSection:(long long)arg1;
- (long long)numberOfSectionsInTableView:(id)arg0;
- (double)tableView:(id)arg0 heightForHeaderInSection:(long long)arg1;
- (void)setTableView:(id)arg0;
- (long long)tableView:(id)arg0 numberOfRowsInSection:(long long)arg1;
- (void).cxx_destruct;
- (id)tableView;
- (void)setContext:(id)arg0;
- (id)tableView:(id)arg0 cellForRowAtIndexPath:(id)arg1;
- (void)setViewModel:(id)arg0;
- (id)userModel;
- (id)delegate;
- (id)context;
- (void)setWidth:(double)arg0;
- (double)tableView:(id)arg0 heightForRowAtIndexPath:(id)arg1;
- (id)viewModel;
- (double)padding;
- (void)setDelegate:(id)arg0;
- (double)width;
- (double)tableView:(id)arg0 heightForFooterInSection:(long long)arg1;
- (id)tableView:(id)arg0 viewForFooterInSection:(long long)arg1;
- (id /* block */)dismissBlock;
- (void)setDismissBlock:(id /* block */)arg0;

@end
