//
//     Generated by private class-dump
//

@protocol AFDGeckoResourcesManagerProtocol <NSObject>

+ (id)dataForPath:(id)arg0 channel:(id)arg1;
+ (void)friends_setImageForImageView:(id)arg0 imageName:(id)arg1 dynamicTheme:(BOOL)arg2 themeColor:(id)arg3;
+ (id)friends_imageNamed:(id)arg0 dynamicTheme:(BOOL)arg1;
+ (id)aAFDGeckoImageView;
+ (id)friends_imageNamed:(id)arg0 dynamicTheme:(BOOL)arg1 themeColor:(id)arg2;
+ (id)imageNamed:(id)arg0 channel:(id)arg1 inSearchBundleName:(id)arg2 dynamicTheme:(BOOL)arg3 themeColor:(id)arg4;
+ (id)imageNamed:(id)arg0 channel:(id)arg1 inSearchBundleName:(id)arg2 dynamicTheme:(BOOL)arg3;
+ (void)setImageForImageView:(id)arg0 imageName:(id)arg1 channel:(id)arg2 inSearchBundleName:(id)arg3 dynamicTheme:(BOOL)arg4 themeColor:(id)arg5;
+ (void)asyncGetDataForPath:(id)arg0 channel:(id)arg1 completion:(id /* block */)arg2;
+ (Class)AFDGeckoImageViewClass;
+ (id)aAFDGeckoButton;

@end
