//
//     Generated by private class-dump
//

@class AFDPineappleRedPacketButtonStateConfig, NSString, NSDictionary, NSNumber;

@interface AFDPineappleRedPacketConfig : MTLModel <MTLJSONSerializing> {
    NSDictionary *_configDict;
    NSNumber *_enabled;
    AFDPineappleRedPacketButtonStateConfig *_unopendState;
    AFDPineappleRedPacketButtonStateConfig *_unopendStateOwn;
    AFDPineappleRedPacketButtonStateConfig *_unopendStateQuiz;
    AFDPineappleRedPacketButtonStateConfig *_openedState;
    AFDPineappleRedPacketButtonStateConfig *_exhaustedState;
    AFDPineappleRedPacketButtonStateConfig *_expiredState;
    NSNumber *_requestTimeout;
    NSNumber *_buttonHeight;
    NSNumber *_buttonFontSize;
    NSString *_publishToast;
    NSString *_dialogFollowTitle;
    NSString *_dialogFollowMessage;
    NSString *_dialogFollowButton;
    NSString *_dialogDenyTitle;
    NSString *_dialogDenyMessage;
    NSString *_dialogDenyButton;
    NSString *_dialogFollowTitleFlash;
    NSString *_dialogFollowMessageFlash;
    NSString *_dialogFollowButtonFlash;
    NSString *_dialogDenyTitleFlash;
    NSString *_dialogDenyMessageFlash;
    NSString *_dialogDenyButtonFlash;
}

@property (retain, nonatomic) NSDictionary *configDict;
@property (retain, nonatomic) NSNumber *enabled;
@property (retain, nonatomic) AFDPineappleRedPacketButtonStateConfig *unopendState;
@property (retain, nonatomic) AFDPineappleRedPacketButtonStateConfig *unopendStateOwn;
@property (retain, nonatomic) AFDPineappleRedPacketButtonStateConfig *unopendStateQuiz;
@property (retain, nonatomic) AFDPineappleRedPacketButtonStateConfig *openedState;
@property (retain, nonatomic) AFDPineappleRedPacketButtonStateConfig *exhaustedState;
@property (retain, nonatomic) AFDPineappleRedPacketButtonStateConfig *expiredState;
@property (retain, nonatomic) NSNumber *requestTimeout;
@property (retain, nonatomic) NSNumber *buttonHeight;
@property (retain, nonatomic) NSNumber *buttonFontSize;
@property (retain, nonatomic) NSString *publishToast;
@property (retain, nonatomic) NSString *dialogFollowTitle;
@property (retain, nonatomic) NSString *dialogFollowMessage;
@property (retain, nonatomic) NSString *dialogFollowButton;
@property (retain, nonatomic) NSString *dialogDenyTitle;
@property (retain, nonatomic) NSString *dialogDenyMessage;
@property (retain, nonatomic) NSString *dialogDenyButton;
@property (retain, nonatomic) NSString *dialogFollowTitleFlash;
@property (retain, nonatomic) NSString *dialogFollowMessageFlash;
@property (retain, nonatomic) NSString *dialogFollowButtonFlash;
@property (retain, nonatomic) NSString *dialogDenyTitleFlash;
@property (retain, nonatomic) NSString *dialogDenyMessageFlash;
@property (retain, nonatomic) NSString *dialogDenyButtonFlash;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)unopendStateJSONTransformer;
+ (id)unopendStateOwnJSONTransformer;
+ (id)unopendStateQuizJSONTransformer;
+ (id)openedStateJSONTransformer;
+ (id)exhaustedStateJSONTransformer;
+ (id)expiredStateJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;

- (void)setButtonFontSize:(id)arg0;
- (id)dialogFollowButton;
- (id)dialogFollowTitle;
- (id)dialogFollowMessage;
- (id)dialogFollowButtonFlash;
- (id)dialogFollowTitleFlash;
- (id)dialogFollowMessageFlash;
- (id)dialogDenyButton;
- (id)dialogDenyTitle;
- (id)dialogDenyMessage;
- (id)dialogDenyButtonFlash;
- (id)dialogDenyTitleFlash;
- (id)dialogDenyMessageFlash;
- (id)publishToast;
- (id)unopendStateQuiz;
- (id)unopendStateOwn;
- (id)unopendState;
- (id)openedState;
- (id)exhaustedState;
- (id)expiredState;
- (void)setUnopendState:(id)arg0;
- (void)setUnopendStateOwn:(id)arg0;
- (void)setUnopendStateQuiz:(id)arg0;
- (void)setOpenedState:(id)arg0;
- (void)setExhaustedState:(id)arg0;
- (void)setExpiredState:(id)arg0;
- (void)setPublishToast:(id)arg0;
- (void)setDialogFollowTitle:(id)arg0;
- (void)setDialogFollowMessage:(id)arg0;
- (void)setDialogFollowButton:(id)arg0;
- (void)setDialogDenyTitle:(id)arg0;
- (void)setDialogDenyMessage:(id)arg0;
- (void)setDialogDenyButton:(id)arg0;
- (void)setDialogFollowTitleFlash:(id)arg0;
- (void)setDialogFollowMessageFlash:(id)arg0;
- (void)setDialogFollowButtonFlash:(id)arg0;
- (void)setDialogDenyTitleFlash:(id)arg0;
- (void)setDialogDenyMessageFlash:(id)arg0;
- (void)setDialogDenyButtonFlash:(id)arg0;
- (id)enabled;
- (id)initWithDictionary:(id)arg0 error:(id *)arg1;
- (void).cxx_destruct;
- (id)buttonHeight;
- (id)configDict;
- (void)setConfigDict:(id)arg0;
- (void)setEnabled:(id)arg0;
- (id)requestTimeout;
- (void)setRequestTimeout:(id)arg0;
- (id)buttonFontSize;
- (void)setButtonHeight:(id)arg0;

@end
