//
//     Generated by private class-dump
//

@interface AnnieSendMultiAnchorEventMethodImpl : AnnieSendMultiAnchorEventMethod

- (void)callWithParamModel:(id)arg0 completionHandler:(id /* block */)arg1;

@end
