//
//     Generated by private class-dump
//

@protocol AWEAwemeDetailPreloadController <NSObject>

@optional

- (void)initialFetchCompletion:(id)arg0 error:(id)arg1;
- (void)cancelCellPreloading;
- (void)scheduleCellPreloading;
- (void)controllerViewDidLoad;
- (void)controllerFinishTransition:(BOOL)arg0;
- (void)prepareForPadViewTransitionAnimated;
- (id)cellForRowAtIndexPath:(id)arg0;
- (void)stop;
- (void)play;
- (void)pause;

@end
