//
//     Generated by private class-dump
//

@interface AWEAwemeDetailConcernController : AWEAwemeNewDetailBaseController

- (void)configWithRouterParamDict:(id)arg0;
- (void)setMetricsInfo;
- (void)viewDidLoad;

@end
