//
//     Generated by private class-dump
//

@class BDImageView, NSString, AWEAdSummerCallingGuideView, AWEAwemeModel, UIView, CHHapticEngine, IESLiveVideoGiftController;
@protocol CHHapticAdvancedPatternPlayer;

@interface AWEAdSummerCallingManager : NSObject <IESLiveVideoGiftControllerDelegate, AWEAdSummerCallingManager> {
    BOOL _isDynamotorLooping;
    BOOL _isLongPressing;
    BOOL _isReadyToPlayEgg;
    id /* block */ reverseInteractionContainerHandler;
    AWEAwemeModel *_model;
    IESLiveVideoGiftController *_dynamotorVideoController;
    UIView *_dynamotorContainerView;
    UIView *_longPressInteractionView;
    AWEAdSummerCallingGuideView *_longPressCountdownView;
    CHHapticEngine *_hapticEngine;
    id<CHHapticAdvancedPatternPlayer> _hapticsEnginePlayer;
    BDImageView *_longPressGuideImageView;
    BDImageView *_longPressProgressingImageView;
    BDImageView *_fullScreenAnimatedEgg;
}

@property (class, readonly, copy, nonatomic) NSString *alphaVideoCacheDirectory;

@property (retain, nonatomic) AWEAwemeModel *model;
@property (retain, nonatomic) IESLiveVideoGiftController *dynamotorVideoController;
@property (retain, nonatomic) UIView *dynamotorContainerView;
@property (nonatomic) BOOL isDynamotorLooping;
@property (retain, nonatomic) UIView *longPressInteractionView;
@property (nonatomic) BOOL isLongPressing;
@property (nonatomic) BOOL isReadyToPlayEgg;
@property (retain, nonatomic) AWEAdSummerCallingGuideView *longPressCountdownView;
@property (retain, nonatomic) CHHapticEngine *hapticEngine;
@property (retain, nonatomic) id<CHHapticAdvancedPatternPlayer> hapticsEnginePlayer;
@property (retain, nonatomic) BDImageView *longPressGuideImageView;
@property (retain, nonatomic) BDImageView *longPressProgressingImageView;
@property (retain, nonatomic) BDImageView *fullScreenAnimatedEgg;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (copy, nonatomic) id /* block */ reverseInteractionContainerHandler;

+ (void)removeAllCache;
+ (void)preloadAlphaVideoWithModel:(id)arg0;
+ (id)summerCallingResourcesCache;
+ (BOOL)isResourceReadyWithModel:(id)arg0;
+ (id)alphaVideoCacheDirectoryWithURLModel:(id)arg0;
+ (id)resourceCachePoolKeyWithModel:(id)arg0;
+ (id)alphaVideoCacheDirectory;
+ (void)tryFetchCouponWithModelIfNeeded:(id)arg0;
+ (void)preDownloadResourcesWithModel:(id)arg0;
+ (void)removeCachedResourceWithModel:(id)arg0;
+ (BOOL)isDynamotorPlaying;

- (void)didFinishPlayingWithError:(id)arg0;
- (void)videoGiftController:(id)arg0 willPlayFrame:(id)arg1;
- (id)longPressGuideImageView;
- (void)loadWebPCacheForImageView:(id)arg0 resourceModel:(id)arg1;
- (id)longPressProgressingImageView;
- (id)fullScreenAnimatedEgg;
- (void)setHapticsEnginePlayer:(id)arg0;
- (void)setIsDynamotorLooping:(BOOL)arg0;
- (id)longPressCountdownView;
- (id)dynamotorVideoController;
- (id)hapticsEnginePlayer;
- (void)setIsReadyToPlayEgg:(BOOL)arg0;
- (id)longPressInteractionView;
- (BOOL)isReadyToPlayEgg;
- (void)resetDynamotor;
- (BOOL)isDynamotorLooping;
- (void)playFullScreenAnimatedEgg;
- (void)openLandingPageAnimated:(BOOL)arg0 refer:(id)arg1 adExtraData:(id)arg2;
- (id /* block */)reverseInteractionContainerHandler;
- (void)delayExecute:(id /* block */)arg0;
- (id)dynamotorContainerView;
- (void)longPressActivated:(id)arg0;
- (void)loadAllCacheAndSetupImageWithModel:(id)arg0;
- (void)playDynamotorAnimationOnView:(id)arg0;
- (void)didClickHeartFillingElement;
- (void)trackDynamotorShow;
- (void)setReverseInteractionContainerHandler:(id /* block */)arg0;
- (void)setDynamotorVideoController:(id)arg0;
- (void)setDynamotorContainerView:(id)arg0;
- (void)setLongPressInteractionView:(id)arg0;
- (void)setLongPressCountdownView:(id)arg0;
- (void)setLongPressGuideImageView:(id)arg0;
- (void)setLongPressProgressingImageView:(id)arg0;
- (void)setFullScreenAnimatedEgg:(id)arg0;
- (void)setModel:(id)arg0;
- (void).cxx_destruct;
- (id)model;
- (BOOL)isLongPressing;
- (void)setIsLongPressing:(BOOL)arg0;
- (void)reset;
- (id)hapticEngine;
- (void)setHapticEngine:(id)arg0;

@end
