//
//     Generated by private class-dump
//

@class NSString;

@interface AWEAnchorUIInfo : MTLModel <MTLJSONSerializing> {
    long long _markCornerRadius;
    long long _markLeftMargin;
    NSString *_markLabelTextColor;
    NSString *_containerViewBackgroundColor;
    NSString *_seperateLineBackgroundColor;
    long long _spaceBetweenTagAndLocLabel;
}

@property (nonatomic) long long markCornerRadius;
@property (nonatomic) long long markLeftMargin;
@property (copy, nonatomic) NSString *markLabelTextColor;
@property (copy, nonatomic) NSString *containerViewBackgroundColor;
@property (copy, nonatomic) NSString *seperateLineBackgroundColor;
@property (nonatomic) long long spaceBetweenTagAndLocLabel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)JSONKeyPathsByPropertyKey;

- (void)setMarkLeftMargin:(long long)arg0;
- (void)setMarkLabelTextColor:(id)arg0;
- (void)setSeperateLineBackgroundColor:(id)arg0;
- (void)setContainerViewBackgroundColor:(id)arg0;
- (long long)markCornerRadius;
- (void)setMarkCornerRadius:(long long)arg0;
- (long long)markLeftMargin;
- (id)markLabelTextColor;
- (id)containerViewBackgroundColor;
- (id)seperateLineBackgroundColor;
- (long long)spaceBetweenTagAndLocLabel;
- (void)setSpaceBetweenTagAndLocLabel:(long long)arg0;
- (void).cxx_destruct;

@end
