//
//     Generated by private class-dump
//

@class NSString, AWERelatedAdLongVideoAdapter, AWEBDALokiManager, AWEAwemeModel;

@interface AWEAdLongVideoBannerManager : NSObject <BDALokiManagerDelegate, AWEAdLongVideoBannerManager> {
    AWEBDALokiManager *_adLokiManager;
    AWERelatedAdLongVideoAdapter *_adAdapter;
    BOOL _hasPreBanner;
    id /* block */ _receiveAdDataBlock;
    id /* block */ _bannerUIDidChangeBlock;
    id /* block */ _bannerDidDisappearBlock;
    id /* block */ _bannerShowBlock;
    AWEAwemeModel *_adBannerAweme;
}

@property (retain, nonatomic) AWEAwemeModel *adBannerAweme;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (copy, nonatomic) id /* block */ receiveAdDataBlock;
@property (copy, nonatomic) id /* block */ bannerUIDidChangeBlock;
@property (copy, nonatomic) id /* block */ bannerDidDisappearBlock;
@property (copy, nonatomic) id /* block */ bannerShowBlock;

+ (BOOL)canAdBannerShowInLongVideo:(id)arg0;

- (void)lokiComponentDowngrade:(id)arg0 errorMsg:(id)arg1;
- (void)lokiShowFinish:(id)arg0;
- (void)lokiClose:(id)arg0;
- (void)lokiComponent:(id)arg0 didChangeIntrinsicContentSize:(struct CGSize { double x0; double x1; })arg1;
- (id)getLynxGlobalProps:(id)arg0;
- (id)lynxBridge;
- (void)setAdBannerAweme:(id)arg0;
- (id /* block */)receiveAdDataBlock;
- (id)adBannerAweme;
- (id /* block */)bannerDidDisappearBlock;
- (void)startFetchLongVideoAdBannerData:(id)arg0;
- (void)loadAdBannerWithContainer:(id)arg0 hasPreBanner:(BOOL)arg1;
- (void)setReceiveAdDataBlock:(id /* block */)arg0;
- (id /* block */)bannerUIDidChangeBlock;
- (void)setBannerUIDidChangeBlock:(id /* block */)arg0;
- (void)setBannerDidDisappearBlock:(id /* block */)arg0;
- (id /* block */)bannerShowBlock;
- (void)setBannerShowBlock:(id /* block */)arg0;
- (id)init;
- (void).cxx_destruct;
- (void)reset;

@end
