//
//     Generated by private class-dump
//

@class NSString, NSDictionary, NSArray, NSNumber;

@interface AWEAdLiveLynxCardAdInfoResultModel : BDXBridgeModel {
    NSDictionary *_adInfo;
    NSString *_adID;
    NSNumber *_adType;
    NSNumber *_cid;
    NSString *_groupID;
    NSString *_logExtra;
    NSArray *_trackUrlList;
    NSString *_SKANParameters;
    NSNumber *_videoDuration;
}

@property (retain, nonatomic) NSDictionary *adInfo;
@property (copy, nonatomic) NSString *adID;
@property (retain, nonatomic) NSNumber *adType;
@property (retain, nonatomic) NSNumber *cid;
@property (copy, nonatomic) NSString *groupID;
@property (copy, nonatomic) NSString *logExtra;
@property (copy, nonatomic) NSArray *trackUrlList;
@property (copy, nonatomic) NSString *SKANParameters;
@property (retain, nonatomic) NSNumber *videoDuration;

+ (id)JSONKeyPathsByPropertyKey;

- (id)logExtra;
- (void)setLogExtra:(id)arg0;
- (id)adID;
- (void)setAdID:(id)arg0;
- (void)setAdInfo:(id)arg0;
- (id)adInfo;
- (void)setTrackUrlList:(id)arg0;
- (id)trackUrlList;
- (id)SKANParameters;
- (void)setSKANParameters:(id)arg0;
- (void)setGroupID:(id)arg0;
- (id)groupID;
- (void).cxx_destruct;
- (id)cid;
- (id)adType;
- (id)videoDuration;
- (void)setVideoDuration:(id)arg0;
- (void)setAdType:(id)arg0;
- (void)setCid:(id)arg0;

@end
