//
//     Generated by private class-dump
//

@interface AWECommentSwiftImpl.CommentHeaderControllerManager : AWEViewFactoryControllerManager <AWEViewControllerLifeCycle> {
    void /* unknown type, empty encoding */ pageContext;
}

- (id)classNameArray;
- (id)init;
- (void).cxx_destruct;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)viewDidDisappear;
- (void)viewWillDisappear;

@end
