//
//     Generated by private class-dump
//

@interface AWECommentSwiftImpl.CommentLiteIncentiveTipsElement : _TtGC19AWECommentSwiftImpl27CommentInputViewBaseElementCS_36CommentInputViewBaseElementViewModel_ <AWECommentInputLiteIncentiveTipViewDelegate> {
    void /* unknown type, empty encoding */ tipView;
    void /* unknown type, empty encoding */ heightConstraint;
    void /* unknown type, empty encoding */ height;
    void /* unknown type, empty encoding */ needReshow;
    void /* unknown type, empty encoding */ avoidCommonBottomTips;
}

- (void)tipViewCloseButtonTappedCompletion:(id /* block */)arg0;
- (void)initializeElement;
- (void)otherBottomTipsViewShown;
- (void)commentRewardHasShown;
- (id)init;
- (void).cxx_destruct;
- (void)dealloc;

@end
