//
//     Generated by private class-dump
//

@class AWECutSameDataExporterInputModel, NSObject, AWEVideoPublishViewModel;
@protocol OS_dispatch_group;

@interface AWECutSameDataExporter : NSObject {
    AWEVideoPublishViewModel *_publishModel;
    AWECutSameDataExporterInputModel *_inputModel;
    NSObject<OS_dispatch_group> *_saveFramsToUploadGroup;
}

@property (retain, nonatomic) AWEVideoPublishViewModel *publishModel;
@property (retain, nonatomic) AWECutSameDataExporterInputModel *inputModel;
@property (retain, nonatomic) NSObject<OS_dispatch_group> *saveFramsToUploadGroup;

- (id)publishModel;
- (void)setPublishModel:(id)arg0;
- (void)p_addSelectedAssetsCount;
- (void)p_fetchAssetsLocationInfos;
- (void)p_addEditedTextsForAudit;
- (void)callbackForCompletion:(id /* block */)arg0;
- (void)exportCutSameDataWithPublishModel:(id)arg0 inputModel:(id)arg1 completion:(id /* block */)arg2;
- (id)p_saveOriginFramesImage:(id)arg0;
- (id)saveFramsToUploadGroup;
- (void)setSaveFramsToUploadGroup:(id)arg0;
- (void).cxx_destruct;
- (id)inputModel;
- (void)setInputModel:(id)arg0;

@end
