//
//     Generated by private class-dump
//

@interface AWECommentSwiftImpl.CommentVideoSameGoodsGuideElement : NSObject {
    void /* unknown type, empty encoding */ pageContext;
    void /* unknown type, empty encoding */ container;
}

- (id)init;
- (void).cxx_destruct;

@end
