//
//     Generated by private class-dump
//

@interface AWECommentSwiftImpl.CommentTransitionAnimator : NSObject {
    void /* unknown type, empty encoding */ type;
    void /* unknown type, empty encoding */ commentInputViewSnapshot;
    void /* unknown type, empty encoding */ transitionContext;
}

- (id)init;
- (void).cxx_destruct;

@end
