//
//     Generated by private class-dump
//

@interface AWECommentSwiftImpl.CommentFoldView : UIView {
    void /* unknown type, empty encoding */ expandAction;
    void /* unknown type, empty encoding */ foldAction;
    void /* unknown type, empty encoding */ isLandscape;
    void /* unknown type, empty encoding */ isBGColorWhite;
    void /* unknown type, empty encoding */ isLoading;
    void /* unknown type, empty encoding */ isExpanded;
    void /* unknown type, empty encoding */ $__lazy_storage_$_expandButton;
    void /* unknown type, empty encoding */ $__lazy_storage_$_loadingView;
    void /* unknown type, empty encoding */ $__lazy_storage_$_expandLabel;
    void /* unknown type, empty encoding */ $__lazy_storage_$_lineView;
}

@property (nonatomic) void /* unknown type, empty encoding */ isLoading;
@property (nonatomic) void /* unknown type, empty encoding */ isExpanded;

- (BOOL)isLoading;
- (void).cxx_destruct;
- (void)setIsExpanded:(BOOL)arg0;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (BOOL)isExpanded;
- (id)initWithCoder:(id)arg0;
- (void)layoutSubviews;
- (void)setIsLoading:(BOOL)arg0;
- (void)expandButtonTapped;

@end
