//
//     Generated by private class-dump
//

@interface AWECommentSwiftImpl.CommentVideoCloudClient : NSObject <BDVideoUploadClientDelegate> {
    void /* unknown type, empty encoding */ streamMediaPathList;
    void /* unknown type, empty encoding */ uploadBusinessAuthParams;
    void /* unknown type, empty encoding */ mediaUploadCompletionBlock;
    void /* unknown type, empty encoding */ progressBlock;
    void /* unknown type, empty encoding */ streamMediaUploadClient;
    void /* unknown type, empty encoding */ vids;
    void /* unknown type, empty encoding */ streamMediaUploadProgress;
    void /* unknown type, empty encoding */ isStreamMediaUploading;
    void /* unknown type, empty encoding */ uploadStreamMediaProcessUpdateCount;
    void /* unknown type, empty encoding */ maxRetryTimes;
}

- (void)videoUpload:(id)arg0 didFinish:(id)arg1 error:(id)arg2;
- (void)videoUpload:(id)arg0 progressDidUpdate:(long long)arg1;
- (void)videoUpload:(id)arg0 fileIndex:(long long)arg1 videoInfo:(id)arg2 error:(id)arg3 log:(id)arg4;
- (id)init;
- (void).cxx_destruct;

@end
