//
//     Generated by private class-dump
//

@class AWEVideoPlayDanmakuContainerView;
@protocol AWEDanmakuItemViewDelegate;

@interface AWEDanmakuFlowTrackLayer : XIGDanmakuBaseTrackLayer {
    BOOL _isVerticalVideo;
    long long _danmakuScene;
    double _lineSpacing;
    double _trackHeight;
    id /* block */ _block;
    double _displayArea;
    double _trackNumber;
    id<AWEDanmakuItemViewDelegate> _itemViewdelegate;
    AWEVideoPlayDanmakuContainerView *_danmakuContainerView;
    struct UIEdgeInsets { double top; double left; double bottom; double right; } _marginInsets;
}

@property (retain, nonatomic) AWEVideoPlayDanmakuContainerView *danmakuContainerView;
@property (nonatomic) long long danmakuScene;
@property (nonatomic) struct UIEdgeInsets { double top; double left; double bottom; double right; } marginInsets;
@property (nonatomic) double lineSpacing;
@property (nonatomic) double trackHeight;
@property (copy, nonatomic) id /* block */ block;
@property (nonatomic) BOOL enableDanmakuInteractionEnabled;
@property (nonatomic) double displayArea;
@property (nonatomic) BOOL isVerticalVideo;
@property (nonatomic) double trackNumber;
@property (weak, nonatomic) id<AWEDanmakuItemViewDelegate> itemViewdelegate;

+ (Class)aAWEPadModuleAdapterClass;

- (id)aAWEPadModuleAdapter;
- (BOOL)isVerticalVideo;
- (id)createContainerView;
- (void)layoutDidChanged;
- (void)updateTracksWhenLayoutChanged:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (void)updateRTLTracksWhenLayoutChanged:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (void)updateTopFixedTrackWhenLayoutChanged:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (void)updateBottomFixedTrackWhenLayoutChanged:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (unsigned long long)calculateRTLTracksCountWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (void)addNumberOfTracks:(unsigned long long)arg0 trackType:(id)arg1;
- (void)removeNumberOfTracks:(unsigned long long)arg0 trackType:(id)arg1;
- (void)adjustLayoutForRTLTrack:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (double)displayArea;
- (double)trackHeight;
- (unsigned long long)calculateTopFixedTracksCountWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (void)adjustLayoutForTopFixedTrack:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (unsigned long long)calculateBottomFixedTracksCountWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (void)adjustLayoutForBottomFixedTrack:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (id)createTrackWithType:(id)arg0;
- (double)calculateTrackHeightWithFontSize:(double)arg0;
- (void)setTrackHeight:(double)arg0;
- (void)setDisplayArea:(double)arg0;
- (id)danmakuContainerView;
- (void)setIsVerticalVideo:(BOOL)arg0;
- (void)setEnableDanmakuInteractionEnabled:(BOOL)arg0;
- (void)setItemViewdelegate:(id)arg0;
- (void)setDanmakuScene:(long long)arg0;
- (long long)danmakuScene;
- (id)itemViewdelegate;
- (BOOL)enableDanmakuInteractionEnabled;
- (void)setDanmakuContainerView:(id)arg0;
- (double)trackNumber;
- (id)init;
- (void).cxx_destruct;
- (void)setBlock:(id /* block */)arg0;
- (void)setTrackNumber:(double)arg0;
- (id /* block */)block;
- (double)lineSpacing;
- (void)setLineSpacing:(double)arg0;
- (struct UIEdgeInsets { double x0; double x1; double x2; double x3; })marginInsets;
- (void)setMarginInsets:(struct UIEdgeInsets { double x0; double x1; double x2; double x3; })arg0;
- (id)layerType;

@end
