//
//     Generated by private class-dump
//

@class NSDictionary;

@interface AWEDCFeedSearchBarDelegateContext : NSObject {
    long long _clickType;
    NSDictionary *_defaultParams;
}

@property (nonatomic) long long clickType;
@property (retain, nonatomic) NSDictionary *defaultParams;

- (id)defaultParams;
- (void)setDefaultParams:(id)arg0;
- (long long)clickType;
- (void)setClickType:(long long)arg0;
- (id)init;
- (void).cxx_destruct;

@end
