//
//     Generated by private class-dump
//

@class UIButton;

@interface AWEDatePickerTopBar : UIView {
    UIButton *_doneButton;
}

@property (retain, nonatomic) UIButton *doneButton;

- (void).cxx_destruct;
- (struct CGSize { double x0; double x1; })intrinsicContentSize;
- (id)doneButton;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (void)setDoneButton:(id)arg0;
- (void)layoutSubviews;

@end
