//
//     Generated by private class-dump
//

@class NSString;

@interface AWEDTOImportAICutData : MTLModel <MTLJSONSerializing> {
    NSString *_videoId;
    NSString *_aiCutId;
    long long _videoCount;
    NSString *_videoSrcLenList;
    NSString *_videoCutLenList;
    NSString *_videoCutStartTime;
}

@property (copy, nonatomic) NSString *videoId;
@property (copy, nonatomic) NSString *aiCutId;
@property (nonatomic) long long videoCount;
@property (copy, nonatomic) NSString *videoSrcLenList;
@property (copy, nonatomic) NSString *videoCutLenList;
@property (copy, nonatomic) NSString *videoCutStartTime;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)JSONKeyPathsByPropertyKey;

- (id)aiCutId;
- (void)setAiCutId:(id)arg0;
- (id)videoSrcLenList;
- (void)setVideoSrcLenList:(id)arg0;
- (id)videoCutLenList;
- (void)setVideoCutLenList:(id)arg0;
- (id)videoCutStartTime;
- (void)setVideoCutStartTime:(id)arg0;
- (void)setVideoId:(id)arg0;
- (void).cxx_destruct;
- (id)videoId;
- (long long)videoCount;
- (void)setVideoCount:(long long)arg0;

@end
