//
//     Generated by private class-dump
//

@class NSString, AWETeenModeAlertConfigModel, UIView, AWEUIAlertView;

@interface AWEDigitalWellbeingAlertManager : NSObject <AWEUserMessage, AWEDigitalWellbeingMessage, UITextViewDelegate, AWEDigitalWellbeingAlertManagerProtocol> {
    BOOL showAlertBackFromH5;
    BOOL _hasShownTeenModeIntroductionAlert;
    long long _showingAlertType;
    AWETeenModeAlertConfigModel *_windowConfig;
    id /* block */ _dismissBlock;
    long long _alertTypeWillShow;
    AWEUIAlertView *_alert;
    UIView *_teenModeAlertView;
    double _teenModeIntroductionAlertBeginShowTime;
    id /* block */ _alertCallBack;
}

@property (nonatomic) long long alertTypeWillShow;
@property (weak, nonatomic) AWEUIAlertView *alert;
@property (weak, nonatomic) UIView *teenModeAlertView;
@property (nonatomic) BOOL hasShownTeenModeIntroductionAlert;
@property (nonatomic) double teenModeIntroductionAlertBeginShowTime;
@property (copy, nonatomic) id /* block */ alertCallBack;
@property (nonatomic) long long showingAlertType;
@property (retain, nonatomic) AWETeenModeAlertConfigModel *windowConfig;
@property (copy, nonatomic) id /* block */ dismissBlock;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) BOOL showAlertBackFromH5;

+ (id)teenModeURLString;
+ (id)sharedManager;

- (void)didFinishLogin;
- (void)didFinishLogout;
- (void)showWithCloseCallback:(id /* block */)arg0;
- (BOOL)canShow;
- (void)serverTeenModeDidTakeEffectForFirstTime;
- (void)isForceServerTeenModeDidChange:(BOOL)arg0;
- (BOOL)isAlertShowing;
- (BOOL)shouldShowAlert:(long long)arg0;
- (id)windowConfig;
- (BOOL)hasShownTeenModeIntroductionAlert;
- (void)bizDowngradeDelayTeenModeAlert;
- (void)showAlertAfterBackFromH5;
- (void)setShowAlertBackFromH5:(BOOL)arg0;
- (void)setHasShownTeenModeIntroductionAlert:(BOOL)arg0;
- (void)setTeenModeIntroductionAlertBeginShowTime:(double)arg0;
- (BOOL)showAlertBackFromH5;
- (BOOL)shouldUserWillEnterFourTeenMode;
- (long long)showingAlertType;
- (BOOL)shouldShowTeenModeUnderFourTeenAlert;
- (BOOL)shouldShowTeenModeIntroductionAlert;
- (BOOL)teenModeShouldAlertInTime;
- (id)getCurrentPopupModel;
- (void)setAlertTypeWillShow:(long long)arg0;
- (void)setShowingAlertType:(long long)arg0;
- (void)setWindowConfig:(id)arg0;
- (void)showTeenModeUnderFourTeenAlertPolling;
- (void)showTeenModeIntroductionAlertWithPolling;
- (id)getUIIDFromWindowConfig;
- (id)getUserTypeFromWindowConfig;
- (void)setTeenModeAlertView:(id)arg0;
- (id)teenModeAlertView;
- (void)showTeenModeUnderFourTeenAlert;
- (BOOL)teenModeShouldAlertInFirstPage;
- (void)showTeenModeIntroductionAlert;
- (BOOL)teenModeShouldAlertInFeed;
- (void)showTeenModeNewStyleIntroductionAlert;
- (void)showTeenModeSimpleStyleIntroductionAlert;
- (void)showTeenModeAlertWithType:(long long)arg0;
- (void)showTeenModeOldStyleIntroductionAlert;
- (void)p_clickOpenTeenMode;
- (double)teenModeIntroductionAlertBeginShowTime;
- (id)alertViewWithAttributedMessage:(id)arg0 attributedText:(id)arg1 handleBlock:(id /* block */)arg2 buttonTile:(id)arg3 buttonHandler:(id /* block */)arg4;
- (void)p_changeTeenModeEnabled;
- (void)openTeenModeWithEnterFrom:(id)arg0;
- (void)p_showAlertView;
- (long long)alertTypeWillShow;
- (id /* block */)alertCallBack;
- (void)setAlertCallBack:(id /* block */)arg0;
- (id)alert;
- (BOOL)textView:(id)arg0 shouldInteractWithURL:(id)arg1 inRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })arg2 interaction:(long long)arg3;
- (id)init;
- (void).cxx_destruct;
- (void)setAlert:(id)arg0;
- (void)dealloc;
- (BOOL)showAlert:(long long)arg0;
- (id /* block */)dismissBlock;
- (void)setDismissBlock:(id /* block */)arg0;

@end
