//
//     Generated by private class-dump
//

@class NSString;

@interface AWEDataLayerMantleGetMethodNetworkProvider : AWEDataLayerGetMethodNetworkProvider <AWEDataLayerMantleNetworkProviderProtocol>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)modelFromNetworkResponseObject:(id)arg0;
- (Class)modelClass;

@end
