//
//     Generated by private class-dump
//

@class NSString, UIImageView, AWEECAwemeVideoDataController, AWEAwemeModel, NSDictionary, UIViewController;
@protocol AWEAwemePlayVideoViewControllerProtocol, AWEPlayVideoViewControllerProtocol, IESECAwemeVideoViewDelegate;

@interface AWEECAwemeVideoView : UIView <AWEModernFullscreenTransitionOuterContextProvider, AWEPlayVideoDelegate, AWEPlayVideoViewControllerStatusDelegate, IESVideoPlayerDelegate, IESECAwemeVideoViewProtocol> {
    BOOL _repeat;
    BOOL _mute;
    BOOL _needToPauseLive;
    BOOL _inTransition;
    id<IESECAwemeVideoViewDelegate> _delegate;
    long long _videoScaleMode;
    long long _coverContentMode;
    UIViewController<AWEAwemePlayVideoViewControllerProtocol, AWEPlayVideoViewControllerProtocol> *_playerController;
    NSString *_videoID;
    NSDictionary *_logExtraDict;
    AWEECAwemeVideoDataController *_dataController;
    UIViewController<AWEAwemePlayVideoViewControllerProtocol, AWEPlayVideoViewControllerProtocol> *_playVideoViewController;
    UIImageView *_coverImageView;
    NSString *_playerTag;
    NSString *_playerSubTag;
}

@property (retain, nonatomic) AWEECAwemeVideoDataController *dataController;
@property (retain, nonatomic) UIViewController<AWEAwemePlayVideoViewControllerProtocol, AWEPlayVideoViewControllerProtocol> *playVideoViewController;
@property (retain, nonatomic) UIImageView *coverImageView;
@property (nonatomic) BOOL inTransition;
@property (copy, nonatomic) NSString *playerTag;
@property (copy, nonatomic) NSString *playerSubTag;
@property (readonly, nonatomic) AWEAwemeModel *model;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) UIViewController<AWEAwemePlayVideoViewControllerProtocol, AWEPlayVideoViewControllerProtocol> *playerController;
@property (weak, nonatomic) id<IESECAwemeVideoViewDelegate> delegate;
@property (nonatomic) BOOL repeat;
@property (nonatomic) BOOL mute;
@property (nonatomic) BOOL needToPauseLive;
@property (nonatomic) long long videoScaleMode;
@property (nonatomic) long long coverContentMode;
@property (readonly, nonatomic) unsigned long long playState;
@property (readonly, copy, nonatomic) NSString *videoID;
@property (retain, nonatomic) NSDictionary *logExtraDict;

- (id)liveTransitionContext;
- (void)player:(id)arg0 playbackFailedWithError:(id)arg1;
- (void)player:(id)arg0 didChangePlaybackStateWithAction:(long long)arg1;
- (void)setLogExtraDict:(id)arg0;
- (id)logExtraDict;
- (void)player:(id)arg0 didUpdateFromPlayViewController:(id)arg1;
- (long long)coverContentMode;
- (void)setCoverContentMode:(long long)arg0;
- (id)playVideoViewController;
- (void)setPlayVideoViewController:(id)arg0;
- (BOOL)shouldModernTransitionUpdatePlayerControllerWithFromContext:(id)arg0;
- (void)videoUpdatePlayerControllerWithPlayVideoVC:(id)arg0;
- (double)currentPlayTime;
- (void)setDataController:(id)arg0;
- (void)setLoopPlayerWithLoopState:(BOOL)arg0 loopWay:(long long)arg1 loopStartTime:(double)arg2 loopEndTime:(double)arg3;
- (void)setPlayerSubTag:(id)arg0;
- (void)setPlayerTag:(id)arg0;
- (void)hideGradientView;
- (BOOL)needToPauseLive;
- (void)setNeedToPauseLive:(BOOL)arg0;
- (void)modernTransitionUpdateOffset:(long long)arg0 isScrolled:(BOOL)arg1;
- (id)modernTransitionContext;
- (void)modernTransitionDidCompleteWithOffset:(long long)arg0;
- (long long)preferScaleMode;
- (void)setCoverImageView:(id)arg0;
- (id)coverImageView;
- (void)setVideoScaleMode:(long long)arg0;
- (void)updateReferString:(id)arg0;
- (void)p_updateVideoPlayerAwemeModel:(id)arg0;
- (id)playerTag;
- (id)playerSubTag;
- (void)p_videoUpdatePlayerControllerWithNewPlayState:(long long)arg0;
- (void)updateAwemeInfos:(id)arg0;
- (void)setCoverImageUrlList:(id)arg0;
- (long long)videoScaleMode;
- (void)setPlayerControllerBackgroundColor:(id)arg0;
- (void)setCacheSecondDuration:(int)arg0;
- (BOOL)mute;
- (void).cxx_destruct;
- (id)model;
- (void)beginTransition;
- (id)playerController;
- (void)stop;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (void)endTransition;
- (double)duration;
- (id)delegate;
- (void)layoutSubviews;
- (void)setDelegate:(id)arg0;
- (void)play;
- (void)pause;
- (void)reset;
- (void)setMute:(BOOL)arg0;
- (BOOL)inTransition;
- (void)setInTransition:(BOOL)arg0;
- (void)addPeriodicTimeObserverForInterval:(double)arg0 queue:(id)arg1 usingBlock:(id /* block */)arg2;
- (double)playableDuration;
- (id)videoID;
- (id)dataController;
- (unsigned long long)playState;
- (BOOL)repeat;
- (void)setRepeat:(BOOL)arg0;
- (void)seekToTime:(double)arg0 completion:(id /* block */)arg1;

@end
