//
//     Generated by private class-dump
//

@class NSURL;

@interface AWEExtensionSecUIDFileStorage : AWEExtensionStorage {
    NSURL *_fileURL;
}

@property (retain, nonatomic) NSURL *fileURL;

+ (id)sharedSecUIDStorage;

- (BOOL)isEmptyString:(id)arg0;
- (id)secUIDStorageKey;
- (id)loginStatusStorageKey;
- (id)getSecUIDsTrackingParamsForTargetSecUID:(id)arg0 groupName:(id)arg1;
- (id)extractSecIDsWithStatus:(unsigned long long)arg0;
- (void)updateSecUID:(id)arg0 status:(unsigned long long)arg1;
- (void)updateLoginStatus:(BOOL)arg0;
- (id)getSecUIDsTrackingParamsForTargetSecUID:(id)arg0;
- (void).cxx_destruct;
- (void)setFileURL:(id)arg0;
- (id)fileURL;
- (void)reset;
- (BOOL)loginStatus;

@end
