//
//     Generated by private class-dump
//

@protocol AWEECMallContainerOptSceneProtocol <NSObject>

+ (id)shareManager;

@optional

- (id)tabMallPrefetchId;
- (void)preCreateContainer;
- (void)preloadLocalImages;
- (void)preloadIGListConfig;
- (void)initPopupTrigger;
- (void)preloadBundle;
- (void)syncPreloadAddressModel;
- (void)registContainerOptScene:(id)arg0;
- (void)launchPrepare;
- (void)preloadPageCard;
- (void)prepare;
- (void)setLandingSpecialStragety:(long long)arg0;
- (long long)landingSpecialStragety;

@end
