//
//     Generated by private class-dump
//

@interface AWEFindFriendsTopIconSectionController : AWEBaseListSectionController

+ (Class)sectionViewModelClass;

- (void)configCell:(id)arg0 index:(long long)arg1 model:(id)arg2;
- (struct CGSize { double x0; double x1; })sizeForItemAtIndex:(long long)arg0 model:(id)arg1 collectionViewSize:(struct CGSize { double x0; double x1; })arg2;
- (id)sectionViewModel;
- (id)init;
- (BOOL)showSeparator;
- (Class)cellClass;

@end
