//
//     Generated by private class-dump
//

@protocol AWEFeedPlayableLoadingMaskView <AWECrotocol>

- (void)showWithModel:(id)arg0 inView:(id)arg1;
- (void)showAnimatedWithModel:(id)arg0 inView:(id)arg1;
- (void)hide;

@end
