//
//     Generated by private class-dump
//

@interface AWEFeedElderModeController : AWEBaseController

- (BOOL)shouldAvoid:(id)arg0;
- (void)tableView:(id)arg0 didEndDisplayingCell:(id)arg1 forRowAtIndexPath:(id)arg2;

@end
