//
//     Generated by private class-dump
//

@protocol AWEFeedRelatedVideoSingleCardCellDelegate <NSObject>

- (void)descriptionDidExpandedOnRelatedVideoSingleCardCell:(id)arg0;
- (void)richContentContaineDidClickOnRelatedVideoSingleCardCell:(id)arg0;
- (void)coverImageUpdateSuccess:(BOOL)arg0 loadingTime:(double)arg1 error:(id)arg2 cell:(id)arg3;
- (void)playerWillStartPlay;

@end
