//
//     Generated by private class-dump
//

@class UILabel;

@interface AWEFeedMixProfileTabEpisodeLatestCell : UICollectionViewCell {
    UILabel *_contentLabel;
}

@property (retain, nonatomic) UILabel *contentLabel;

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (void)setupUI;
- (id)contentLabel;
- (void)setContentLabel:(id)arg0;

@end
