//
//     Generated by private class-dump
//

@class UIColor, NSString, NSArray, UIImage;

@interface AWEFeedNearbyShopCardUIConfig : NSObject {
    BOOL _isEnhancedContennt;
    UIColor *_shopCardDetailBGColor;
    UIColor *_shopCardDetailLabelColor;
    UIImage *_arrowIconImg;
    UIImage *_locationIcon;
    NSString *_locationIconBGCDNPath;
    NSString *_locationIconBGCDNName;
    UIImage *_contentBGImg;
    NSString *_contentBGCDNPath;
    NSString *_contentBGCDNName;
    UIImage *_shopIconImg;
    UIImage *_shopTextImg;
    NSArray *_gradientBGColors;
}

@property (nonatomic) BOOL isEnhancedContennt;
@property (retain, nonatomic) UIColor *shopCardDetailBGColor;
@property (retain, nonatomic) UIColor *shopCardDetailLabelColor;
@property (retain, nonatomic) UIImage *arrowIconImg;
@property (retain, nonatomic) UIImage *locationIcon;
@property (copy, nonatomic) NSString *locationIconBGCDNPath;
@property (copy, nonatomic) NSString *locationIconBGCDNName;
@property (retain, nonatomic) UIImage *contentBGImg;
@property (copy, nonatomic) NSString *contentBGCDNPath;
@property (copy, nonatomic) NSString *contentBGCDNName;
@property (retain, nonatomic) UIImage *shopIconImg;
@property (retain, nonatomic) UIImage *shopTextImg;
@property (copy, nonatomic) NSArray *gradientBGColors;

- (id)gradientBGColors;
- (id)locationIcon;
- (id)contentBGImg;
- (id)contentBGCDNPath;
- (id)contentBGCDNName;
- (void)setLocationIcon:(id)arg0;
- (void)setContentBGImg:(id)arg0;
- (void)setContentBGCDNPath:(id)arg0;
- (void)setContentBGCDNName:(id)arg0;
- (void)setGradientBGColors:(id)arg0;
- (BOOL)isEnhancedContennt;
- (id)shopCardDetailBGColor;
- (id)shopCardDetailLabelColor;
- (id)arrowIconImg;
- (id)shopIconImg;
- (id)shopTextImg;
- (void)setIsEnhancedContennt:(BOOL)arg0;
- (void)setShopCardDetailBGColor:(id)arg0;
- (void)setShopCardDetailLabelColor:(id)arg0;
- (void)setArrowIconImg:(id)arg0;
- (id)locationIconBGCDNPath;
- (void)setLocationIconBGCDNPath:(id)arg0;
- (id)locationIconBGCDNName;
- (void)setLocationIconBGCDNName:(id)arg0;
- (void)setShopIconImg:(id)arg0;
- (void)setShopTextImg:(id)arg0;
- (id)initWithModel:(id)arg0;
- (void).cxx_destruct;

@end
