//
//     Generated by private class-dump
//

@class AWEUGDesktopChannelGuideInstallConfigModel, AWEUGDesktopChannelGuideTrackerInfoModel, NSString, AWEAwemeModel;
@protocol AWESpecialCardContextProtocol, AWESpecialCardDelegate;

@interface AWEFeedDesktopChannelGuideCardController : AWEBaseController <AWEFeedControllerProtocol, AWESpecialCardControllerProtocol, AWEUGDesktopChannelGuideMessage> {
    BOOL _isCancelClicked;
    BOOL _isInstallClicked;
    id<AWESpecialCardContextProtocol> cardContext;
    id<AWESpecialCardDelegate> cardDelegate;
    AWEUGDesktopChannelGuideInstallConfigModel *_installConfig;
    AWEUGDesktopChannelGuideTrackerInfoModel *_trackerInfo;
    AWEAwemeModel *_model;
}

@property (retain, nonatomic) AWEUGDesktopChannelGuideInstallConfigModel *installConfig;
@property (retain, nonatomic) AWEUGDesktopChannelGuideTrackerInfoModel *trackerInfo;
@property (nonatomic) BOOL isCancelClicked;
@property (nonatomic) BOOL isInstallClicked;
@property (retain, nonatomic) AWEAwemeModel *model;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<AWESpecialCardDelegate> cardDelegate;
@property (weak, nonatomic) id<AWESpecialCardContextProtocol> cardContext;

- (id)cardContext;
- (void)setCardContext:(id)arg0;
- (void)showAlineCardDesktopChannelGuideWithModel:(id)arg0 extraParams:(id)arg1;
- (id)cardDelegate;
- (void)setCardDelegate:(id)arg0;
- (void)cardDidAppear:(id)arg0 withAweme:(id)arg1;
- (void)cardDidDisappear:(id)arg0 withAweme:(id)arg1;
- (void)cardTemplateButtonClickWithParams:(id)arg0;
- (void)setTrackerInfo:(id)arg0;
- (void)handleRawData:(id)arg0 pitayaModel:(id)arg1;
- (void)setIsCancelClicked:(BOOL)arg0;
- (id)buildCommonParams;
- (void)setIsInstallClicked:(BOOL)arg0;
- (id)installConfig;
- (BOOL)isCancelClicked;
- (BOOL)isInstallClicked;
- (id)formatActionScheme:(id)arg0;
- (void)setInstallConfig:(id)arg0;
- (void)setModel:(id)arg0;
- (id)trackerInfo;
- (void).cxx_destruct;
- (id)model;
- (void)dealloc;
- (void)viewDidLoad;

@end
