//
//     Generated by private class-dump
//

@class NSString, AWEURLModel;

@interface AWEFavoriteFormatModel : AWEBaseApiModel {
    NSString *_seasonID;
    NSString *_title;
    NSString *_schema;
    NSString *_content;
    unsigned long long _status;
    AWEURLModel *_coverURL;
}

@property (copy, nonatomic) NSString *seasonID;
@property (copy, nonatomic) NSString *title;
@property (copy, nonatomic) NSString *schema;
@property (copy, nonatomic) NSString *content;
@property (nonatomic) unsigned long long status;
@property (retain, nonatomic) AWEURLModel *coverURL;

+ (id)coverURLJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;

- (void)setSeasonID:(id)arg0;
- (id)seasonID;
- (void)setSchema:(id)arg0;
- (void).cxx_destruct;
- (unsigned long long)status;
- (id)content;
- (id)title;
- (void)setStatus:(unsigned long long)arg0;
- (void)setContent:(id)arg0;
- (id)schema;
- (void)setTitle:(id)arg0;
- (id)coverURL;
- (void)setCoverURL:(id)arg0;

@end
