//
//     Generated by private class-dump
//

@interface AWEFeedPlayInteractionController : AWEBaseController

+ (Class)aAWEPadModuleAdapterClass;

- (id)aAWEPadModuleAdapter;
- (void)beginRefresh;
- (void)refreshCompletion:(id)arg0 error:(id)arg1 needAnimation:(BOOL)arg2;
- (id)currentReferString;

@end
