//
//     Generated by private class-dump
//

@class NSString, NSNumber;

@interface AWEFlashMobFlashJoinBtnConfig : MTLModel <MTLJSONSerializing> {
    BOOL _stickerJoinIconShow;
    NSString *_stickerJoinLineColor;
    NSString *_stickerJoinIconURL;
    NSNumber *_stickerJoinBtnHeight;
    NSNumber *_stickerJoinMarginBottom;
    NSNumber *_stickerJoinMarginLeft;
    NSNumber *_stickerJoinMarginRight;
    NSNumber *_stickerJoinMarginTop;
    NSString *_stickerJoinTextFeed;
    NSString *_stickerJoinTextStudio;
    NSString *_stickerJoinTextColor;
    NSNumber *_stickerJoinTextSize;
}

@property (copy, nonatomic) NSString *stickerJoinLineColor;
@property (nonatomic) BOOL stickerJoinIconShow;
@property (copy, nonatomic) NSString *stickerJoinIconURL;
@property (retain, nonatomic) NSNumber *stickerJoinBtnHeight;
@property (retain, nonatomic) NSNumber *stickerJoinMarginBottom;
@property (retain, nonatomic) NSNumber *stickerJoinMarginLeft;
@property (retain, nonatomic) NSNumber *stickerJoinMarginRight;
@property (retain, nonatomic) NSNumber *stickerJoinMarginTop;
@property (copy, nonatomic) NSString *stickerJoinTextFeed;
@property (copy, nonatomic) NSString *stickerJoinTextStudio;
@property (copy, nonatomic) NSString *stickerJoinTextColor;
@property (retain, nonatomic) NSNumber *stickerJoinTextSize;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)JSONKeyPathsByPropertyKey;

- (id)stickerJoinMarginTop;
- (id)stickerJoinLineColor;
- (void)setStickerJoinLineColor:(id)arg0;
- (BOOL)stickerJoinIconShow;
- (void)setStickerJoinIconShow:(BOOL)arg0;
- (id)stickerJoinIconURL;
- (void)setStickerJoinIconURL:(id)arg0;
- (id)stickerJoinBtnHeight;
- (void)setStickerJoinBtnHeight:(id)arg0;
- (id)stickerJoinMarginBottom;
- (void)setStickerJoinMarginBottom:(id)arg0;
- (id)stickerJoinMarginLeft;
- (void)setStickerJoinMarginLeft:(id)arg0;
- (id)stickerJoinMarginRight;
- (void)setStickerJoinMarginRight:(id)arg0;
- (void)setStickerJoinMarginTop:(id)arg0;
- (id)stickerJoinTextFeed;
- (void)setStickerJoinTextFeed:(id)arg0;
- (id)stickerJoinTextStudio;
- (void)setStickerJoinTextStudio:(id)arg0;
- (id)stickerJoinTextColor;
- (void)setStickerJoinTextColor:(id)arg0;
- (id)stickerJoinTextSize;
- (void)setStickerJoinTextSize:(id)arg0;
- (void).cxx_destruct;

@end
