//
//     Generated by private class-dump
//

@interface AWEFriendsImpl.CloseFriendNowImageCell : UICollectionViewCell <ACFMomentFeedPIPDelegate> {
    void /* unknown type, empty encoding */ model;
    void /* unknown type, empty encoding */ pageContext;
    void /* unknown type, empty encoding */ pipComponent;
    void /* unknown type, empty encoding */ enterPureModeTimestamp;
    void /* unknown type, empty encoding */ $__lazy_storage_$_contentImageView;
    void /* unknown type, empty encoding */ $__lazy_storage_$_mediaContentView;
}

- (void)swapPIPContent;
- (void)pipViewEnterPureMode;
- (void)pipViewExitPureMode;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (id)initWithCoder:(id)arg0;
- (void)prepareForReuse;

@end
