//
//     Generated by private class-dump
//

@protocol AWEFeedTabJumpGuideControllerPrivateProtocol <NSObject>

- (id)referString;
- (id)currentAwemeModel;
- (id)currentJumpTabInfoModel;
- (id)createJumpToMallTrackParamsWithMethod:(id)arg0;
- (void)showFeedTabJumpGuideButton:(id)arg0;
- (void)recordGuideShow;
- (void)trackProductEntranceShowToMallWithControllerTrackParam:(id)arg0;

@end
