//
//     Generated by private class-dump
//

@class NSArray, UIImageView, DUXButton, UILabel, NSString;

@interface AWEGuestFollowListCell : UICollectionViewCell {
    NSArray *_avatarURLs;
    UILabel *_nameLabel;
    NSString *_verifiedIconName;
    long long _followStatus;
    UIImageView *_avatarView;
    UIImageView *_verifiedIconView;
    DUXButton *_followButton;
}

@property (retain, nonatomic) UIImageView *avatarView;
@property (retain, nonatomic) UILabel *nameLabel;
@property (retain, nonatomic) UIImageView *verifiedIconView;
@property (retain, nonatomic) DUXButton *followButton;
@property (copy, nonatomic) NSArray *avatarURLs;
@property (copy, nonatomic) NSString *verifiedIconName;
@property (nonatomic) long long followStatus;

- (long long)followStatus;
- (void)setFollowStatus:(long long)arg0;
- (id)verifiedIconName;
- (id)avatarURLs;
- (void)setupBinding;
- (id)followButton;
- (void)setFollowButton:(id)arg0;
- (void)setVerifiedIconName:(id)arg0;
- (void)setAvatarURLs:(id)arg0;
- (void)updateWithFollowStatus:(long long)arg0;
- (id)verifiedIconView;
- (void)setVerifiedIconView:(id)arg0;
- (void)updateWithVerifiedIconName:(id)arg0;
- (void)followButtonDidClick;
- (void)setAvatarView:(id)arg0;
- (id)avatarView;
- (void).cxx_destruct;
- (void)setup;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (id)nameLabel;
- (void)setNameLabel:(id)arg0;

@end
