//
//     Generated by private class-dump
//

@class NSString;
@protocol HGNetworkTaskProtocol;

@interface AWEHGPluginRoomInfoImpl : NSObject <HGAwemeRoomInfoPluginDelegate> {
    id<HGNetworkTaskProtocol> _getRoomInfoNetRequest;
}

@property (retain, nonatomic) id<HGNetworkTaskProtocol> getRoomInfoNetRequest;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)sharedPlugin;

- (void)hg_getRoomInfoForUniqueID:(id)arg0 completion:(id /* block */)arg1;
- (id)getRoomInfoNetRequest;
- (void)setGetRoomInfoNetRequest:(id)arg0;
- (void).cxx_destruct;

@end
