//
//     Generated by private class-dump
//

@class NSString;

@interface AWEIntelliAlbumSDKLogger : NSObject <ILALoggerProtocol>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)sharedInstance;

- (void)event:(id)arg0 params:(id)arg1;
- (void)log:(id)arg0 level:(unsigned long long)arg1;

@end
