//
//     Generated by private class-dump
//

@interface AWEIMSwiftImpl.QuestionsAndAnswersActivityStageInfo : MTLModel <MTLJSONSerializing> {
    void /* unknown type, empty encoding */ stageId;
    void /* unknown type, empty encoding */ stageStartTime;
    void /* unknown type, empty encoding */ answerDuration;
    void /* unknown type, empty encoding */ waitingDuration;
}

@property (nonatomic, retain) void /* unknown type, empty encoding */ stageId;
@property (nonatomic, retain) void /* unknown type, empty encoding */ stageStartTime;
@property (nonatomic, retain) void /* unknown type, empty encoding */ answerDuration;
@property (nonatomic, retain) void /* unknown type, empty encoding */ waitingDuration;

+ (id)JSONKeyPathsByPropertyKey;

- (id)stageId;
- (void)setStageId:(id)arg0;
- (id)stageStartTime;
- (void)setStageStartTime:(id)arg0;
- (id)answerDuration;
- (void)setAnswerDuration:(id)arg0;
- (id)waitingDuration;
- (void)setWaitingDuration:(id)arg0;
- (id)init;
- (id)initWithDictionary:(id)arg0 error:(id *)arg1;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg0;

@end
