//
//     Generated by private class-dump
//

@protocol AWEIMRightToLeftPopNonInteractedOuterContextProvider

@optional

- (BOOL)enableLeftSlideNonInteractedPopTransitionToPage:(Class)arg0;
- (id)nonInteractedPopTransitionAnimationDuration;
- (unsigned long long)nonInteractedPopTransitionAnimationOptions;
- (BOOL)usingFadingAnimation;

@end
