//
//     Generated by private class-dump
//

@class UIButton, UITapGestureRecognizer, UIImageView, AWEIMMarkMoveNoticeTipConfigModel, UILabel, UIView, YYLabel;
@protocol AWEIMMarkMoveNoticeTipViewProtocol;

@interface AWEIMMarkMoveNoticeTipView : UIView {
    AWEIMMarkMoveNoticeTipConfigModel *_configModel;
    id<AWEIMMarkMoveNoticeTipViewProtocol> _delegate;
    UIImageView *_avatarImageView;
    YYLabel *_titleLabel;
    YYLabel *_subTitleLabel;
    UIButton *_deleteBtn;
    UITapGestureRecognizer *_tap;
    UILabel *_tokenLabel;
    UIImageView *_tokenImageView;
    UIView *_tokenContainer;
}

@property (retain, nonatomic) UIImageView *avatarImageView;
@property (retain, nonatomic) YYLabel *titleLabel;
@property (retain, nonatomic) YYLabel *subTitleLabel;
@property (retain, nonatomic) UIButton *deleteBtn;
@property (retain, nonatomic) UITapGestureRecognizer *tap;
@property (retain, nonatomic) UILabel *tokenLabel;
@property (retain, nonatomic) UIImageView *tokenImageView;
@property (retain, nonatomic) UIView *tokenContainer;
@property (retain, nonatomic) AWEIMMarkMoveNoticeTipConfigModel *configModel;
@property (weak, nonatomic) id<AWEIMMarkMoveNoticeTipViewProtocol> delegate;

- (void)configWithModel:(id)arg0;
- (void)setConfigModel:(id)arg0;
- (id)configModel;
- (void)setupLayouts;
- (id)initWithConfigModel:(id)arg0;
- (id)tokenLabel;
- (void)setTokenLabel:(id)arg0;
- (void)setupTruncationTokenWithConfig:(id)arg0;
- (void)didTapMoveNoticeViewCard;
- (id)deleteBtn;
- (void)setTokenContainer:(id)arg0;
- (id)tokenContainer;
- (void)didTapTailToken;
- (void)setTokenImageView:(id)arg0;
- (id)tokenImageView;
- (void)didClickDeleteIcon:(id)arg0;
- (void)setDeleteBtn:(id)arg0;
- (void).cxx_destruct;
- (double)height;
- (id)titleLabel;
- (void)setup;
- (id)delegate;
- (void)setDelegate:(id)arg0;
- (void)setTitleLabel:(id)arg0;
- (void)setupView;
- (id)avatarImageView;
- (void)setAvatarImageView:(id)arg0;
- (id)subTitleLabel;
- (void)setSubTitleLabel:(id)arg0;
- (id)tap;
- (void)setTap:(id)arg0;

@end
