//
//     Generated by private class-dump
//

@class AWEIMIncentiveChatCellConfDetail;

@interface AWEIMIncentiveChatCellConf : NSObject {
    AWEIMIncentiveChatCellConfDetail *_commonConf;
    AWEIMIncentiveChatCellConfDetail *_privateUpdateQuotaConf;
    AWEIMIncentiveChatCellConfDetail *_groupUpdateQuotaConf;
}

@property (retain, nonatomic) AWEIMIncentiveChatCellConfDetail *commonConf;
@property (retain, nonatomic) AWEIMIncentiveChatCellConfDetail *privateUpdateQuotaConf;
@property (retain, nonatomic) AWEIMIncentiveChatCellConfDetail *groupUpdateQuotaConf;

- (id)dictionaryRawData;
- (id)commonConf;
- (void)setCommonConf:(id)arg0;
- (id)privateUpdateQuotaConf;
- (void)setPrivateUpdateQuotaConf:(id)arg0;
- (id)groupUpdateQuotaConf;
- (void)setGroupUpdateQuotaConf:(id)arg0;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg0;

@end
