//
//     Generated by private class-dump
//

@interface AWEKnowledgeSwiftImpl.HangoutListLandingUndertakeComponent : AWESpeCategoryKit.FeedListBaseComponent <AWEKnowledgeSwiftImpl.HangoutListComponentProtocol>

- (void)onFetchListDataEndWithReason:(long long)arg0 success:(BOOL)arg1 response:(id)arg2 error:(id)arg3;
- (void)didLandingWithParams:(id)arg0;
- (void)didLeaveWithParams:(id)arg0;
- (id)init;

@end
