//
//     Generated by private class-dump
//

@protocol AWEKnowledgeRichFullPageSwiftService <HTSService>

- (id)fullPageRecommendViewControllerWithContext:(id)arg0 config:(id)arg1;
- (id)fullPageRecommendViewControllerWithContext:(id)arg0 config:(id)arg1;

@end
