//
//     Generated by private class-dump
//

@class AWELiveAcqCastVideoLikeController, NSNumber, NSArray, AWELiveAcqCastVideoRecommendController, NSString, AWELiveAcqSlidingTabbarView, AWELiveAcqCastLiveStreamController, UICollectionView, AWELiveAcqSlidingViewController, AWELiveAcqCastVideoPostController;

@interface AWELiveAcqCastVideoUserPanel : AWELiveAcqCastVideoBasePanel <AWEUserProfileTabVCDelegate, AWESlidingViewControllerDelegate> {
    UICollectionView *_switchCollectionView;
    NSArray *_titlesArray;
    NSArray *_tabTypesArray;
    AWELiveAcqSlidingTabbarView *_tabView;
    AWELiveAcqSlidingViewController *_slidingVC;
    AWELiveAcqCastVideoRecommendController *_recommendVC;
    AWELiveAcqCastVideoPostController *_postVC;
    AWELiveAcqCastVideoLikeController *_likeVC;
    NSNumber *_favoriteCount;
    NSNumber *_awemeCount;
    long long _currentSelectedIndex;
    unsigned long long _lastSelectedSlidingTab;
    double _selectionLineSize;
    AWELiveAcqCastLiveStreamController *_liveStreamVC;
}

@property (retain, nonatomic) AWELiveAcqCastLiveStreamController *liveStreamVC;
@property (retain, nonatomic) UICollectionView *switchCollectionView;
@property (retain, nonatomic) NSArray *titlesArray;
@property (retain, nonatomic) NSArray *tabTypesArray;
@property (retain, nonatomic) AWELiveAcqSlidingTabbarView *tabView;
@property (retain, nonatomic) AWELiveAcqSlidingViewController *slidingVC;
@property (retain, nonatomic) AWELiveAcqCastVideoRecommendController *recommendVC;
@property (retain, nonatomic) AWELiveAcqCastVideoPostController *postVC;
@property (retain, nonatomic) AWELiveAcqCastVideoLikeController *likeVC;
@property (nonatomic) NSNumber *favoriteCount;
@property (nonatomic) NSNumber *awemeCount;
@property (nonatomic) long long currentSelectedIndex;
@property (nonatomic) unsigned long long lastSelectedSlidingTab;
@property (nonatomic) double selectionLineSize;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)setFavoriteCount:(id)arg0;
- (void)onClickBack;
- (void)setTabView:(id)arg0;
- (id)awemeCount;
- (void)setAwemeCount:(id)arg0;
- (id)titlesArray;
- (void)setTitlesArray:(id)arg0;
- (long long)numberOfControllers:(id)arg0;
- (id)slidingViewController:(id)arg0 viewControllerAtIndex:(long long)arg1;
- (void)slidingViewController:(id)arg0 didSelectIndex:(long long)arg1 transitionType:(long long)arg2;
- (long long)currentSelectedIndex;
- (id)slidingVC;
- (void)setCurrentSelectedIndex:(long long)arg0;
- (void)setSlidingVC:(id)arg0;
- (void)userProfileTabVC:(id)arg0 didScroll:(struct CGPoint { double x0; double x1; })arg1;
- (double)maxBannerHeight;
- (long long)tabTypeAtIndex:(long long)arg0;
- (double)selectionLineSize;
- (void)setSelectionLineSize:(double)arg0;
- (long long)indexForVCType:(long long)arg0;
- (void)setProfileShowTab:(long long)arg0;
- (double)userProfileTabHeight;
- (id)userForTabVC;
- (id)recommendVC;
- (void)setTabTypesArray:(id)arg0;
- (id)tabTypesArray;
- (void)setLastSelectedSlidingTab:(unsigned long long)arg0;
- (id)postVC;
- (unsigned long long)lastSelectedSlidingTab;
- (void)updateFavoriteTabIcon:(long long)arg0;
- (id)p_tabVCForType:(long long)arg0;
- (id)likeVC;
- (id)liveStreamVC;
- (struct CGPoint { double x0; double x1; })contentOffsetOfCurrentVC;
- (id)switchCollectionView;
- (void)setSwitchCollectionView:(id)arg0;
- (void)setRecommendVC:(id)arg0;
- (void)setPostVC:(id)arg0;
- (void)setLikeVC:(id)arg0;
- (void)setLiveStreamVC:(id)arg0;
- (void).cxx_destruct;
- (double)headerHeight;
- (void)setupUI;
- (id)favoriteCount;
- (long long)currentTab;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0 viewModel:(id)arg1;
- (id)tabView;

@end
