//
//     Generated by private class-dump
//

@class AWELiveAppointmentGroupStatusModel;

@interface AWELiveAppointmentGroupStatusResponseModel : AWEBaseApiModel {
    AWELiveAppointmentGroupStatusModel *_appointmentGroupStatus;
}

@property (retain, nonatomic) AWELiveAppointmentGroupStatusModel *appointmentGroupStatus;

+ (id)appointmentGroupStatusJSONAdapter;
+ (id)JSONKeyPathsByPropertyKey;

- (id)appointmentGroupStatus;
- (void)setAppointmentGroupStatus:(id)arg0;
- (void).cxx_destruct;

@end
