//
//     Generated by private class-dump
//

@class UIButton, AWEDanmakuModel, UIImageView, UILabel, UIView, YYLabel;
@protocol AWELandScapeDanmakuListTableViewCellDelegate;

@interface AWELandScapeDanmakuListTableViewCell : UITableViewCell {
    BOOL _hasDigged;
    id<AWELandScapeDanmakuListTableViewCellDelegate> _delegate;
    UIView *_leftContainer;
    UIView *_rightContainer;
    UILabel *_timeOffsetLabel;
    YYLabel *_descLabel;
    UIImageView *_digImageView;
    UIButton *_textButton;
    unsigned long long _danmakuScene;
    AWEDanmakuModel *_danmakuModel;
}

@property (retain, nonatomic) UIView *leftContainer;
@property (retain, nonatomic) UIView *rightContainer;
@property (retain, nonatomic) UILabel *timeOffsetLabel;
@property (retain, nonatomic) YYLabel *descLabel;
@property (retain, nonatomic) UIImageView *digImageView;
@property (retain, nonatomic) UIButton *textButton;
@property (nonatomic) unsigned long long danmakuScene;
@property (retain, nonatomic) AWEDanmakuModel *danmakuModel;
@property (nonatomic) BOOL hasDigged;
@property (weak, nonatomic) id<AWELandScapeDanmakuListTableViewCellDelegate> delegate;

+ (Class)aAWEPadModuleAdapterClass;
+ (double)heightForCellWithFunctionModel:(id)arg0 danmakuScene:(unsigned long long)arg1;
+ (id)attributedString:(id)arg0 danmakuScene:(unsigned long long)arg1;
+ (id)identifier;

- (id)aAWEPadModuleAdapter;
- (id)descLabel;
- (void)setDescLabel:(id)arg0;
- (id)leftContainer;
- (id)rightContainer;
- (void)setRightContainer:(id)arg0;
- (void)setLeftContainer:(id)arg0;
- (id)digImageView;
- (void)setDigImageView:(id)arg0;
- (BOOL)hasDigged;
- (void)setHasDigged:(BOOL)arg0;
- (void)setDanmakuScene:(unsigned long long)arg0;
- (unsigned long long)danmakuScene;
- (id)danmakuModel;
- (void)setDanmakuModel:(id)arg0;
- (void)configCellWithModel:(id)arg0 danmakuScene:(unsigned long long)arg1;
- (id)timeOffsetLabel;
- (id)stringWithNSTimeInterval:(double)arg0;
- (void)digDanmaku;
- (void)clickDanmaku;
- (void)setTimeOffsetLabel:(id)arg0;
- (id)initWithStyle:(long long)arg0 reuseIdentifier:(id)arg1;
- (void).cxx_destruct;
- (id)delegate;
- (id)textButton;
- (void)setDelegate:(id)arg0;
- (void)setupUI;
- (void)setTextButton:(id)arg0;

@end
