//
//     Generated by private class-dump
//

@class NSString;

@protocol AWELeftSideBarItemContext <NSObject>

@property (readonly, copy, nonatomic) NSString *businessId;
@property (readonly, copy, nonatomic) NSString *businessType;
@property (readonly, copy, nonatomic) NSString *moduleType;
@property (readonly, copy, nonatomic) NSString *sideBarIdentifer;
@property (readonly, nonatomic) BOOL isDynamic;
@property (readonly, nonatomic) long long pageLevel;
@property (readonly, nonatomic) long long themeMode;
@property (readonly, nonatomic) long long themeType;
@property (readonly, nonatomic) double cellWidth;
@property (readonly, nonatomic) double containerCornerRadius;
@property (readonly, nonatomic) double leftSideBarWidth;
@property (readonly, nonatomic) double leftSideBarHorizontalPadding;

- (id)sideBarIdentifer;
- (long long)pageLevel;
- (long long)themeMode;
- (double)leftSideBarWidth;
- (double)leftSideBarHorizontalPadding;
- (BOOL)isDynamic;
- (id)businessType;
- (long long)themeType;
- (id)businessId;
- (id)moduleType;
- (double)cellWidth;
- (double)containerCornerRadius;

@end
