//
//     Generated by private class-dump
//

@class NSString;

@interface AWELiveAnchorStableModePushContent : NSObject {
    long long _pushType;
    NSString *_reason;
    NSString *_detail;
    NSString *_action;
}

@property (nonatomic) long long pushType;
@property (retain, nonatomic) NSString *reason;
@property (retain, nonatomic) NSString *detail;
@property (retain, nonatomic) NSString *action;

- (void)setDetail:(id)arg0;
- (void).cxx_destruct;
- (id)reason;
- (id)detail;
- (void)setAction:(id)arg0;
- (id)action;
- (void)setReason:(id)arg0;
- (void)setPushType:(long long)arg0;
- (long long)pushType;

@end
