//
//     Generated by private class-dump
//

@interface AWEListenFeedCollectAlertStatusInfo : AWEBaseApiModel {
    BOOL _listenFeedCollectStatus;
}

@property (readonly, nonatomic) BOOL listenFeedCollectStatus;

+ (id)JSONKeyPathsByPropertyKey;

- (BOOL)listenFeedCollectStatus;

@end
