//
//     Generated by private class-dump
//

@class NSString;

@interface AWELiveTinyAppPredownloadServiceImpl : NSObject <IESLiveTinyAppPredownloadService>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)ies_tinyAppPredownloadWithURL:(id)arg0 callback:(id /* block */)arg1;

@end
