//
//     Generated by private class-dump
//

@class NSString;

@interface AWELiveTrackerImpl : NSObject <IESLiveTracker>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)trackEvent:(id)arg0 params:(id)arg1;
- (void)setTrackerDelegate:(id)arg0;
- (void)trackEventWithNoLivePrefix:(id)arg0 params:(id)arg1;
- (void)vsTrackEvent:(id)arg0 params:(id)arg1;
- (void)vsTrackEvent:(id)arg0 params:(id)arg1 isLive:(BOOL)arg2;
- (void)trackADTag:(id)arg0 label:(id)arg1 extra:(id)arg2;
- (void)trackADTag:(id)arg0 label:(id)arg1 refer:(id)arg2 groupID:(id)arg3 creativeID:(id)arg4 logExtra:(id)arg5 extraParams:(id)arg6;
- (void)trackADTag:(id)arg0 label:(id)arg1 refer:(id)arg2 creativeID:(id)arg3 logExtra:(id)arg4 adID:(id)arg5 adExtraData:(id)arg6;
- (void)trackADVsEvent:(id)arg0 label:(id)arg1 refer:(id)arg2 eventType:(id)arg3 adExtraData:(id)arg4;
- (void)trackLiveRoomADLabel:(id)arg0 extra:(id)arg1;
- (BOOL)checkCanTrackAdVs:(id)arg0;

@end
