//
//     Generated by private class-dump
//

@class DUXFilter;

@interface AWELVideoLibraryFilterItemCollectionViewCell : UICollectionViewCell {
    DUXFilter *_filterItem;
}

@property (retain, nonatomic) DUXFilter *filterItem;

- (void)p_setupSubview;
- (id)filterItem;
- (void)setFilterItem:(id)arg0;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;

@end
