//
//     Generated by private class-dump
//

@class AWELiveSpeakingImage;

@interface AWELiveSpeakingImageList : NSObject {
    AWELiveSpeakingImage *_speakingImageUnknown;
    AWELiveSpeakingImage *_speakingImageMale;
    AWELiveSpeakingImage *_speakingImageFemale;
}

@property (retain, nonatomic) AWELiveSpeakingImage *speakingImageUnknown;
@property (retain, nonatomic) AWELiveSpeakingImage *speakingImageMale;
@property (retain, nonatomic) AWELiveSpeakingImage *speakingImageFemale;

- (id)speakingImageUnknown;
- (void)setSpeakingImageUnknown:(id)arg0;
- (id)speakingImageMale;
- (void)setSpeakingImageMale:(id)arg0;
- (id)speakingImageFemale;
- (void)setSpeakingImageFemale:(id)arg0;
- (void).cxx_destruct;

@end
