//
//     Generated by private class-dump
//

@interface AWEMusicStreamingImpl.BNLyricModeLineModel : _TtCs12_SwiftObject {
    void /* unknown type, empty encoding */ attributedText;
    void /* unknown type, empty encoding */ transAttributedText;
    void /* unknown type, empty encoding */ pressedColor;
    void /* unknown type, empty encoding */ normalColor;
    void /* unknown type, empty encoding */ playingColor;
    void /* unknown type, empty encoding */ status;
    void /* unknown type, empty encoding */ textTopPadding;
    void /* unknown type, empty encoding */ index;
    void /* unknown type, empty encoding */ rowWidth;
    void /* unknown type, empty encoding */ cellHeight;
    void /* unknown type, empty encoding */ originHeight;
    void /* unknown type, empty encoding */ transHeight;
    void /* unknown type, empty encoding */ delegate;
    void /* unknown type, empty encoding */ tapDelegate;
    void /* unknown type, empty encoding */ isEmptyReminder;
    void /* unknown type, empty encoding */ isLyricEmpty;
    void /* unknown type, empty encoding */ lyricType;
    void /* unknown type, empty encoding */ lineType;
    void /* unknown type, empty encoding */ words;
    void /* unknown type, empty encoding */ wordsSizes;
}

@end
