//
//     Generated by private class-dump
//

@class NSString;

@interface AWEMusicMVVideoSegInfo : MTLModel <ACCMusicMVVideoSegInfoProtocol, MTLJSONSerializing> {
    double _startTime;
    double _endTime;
    NSString *_fragmentID;
    double _cropRatio;
    NSString *_materialType;
    double _sourceDuration;
    long long _groupID;
}

@property (nonatomic) double startTime;
@property (nonatomic) double endTime;
@property (copy, nonatomic) NSString *fragmentID;
@property (nonatomic) double cropRatio;
@property (copy, nonatomic) NSString *materialType;
@property (nonatomic) double sourceDuration;
@property (nonatomic) long long groupID;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) double startTime;
@property (nonatomic) double endTime;
@property (copy, nonatomic) NSString *fragmentID;
@property (nonatomic) double cropRatio;
@property (copy, nonatomic) NSString *materialType;
@property (nonatomic) double sourceDuration;
@property (nonatomic) long long groupID;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)JSONKeyPathsByPropertyKey;

- (double)cropRatio;
- (void)setCropRatio:(double)arg0;
- (void)setSourceDuration:(double)arg0;
- (double)sourceDuration;
- (id)fragmentID;
- (void)setFragmentID:(id)arg0;
- (void)setGroupID:(long long)arg0;
- (long long)groupID;
- (void)setStartTime:(double)arg0;
- (void).cxx_destruct;
- (double)endTime;
- (double)startTime;
- (void)setEndTime:(double)arg0;
- (id)materialType;
- (void)setMaterialType:(id)arg0;

@end
