//
//     Generated by private class-dump
//

@class NSArray, NSString, AWEMusicMVTemplateRspBase;

@interface AWEMusicMVTemplateModel : MTLModel <ACCMusicMVTemplateModelProtocol, MTLJSONSerializing> {
    NSArray *_templatesInfo;
    NSArray *_musicEditsInfo;
    AWEMusicMVTemplateRspBase *_baseInfo;
}

@property (copy, nonatomic) NSArray *templatesInfo;
@property (copy, nonatomic) NSArray *musicEditsInfo;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (copy, nonatomic) NSArray *templatesInfo;
@property (copy, nonatomic) NSArray *musicEditsInfo;
@property (retain, nonatomic) AWEMusicMVTemplateRspBase *baseInfo;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)templatesInfoJSONTransformer;
+ (id)musicEditsInfoJSONTransformer;
+ (id)baseInfoJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;

- (id)templatesInfo;
- (void)setTemplatesInfo:(id)arg0;
- (id)musicEditsInfo;
- (void)setMusicEditsInfo:(id)arg0;
- (id)baseInfo;
- (void)setBaseInfo:(id)arg0;
- (void).cxx_destruct;

@end
