//
//     Generated by private class-dump
//

@class NSNumber;

@interface AWEMusicClimaxModel : AWEBaseDataModel {
    NSNumber *_startPoint;
}

@property (retain, nonatomic) NSNumber *startPoint;

+ (id)JSONKeyPathsByPropertyKey;

- (void)setStartPoint:(id)arg0;
- (void).cxx_destruct;
- (id)startPoint;

@end
