//
//     Generated by private class-dump
//

@class UIColor, NSString, UIFont, NSURL;

@interface AWEModernFeedVideoDeepQATitleFrame : NSObject {
    NSString *_titleText;
    UIColor *_textColor;
    UIColor *_backgroundColor;
    UIFont *_titleFont;
    NSURL *_iconImageURL;
    long long _type;
    struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _iconImageFrame;
    struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _titleFrame;
    struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _contanierFrame;
}

@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } iconImageFrame;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } titleFrame;
@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } contanierFrame;
@property (copy, nonatomic) NSString *titleText;
@property (retain, nonatomic) UIColor *textColor;
@property (retain, nonatomic) UIColor *backgroundColor;
@property (retain, nonatomic) UIFont *titleFont;
@property (retain, nonatomic) NSURL *iconImageURL;
@property (nonatomic) long long type;

- (void)configFrameWithModel:(id)arg0 containerWidth:(double)arg1 leftMargin:(double)arg2 rightMargin:(double)arg3;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })contanierFrame;
- (void)setContanierFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (void)setIconImageFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (void)setTitleText:(id)arg0;
- (id)init;
- (void).cxx_destruct;
- (long long)type;
- (id)titleText;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })iconImageFrame;
- (void)setType:(long long)arg0;
- (id)backgroundColor;
- (void)setTextColor:(id)arg0;
- (id)titleFont;
- (void)setBackgroundColor:(id)arg0;
- (void)setTitleFont:(id)arg0;
- (id)textColor;
- (id)iconImageURL;
- (void)setIconImageURL:(id)arg0;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })titleFrame;
- (void)setTitleFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;

@end
