//
//     Generated by private class-dump
//

@class NSDate, AWENearbyFeedbackSheet, NSString, AWEPageContext, AWEAwemeModel, AWEGradientView, CAGradientLayer, AWENearbyPOIInfoCardView, AWENearbyPOIBGView;
@protocol AWEPlayInteractionContextProtocol;

@interface AWENearbyPOIInfoCardViewController : UIViewController <AWENearbyFeedbackSheetDelegate, AWENearbyPOIInfoCardMessage, AWEFeedNearbyCardViewControllerProtocol> {
    BOOL _isShowingCardView;
    AWEAwemeModel *model;
    AWEPageContext<AWEPlayInteractionContextProtocol> *_playInteractionContext;
    AWENearbyPOIBGView *_bgView;
    AWENearbyFeedbackSheet *_feedbackSheet;
    AWENearbyPOIInfoCardView *_cardView;
    NSDate *_willDisplayDate;
    NSDate *_endDisplayDate;
    CAGradientLayer *_enhancedInfoMaskLayer;
    AWEGradientView *_topGradientView;
    AWEGradientView *_bottomGradientView;
}

@property (retain, nonatomic) AWENearbyPOIBGView *bgView;
@property (retain, nonatomic) AWENearbyFeedbackSheet *feedbackSheet;
@property (retain, nonatomic) AWENearbyPOIInfoCardView *cardView;
@property (nonatomic) BOOL isShowingCardView;
@property (retain, nonatomic) NSDate *willDisplayDate;
@property (retain, nonatomic) NSDate *endDisplayDate;
@property (retain, nonatomic) CAGradientLayer *enhancedInfoMaskLayer;
@property (retain, nonatomic) AWEGradientView *topGradientView;
@property (retain, nonatomic) AWEGradientView *bottomGradientView;
@property (weak, nonatomic) AWEPageContext<AWEPlayInteractionContextProtocol> *playInteractionContext;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (retain, nonatomic) AWEAwemeModel *model;

- (void)didDisplay;
- (id)playInteractionContext;
- (void)setPlayInteractionContext:(id)arg0;
- (void)renderModel:(id)arg0 extraParams:(id)arg1;
- (void)setFeedbackSheet:(id)arg0;
- (id)feedbackSheet;
- (void)feedbackSheet:(id)arg0 didClickItem:(id)arg1 atIndex:(long long)arg2;
- (void)setWillDisplayDate:(id)arg0;
- (void)setEndDisplayDate:(id)arg0;
- (id)endDisplayDate;
- (id)willDisplayDate;
- (void)__configCardViewWithModel:(id)arg0;
- (void)addGradientView;
- (id)enhancedInfoMaskLayer;
- (id)alphaGradientLayer;
- (void)setEnhancedInfoMaskLayer:(id)arg0;
- (void)poiInfoCardDidTapPOIWithRouteMethod:(id)arg0 model:(id)arg1 bulletType:(id)arg2;
- (void)setupMaskEnhancedNotification;
- (void)configFeedbackSheet;
- (void)onLongPressView:(id)arg0;
- (void)setIsShowingCardView:(BOOL)arg0;
- (void)updateLayoutWithModel:(id)arg0;
- (BOOL)isShowingCardView;
- (void)__startCardViewAnimation;
- (void)deleteAweme:(id)arg0;
- (id)feedbackItems;
- (void)setModel:(id)arg0;
- (void)viewDidAppear:(BOOL)arg0;
- (void).cxx_destruct;
- (id)model;
- (void)viewDidDisappear:(BOOL)arg0;
- (void)dealloc;
- (void)play;
- (void)viewDidLoad;
- (id)bgView;
- (void)setBgView:(id)arg0;
- (void)resetView;
- (id)cardView;
- (void)setCardView:(id)arg0;
- (void)didEndDisplaying;
- (id)bottomGradientView;
- (void)setBottomGradientView:(id)arg0;
- (id)topGradientView;
- (void)setTopGradientView:(id)arg0;
- (void)willDisplay;

@end
