//
//     Generated by private class-dump
//

@class NSString;

@interface AWENearbyPostLaunchInitTask : NSObject <HTSBootTask>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)trackNearbInitTaskWithStartInitTimeStamp:(double)arg0 duration:(double)arg1;
+ (void)execute;

@end
