//
//     Generated by private class-dump
//

@class NSString, NSArray;

@interface AWENearbyRelationCardModel : AWEBaseApiModel <AWENearbyInsertCardProtocol> {
    NSString *_title;
    NSString *_subTitle;
    long long _locationIndex;
    NSArray *_candidateList;
    struct CGSize { double width; double height; } _size;
}

@property (copy, nonatomic) NSString *title;
@property (copy, nonatomic) NSString *subTitle;
@property (nonatomic) long long locationIndex;
@property (copy, nonatomic) NSArray *candidateList;
@property (nonatomic) struct CGSize { double width; double height; } size;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)candidateListJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;

- (long long)indexToInsert;
- (void)setCandidateList:(id)arg0;
- (void).cxx_destruct;
- (id)candidateList;
- (id)title;
- (struct CGSize { double x0; double x1; })size;
- (void)setSize:(struct CGSize { double x0; double x1; })arg0;
- (void)setSubTitle:(id)arg0;
- (id)subTitle;
- (void)setTitle:(id)arg0;
- (long long)locationIndex;
- (void)setLocationIndex:(long long)arg0;

@end
