//
//     Generated by private class-dump
//

@class NSString;

@interface AWENewVideoCoverTextTemplateLayerChangeTextCommand : AWENewVideoCoverCommand {
    NSString *_originContent;
    NSString *_nowContent;
}

@property (copy, nonatomic) NSString *originContent;
@property (copy, nonatomic) NSString *nowContent;

- (void)setOriginContent:(id)arg0;
- (id)originContent;
- (void)realExecute;
- (void)realUnExecute;
- (id)nowContent;
- (void)setNowContent:(id)arg0;
- (void).cxx_destruct;

@end
