//
//     Generated by private class-dump
//

@class NSArray, NSDictionary, AWENaviEffectContextModel, TTKNaviModel;

@interface AWENaviFetchEffectsResult : NSObject {
    TTKNaviModel *_avatar;
    AWENaviEffectContextModel *_contextModel;
    NSArray *_others;
    NSDictionary *_effectNameToEffectMapping;
}

@property (retain, nonatomic) TTKNaviModel *avatar;
@property (retain, nonatomic) AWENaviEffectContextModel *contextModel;
@property (copy, nonatomic) NSArray *others;
@property (copy, nonatomic) NSDictionary *effectNameToEffectMapping;

- (void)setContextModel:(id)arg0;
- (void)setEffectNameToEffectMapping:(id)arg0;
- (id)effectNameToEffectMapping;
- (id)contextModel;
- (void).cxx_destruct;
- (id)others;
- (id)avatar;
- (void)setAvatar:(id)arg0;
- (void)setOthers:(id)arg0;

@end
