//
//     Generated by private class-dump
//

@class NSString;

@interface AWENetworkProviderLayer.CodeGenV1WannaCardNetworkProvider : AWEDataLayerRootModelGetMethodNetworkProvider {
    void /* unknown type, empty encoding */ firstRefresh;
    void /* unknown type, empty encoding */ connectStrategy;
    void /* unknown type, empty encoding */ wannaCardType;
    void /* unknown type, empty encoding */ isClientCondition;
    void /* unknown type, empty encoding */ pullType;
}

@property (nonatomic) void /* unknown type, empty encoding */ firstRefresh;
@property (nonatomic, copy) NSString *connectStrategy;
@property (nonatomic) void /* unknown type, empty encoding */ wannaCardType;
@property (nonatomic) void /* unknown type, empty encoding */ isClientCondition;
@property (nonatomic) void /* unknown type, empty encoding */ pullType;

+ (id)businessURI;

- (long long)pullType;
- (void)setPullType:(long long)arg0;
- (id)networkDomain;
- (id)networkURLPath;
- (id)networkParams;
- (BOOL)firstRefresh;
- (void)setFirstRefresh:(BOOL)arg0;
- (id)connectStrategy;
- (void)setConnectStrategy:(id)arg0;
- (unsigned long long)wannaCardType;
- (void)setWannaCardType:(unsigned long long)arg0;
- (long long)isClientCondition;
- (void)setIsClientCondition:(long long)arg0;
- (id)init;
- (void).cxx_destruct;
- (Class)modelClass;

@end
