//
//     Generated by private class-dump
//

@class NSMutableDictionary, NSString, AWEAwemeModel, AWEDanmakuDataManager;
@protocol AWEPlayInteractionDanmakuControllerViewModelDelegate;

@interface AWEPlayInteractionDanmakuControllerViewModel : NSObject <AWEDanmakuDataManagerDelegate> {
    id<AWEPlayInteractionDanmakuControllerViewModelDelegate> _delegate;
    AWEAwemeModel *_model;
    NSString *_enterFrom;
    NSString *_previousPage;
    AWEDanmakuDataManager *_danmakuManager;
    long long _danamkuScene;
    long long _sceneType;
    NSMutableDictionary *_danmakuCountMap;
}

@property (retain, nonatomic) AWEDanmakuDataManager *danmakuManager;
@property (nonatomic) long long danamkuScene;
@property (nonatomic) long long sceneType;
@property (retain, nonatomic) NSMutableDictionary *danmakuCountMap;
@property (retain, nonatomic) AWEAwemeModel *model;
@property (weak, nonatomic) id<AWEPlayInteractionDanmakuControllerViewModelDelegate> delegate;
@property (copy, nonatomic) NSString *enterFrom;
@property (copy, nonatomic) NSString *previousPage;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)setEnterFrom:(id)arg0;
- (id)enterFrom;
- (void)stopDanmaku;
- (id)danmakuCountWithModel:(id)arg0;
- (void)playerSeeked;
- (id)getRequestLogID:(id)arg0;
- (void)activateDanmaku;
- (void)deactivateDanmaku;
- (void)didReceivedNewData:(id)arg0;
- (void)didReceivedAppendData:(id)arg0;
- (void)didFailedWithError:(id)arg0;
- (void)didSendDataRequestFrom:(double)arg0;
- (void)didReceivedDataFrom:(double)arg0 endTime:(double)arg1;
- (id)initWithScene:(long long)arg0 sceneType:(long long)arg1;
- (void)sendWithParams:(id)arg0 completion:(id /* block */)arg1;
- (void)clearDanmakuForRefresh;
- (void)fetchDanmakuWithItemId:(id)arg0 danmakuIds:(id)arg1 completion:(id /* block */)arg2;
- (double)videoPlayOffset;
- (void)didGetDanmakuTotalCount:(long long)arg0 awemeModel:(id)arg1;
- (id)danmakuManager;
- (id)danmakuCountMap;
- (void)setDanmakuManager:(id)arg0;
- (long long)danamkuScene;
- (void)setDanamkuScene:(long long)arg0;
- (void)setDanmakuCountMap:(id)arg0;
- (void)setModel:(id)arg0;
- (void).cxx_destruct;
- (id)model;
- (id)delegate;
- (void)setDelegate:(id)arg0;
- (void)reset;
- (id)previousPage;
- (void)setPreviousPage:(id)arg0;
- (long long)sceneType;
- (void)setSceneType:(long long)arg0;
- (void)updateModel:(id)arg0;
- (double)videoPlayRate;

@end
