//
//     Generated by private class-dump
//

@class NSString;

@protocol AWEProfileTabItemProtocol <NSObject>

@property (copy, nonatomic) NSString *title;
@property (nonatomic) unsigned long long count;
@property (nonatomic) BOOL showLock;
@property (nonatomic) BOOL showRedDot;
@property (copy, nonatomic) NSString *redDotAccessibilityText;

- (BOOL)showRedDot;
- (void)setShowRedDot:(BOOL)arg0;
- (id)redDotAccessibilityText;
- (void)setRedDotAccessibilityText:(id)arg0;
- (void)setCount:(unsigned long long)arg0;
- (id)title;
- (unsigned long long)count;
- (void)setTitle:(id)arg0;
- (void)setShowLock:(BOOL)arg0;
- (BOOL)showLock;

@end
