//
//     Generated by private class-dump
//

@class NSArray, NSString;

@interface AWEPastMemoriesResponseModel : MTLModel <MTLJSONSerializing> {
    BOOL _hasMore;
    NSArray *_awemeModels;
    long long _cursor;
    long long _total;
}

@property (retain, nonatomic) NSArray *awemeModels;
@property (nonatomic) long long cursor;
@property (nonatomic) BOOL hasMore;
@property (nonatomic) long long total;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)awemeModelsJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;

- (id)awemeModels;
- (void)setAwemeModels:(id)arg0;
- (long long)cursor;
- (long long)total;
- (void).cxx_destruct;
- (void)setHasMore:(BOOL)arg0;
- (BOOL)hasMore;
- (void)setCursor:(long long)arg0;
- (void)setTotal:(long long)arg0;

@end
