//
//     Generated by private class-dump
//

@class AWEVideoPublishViewModel;

@interface AWEPublishModelFlowHandle : NSObject {
    AWEVideoPublishViewModel *_publishModel;
}

@property (retain, nonatomic) AWEVideoPublishViewModel *publishModel;

- (id)publishModel;
- (void)setPublishModel:(id)arg0;
- (void)saveHashtagWithPublishState:(BOOL)arg0;
- (void)saveOrignalDraftWithCompletion:(id /* block */)arg0;
- (void)publishStep;
- (void)savePollStickerInfos;
- (void)saveDraftWithBackup:(BOOL)arg0 completion:(id /* block */)arg1;
- (BOOL)isLivePlayBack;
- (BOOL)isShowToastHashTagCountLimitIfNeeded;
- (void)configForStoryWithTitlePreserve:(BOOL)arg0;
- (void)configMusickSelectedFrom;
- (void)configCommon;
- (void)setHashtagFlag;
- (void)setItemDonwloadAllPeople;
- (BOOL)publishShouldShowRedPacketAlert;
- (void)markPublishRedPacketAlertShowed;
- (void)addCurrentLocationInfoWithShowPOI:(BOOL)arg0;
- (BOOL)publishRedPacketDateValid;
- (BOOL)p_isRedpacketTaskAcitivity:(id)arg0;
- (id)initWithModel:(id)arg0;
- (void).cxx_destruct;

@end
