//
//     Generated by private class-dump
//

@class AWEPOIModalViewPanGestureRecognizer, UIScrollView, DitoPageContext;
@protocol AWEPOIModalViewDelegateProtocol;

@protocol AWEPOIModalViewManagerProtocol <NSObject, UIScrollViewDelegate>

@property (weak, nonatomic) DitoPageContext *context;
@property (weak, nonatomic) id<AWEPOIModalViewDelegateProtocol> mvManagerDelegate;
@property (readonly, nonatomic) AWEPOIModalViewPanGestureRecognizer *mvStatePanGes;
@property (readonly, nonatomic) long long modalViewState;
@property (weak, nonatomic) UIScrollView *scrollView;
@property (nonatomic) double speedLimitForVertical;
@property (nonatomic) double speedLimitForHorizontal;
@property (readonly, nonatomic) double currentModalViewRatio;
@property (nonatomic) struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; } currentFrame;
@property (nonatomic) double placeHolderHeight;
@property (nonatomic) double tapViewBottomValue;
@property (nonatomic) BOOL shouldUnLockScrollInHalfState;

- (long long)modalViewState;
- (double)currentModalViewRatio;
- (double)modalViewOffsetForModalViewRatio:(double)arg0;
- (BOOL)isFirstComponentVisible;
- (double)convertRatioByOriginY:(double)arg0;
- (void)showAsModalViewWithRatio:(double)arg0;
- (double)convertOriginYByRatio:(double)arg0;
- (void)forbidContentInteraction;
- (void)prepareToDismiss;
- (void)resumeContentInteraction;
- (void)collapseToModalView;
- (void)expandToFullScreen;
- (void)setTapViewBottomValue:(double)arg0;
- (id)mvManagerDelegate;
- (double)tapViewBottomValue;
- (void)setMvManagerDelegate:(id)arg0;
- (void)setShouldUnLockScrollInHalfState:(BOOL)arg0;
- (id)mvStatePanGes;
- (double)speedLimitForHorizontal;
- (double)speedLimitForVertical;
- (double)placeHolderHeight;
- (BOOL)shouldUnLockScrollInHalfState;
- (void)setSpeedLimitForVertical:(double)arg0;
- (void)setSpeedLimitForHorizontal:(double)arg0;
- (void)setPlaceHolderHeight:(double)arg0;
- (void)setScrollView:(id)arg0;
- (void)setContext:(id)arg0;
- (id)context;
- (id)scrollView;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })currentFrame;
- (void)setCurrentFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;

@end
