//
//     Generated by private class-dump
//

@class NSArray;

@interface AWEPLVFilterHeaderModel : AWEBaseApiModel {
    NSArray *_filterList;
}

@property (retain, nonatomic) NSArray *filterList;

+ (id)filterListJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;

- (id)filterList;
- (void)setFilterList:(id)arg0;
- (void).cxx_destruct;

@end
