//
//     Generated by private class-dump
//

@interface AWEPOIRouterParamsVerifyManager : AWEPOIParamsVerifyManager

+ (id)shareManager;

- (void)reloadConfig;
- (void)verifyForKey:(id)arg0 params:(id)arg1;

@end
