//
//     Generated by private class-dump
//

@class NSString, AWEURLModel;

@interface AWEPOIDetailQualityModel : MTLModel <MTLJSONSerializing> {
    NSString *_title;
    AWEURLModel *_entranceIconURL;
    NSString *_desc;
    long long _score;
    NSString *_rankCode;
    long long _qualityRank;
    AWEURLModel *_rankIconURL;
    NSString *_rankLinkDesc;
    NSString *_rankSchema;
    long long _rankType;
}

@property (copy, nonatomic) NSString *title;
@property (retain, nonatomic) AWEURLModel *entranceIconURL;
@property (copy, nonatomic) NSString *desc;
@property (nonatomic) long long score;
@property (copy, nonatomic) NSString *rankCode;
@property (nonatomic) long long qualityRank;
@property (retain, nonatomic) AWEURLModel *rankIconURL;
@property (copy, nonatomic) NSString *rankLinkDesc;
@property (copy, nonatomic) NSString *rankSchema;
@property (nonatomic) long long rankType;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)JSONKeyPathsByPropertyKey;

- (id)rankSchema;
- (void)setRankSchema:(id)arg0;
- (id)rankCode;
- (void)setRankCode:(id)arg0;
- (id)entranceIconURL;
- (void)setEntranceIconURL:(id)arg0;
- (long long)qualityRank;
- (void)setQualityRank:(long long)arg0;
- (id)rankIconURL;
- (void)setRankIconURL:(id)arg0;
- (id)rankLinkDesc;
- (void)setRankLinkDesc:(id)arg0;
- (id)desc;
- (void)setScore:(long long)arg0;
- (long long)score;
- (void).cxx_destruct;
- (void)setRankType:(long long)arg0;
- (id)title;
- (void)setDesc:(id)arg0;
- (void)setTitle:(id)arg0;
- (long long)rankType;

@end
