//
//     Generated by private class-dump
//

@class NSString, NSObject;
@protocol AWEPostPageContext;

@interface AWEPostPageStarAtlasHandler : NSObject <AWEPostPageStarAtlasService> {
    BOOL isStarRequestFinish;
    id<AWEPostPageContext> _context;
    id didUpdateStarAtlasTypeSignal;
    long long cleanStarAtlasDraftSignal;
    NSObject *requestStarAtlasOrdersSignal;
}

@property (retain, nonatomic) NSObject *requestStarAtlasOrdersSignal;
@property (retain, nonatomic) id didUpdateStarAtlasTypeSignal;
@property (nonatomic) long long cleanStarAtlasDraftSignal;
@property (nonatomic) BOOL isStarRequestFinish;
@property (readonly, nonatomic) id<AWEPostPageContext> context;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)_aweLazyRegisterPostPage;

- (void)bindServices:(id)arg0;
- (BOOL)isStarRequestFinish;
- (id)requestStarAtlasOrdersSignal;
- (id)didUpdateStarAtlasTypeSignal;
- (void)setDidUpdateStarAtlasTypeSignal:(id)arg0;
- (long long)cleanStarAtlasDraftSignal;
- (void)setCleanStarAtlasDraftSignal:(long long)arg0;
- (void)setIsStarRequestFinish:(BOOL)arg0;
- (void)sendRequestStarAtlasOrdersSignal:(unsigned long long)arg0 model:(id)arg1 error:(id)arg2;
- (void)setRequestStarAtlasOrdersSignal:(id)arg0;
- (void).cxx_destruct;
- (id)context;

@end
