//
//     Generated by private class-dump
//

@class NSString, AWEDitoPOIMallPageContext, UIView, UITableView;
@protocol AWEDitoPOIMallTableViewFilterContentViewDelegate;

@interface AWEPOIDetailNGPOIMallFilterContentView : UIView <UITableViewDelegate, UITableViewDataSource, UIGestureRecognizerDelegate> {
    id<AWEDitoPOIMallTableViewFilterContentViewDelegate> _delegate;
    id /* block */ _didDismissBlock;
    UITableView *_l2AreaTableView;
    UITableView *_l3AreaTableView;
    UIView *_maskView;
    UIView *_contentView;
    AWEDitoPOIMallPageContext *_context;
    double _componentHeight;
}

@property (copy, nonatomic) id /* block */ didDismissBlock;
@property (retain, nonatomic) UITableView *l2AreaTableView;
@property (retain, nonatomic) UITableView *l3AreaTableView;
@property (retain, nonatomic) UIView *maskView;
@property (retain, nonatomic) UIView *contentView;
@property (retain, nonatomic) AWEDitoPOIMallPageContext *context;
@property (nonatomic) double componentHeight;
@property (weak, nonatomic) id<AWEDitoPOIMallTableViewFilterContentViewDelegate> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id /* block */)didDismissBlock;
- (void)setDidDismissBlock:(id /* block */)arg0;
- (void)presentFilterFromContainer:(id)arg0 anchorView:(id)arg1 animated:(BOOL)arg2 animatedBlock:(id /* block */)arg3;
- (void)dismissFilterAnimated:(BOOL)arg0 animatedBlock:(id /* block */)arg1;
- (id)l2AreaTableView;
- (id)l3AreaTableView;
- (void)setL2AreaTableView:(id)arg0;
- (void)setL3AreaTableView:(id)arg0;
- (void)setComponentHeight:(double)arg0;
- (double)componentHeight;
- (void)reloadTableview;
- (void)resetL2TableSelected;
- (id)init;
- (void)tableView:(id)arg0 willDisplayCell:(id)arg1 forRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg0;
- (void)tableView:(id)arg0 didSelectRowAtIndexPath:(id)arg1;
- (long long)tableView:(id)arg0 numberOfRowsInSection:(long long)arg1;
- (void).cxx_destruct;
- (void)setContext:(id)arg0;
- (id)tableView:(id)arg0 cellForRowAtIndexPath:(id)arg1;
- (id)maskView;
- (id)contentView;
- (id)delegate;
- (id)context;
- (void)setDelegate:(id)arg0;
- (void)setMaskView:(id)arg0;
- (void)setContentView:(id)arg0;
- (void)setupUI;
- (void)dismissView;
- (void)updateContext:(id)arg0;

@end
