//
//     Generated by private class-dump
//

@class AWEPOIDetailInfoSimilarPOIShareViewModel, NSArray, NSDictionary, NSString;

@interface AWEPOIDetailoNGSharePOIComponentViewModel : DitoComponentViewModel <AWEPOIDetailInfoSimilarPOIShareDelegate> {
    AWEPOIDetailInfoSimilarPOIShareViewModel *_bizViewModel;
    NSArray *_conversationUsers;
    NSDictionary *_nodeData;
}

@property (copy, nonatomic) NSArray *conversationUsers;
@property (retain, nonatomic) NSDictionary *nodeData;
@property (retain, nonatomic) AWEPOIDetailInfoSimilarPOIShareViewModel *bizViewModel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (struct CGSize { double x0; double x1; })componentSizeWithMaxWidth:(double)arg0;
- (void)bindStateAndAction;
- (void)didTapColletGuide;
- (id)conversationUsers;
- (id)bizViewModel;
- (void)setBizViewModel:(id)arg0;
- (void)setupBizViewModel;
- (id)currentNodeData;
- (void)setConversationUsers:(id)arg0;
- (void).cxx_destruct;
- (id)initWithNode:(id)arg0;
- (id)nodeData;
- (void)setNodeData:(id)arg0;
- (void)didTapShare;

@end
