//
//     Generated by private class-dump
//

@class ACCCameraSubscription, NSString;

@interface AWEPOIStickerServiceImpl : NSObject <AWEPOIStickerService> {
    ACCCameraSubscription *_subscription;
}

@property (retain, nonatomic) ACCCameraSubscription *subscription;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)didAddPOIStickerWithLocationModel:(id)arg0;
- (void).cxx_destruct;
- (void)setSubscription:(id)arg0;
- (void)addSubscriber:(id)arg0;
- (id)subscription;

@end
