//
//     Generated by private class-dump
//

@class AWEPOICityLiveComponentView, NSString, NSArray, AWEAwemeModel;

@interface AWEPOICityLiveComponentViewModel : DitoComponentViewModel <AWEPOIDetailNGAutoPlayUtilObjectProtocol, AWEPOISyncFeedExtensionGetModelProtocol, AWEPOIDetailNGViewModelZoomTransitionProtocol> {
    BOOL _firstTimeShow;
    AWEAwemeModel *_aweme;
    AWEPOICityLiveComponentView *_cell;
    NSString *_statusLabelText;
    NSString *_statusDetailIconImageName;
    NSString *_statusDetailLabelText;
    NSArray *_coverImagURLList;
    NSArray *_userAvatarImageURLList;
    NSString *_userNikenameText;
    NSString *_contentText;
    NSString *_liveStreamData;
    NSString *_liveStreamURL;
    double _height;
}

@property (nonatomic) double height;
@property (nonatomic) BOOL firstTimeShow;
@property (readonly, nonatomic) BOOL isInLiveTab;
@property (readonly, nonatomic) AWEAwemeModel *aweme;
@property (weak, nonatomic) AWEPOICityLiveComponentView *cell;
@property (readonly, copy, nonatomic) NSString *statusLabelText;
@property (readonly, copy, nonatomic) NSString *statusDetailIconImageName;
@property (readonly, copy, nonatomic) NSString *statusDetailLabelText;
@property (readonly, nonatomic) NSArray *coverImagURLList;
@property (readonly, nonatomic) NSArray *userAvatarImageURLList;
@property (readonly, copy, nonatomic) NSString *userNikenameText;
@property (readonly, copy, nonatomic) NSString *contentText;
@property (readonly, copy, nonatomic) NSString *liveStreamData;
@property (readonly, copy, nonatomic) NSString *liveStreamURL;
@property (readonly, nonatomic) BOOL shouldAutoPlay;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (double)coverImageHWRatio;

- (id)aweme;
- (void)canEnterLiveRoom:(id /* block */)arg0;
- (id)liveStreamURL;
- (void)enterLiveRoom;
- (id)playerCell;
- (id)getAwemeModel;
- (id)liveStreamData;
- (id)constData;
- (id)generalContext;
- (struct CGSize { double x0; double x1; })componentSizeWithMaxWidth:(double)arg0;
- (id)syncFeedManager;
- (double)labelContentHeightWithString:(id)arg0 maxWidth:(double)arg1;
- (id)zoomTransitionView;
- (id)coverImagURLList;
- (id)userNikenameText;
- (id)statusLabelText;
- (id)statusDetailLabelText;
- (id)statusDetailIconImageName;
- (id)userAvatarImageURLList;
- (BOOL)isInLiveTab;
- (BOOL)firstTimeShow;
- (void)setFirstTimeShow:(BOOL)arg0;
- (void)trackFirstShowEvent;
- (void)componentViewWillShow;
- (void)componentViewDidEndShow;
- (void).cxx_destruct;
- (double)height;
- (id)initWithNode:(id)arg0;
- (void)setHeight:(double)arg0;
- (id)cell;
- (void)setCell:(id)arg0;
- (id)contentText;
- (unsigned long long)indexInGroup;
- (BOOL)shouldAutoPlay;

@end
