//
//     Generated by private class-dump
//

@class NSArray, NSString;
@protocol AWEPostPageContext;

@interface AWEPostPageGameCPHandler : NSObject <AWEPostPageGameCPService> {
    id<AWEPostPageContext> _context;
    NSArray *_gameCPAddHashTagNameSignal;
}

@property (retain, nonatomic) NSArray *gameCPAddHashTagNameSignal;
@property (readonly, nonatomic) id<AWEPostPageContext> context;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)_aweLazyRegisterPostPage;

- (void)bindServices:(id)arg0;
- (void)reportMultiAnchorSelectPanelShowTracker;
- (void)sendGameCPAddHashTagNameSignal:(id)arg0;
- (void)reportTrackerWithEvent:(id)arg0 extra:(id)arg1;
- (id)gameCPHashTagsStringWithList:(id)arg0 resolveHashTagNames:(id)arg1 maxHashTagLimit:(long long)arg2;
- (id)gameCPAddHashTagNameSignal;
- (void)setGameCPAddHashTagNameSignal:(id)arg0;
- (id)p_gameCPHashTagsStringWithHashTagList:(id)arg0 countLimit:(long long)arg1;
- (void).cxx_destruct;
- (id)context;

@end
