//
//     Generated by private class-dump
//

@protocol AWEPadBizUIAdapter <NSObject>

- (void)pushUI:(id)arg0 adaptWidthconstraint:(id)arg1;
- (BOOL)enablePanelUIAdapted;
- (void)performPadUIAdapterExecution:(id /* block */)arg0;
- (BOOL)enableAutoRotation;

@end
