//
//     Generated by private class-dump
//

@class AWEPOICommonModalViewController, UIView;
@protocol AWEPOIModalContentDelegate;

@protocol AWEPOICommonModalCustomContentProtocol <NSObject>

@property (readonly, nonatomic) UIView *contentView;
@property (weak, nonatomic) id<AWEPOIModalContentDelegate> modalContentDelegate;
@property (weak, nonatomic) AWEPOICommonModalViewController *modalVC;

- (void)enableContentScroll;
- (void)disableContentScroll;
- (id)contentView;
- (struct CGPoint { double x0; double x1; })currentContentOffset;

@optional

- (void)stopLoadingView;
- (void)setModalContentDelegate:(id)arg0;
- (void)setModalVC:(id)arg0;
- (void)willChangeToModalPageSize:(id)arg0 currentFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg1;
- (void)contentOffsetYDidChangeTo:(double)arg0;
- (id)modalVC;
- (id)modalContentDelegate;
- (void)reload;
- (void)addEmptyListView;

@end
