//
//     Generated by private class-dump
//

@class AFDRadarActivityModel, UIImageView, UILabel, UIView, MASConstraint;

@interface AWERadarActivityBannerViewController : UIViewController {
    BOOL _isAppear;
    BOOL _hasShownGuide;
    UIView *_bannerView;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    UIImageView *_activityImageView;
    UIImageView *_arrowImageView;
    UIView *_lineView;
    MASConstraint *_showConstraint;
    MASConstraint *_hideConstraint;
    MASConstraint *_bannerHeightConstraint;
    MASConstraint *_highligntedBannerHeightConstraint;
    AFDRadarActivityModel *_model;
}

@property (retain, nonatomic) UILabel *titleLabel;
@property (retain, nonatomic) UILabel *descLabel;
@property (retain, nonatomic) UIImageView *activityImageView;
@property (retain, nonatomic) UIImageView *arrowImageView;
@property (retain, nonatomic) UIView *lineView;
@property (retain, nonatomic) MASConstraint *showConstraint;
@property (retain, nonatomic) MASConstraint *hideConstraint;
@property (retain, nonatomic) MASConstraint *bannerHeightConstraint;
@property (retain, nonatomic) MASConstraint *highligntedBannerHeightConstraint;
@property (nonatomic) BOOL isAppear;
@property (nonatomic) BOOL hasShownGuide;
@property (retain, nonatomic) AFDRadarActivityModel *model;
@property (retain, nonatomic) UIView *bannerView;

- (id)descLabel;
- (void)setDescLabel:(id)arg0;
- (BOOL)isAppear;
- (void)setIsAppear:(BOOL)arg0;
- (void)setShowConstraint:(id)arg0;
- (void)setHideConstraint:(id)arg0;
- (id)hideConstraint;
- (id)showConstraint;
- (double)bannerMaxHeight;
- (BOOL)p_hasValidBanner;
- (double)p_bannerHeight;
- (void)setBannerHeightConstraint:(id)arg0;
- (void)setHighligntedBannerHeightConstraint:(id)arg0;
- (id)highligntedBannerHeightConstraint;
- (void)p_openActivitySchema;
- (void)p_showActivityGuideIfNeeded;
- (BOOL)hasShownGuide;
- (void)setHasShownGuide:(BOOL)arg0;
- (id)bannerHeightConstraint;
- (BOOL)p_checkActivityEnaleShake;
- (void)updateWithActivityModel:(id)arg0;
- (void)setModel:(id)arg0;
- (void)viewDidAppear:(BOOL)arg0;
- (void).cxx_destruct;
- (id)model;
- (id)titleLabel;
- (void)viewDidLoad;
- (void)setTitleLabel:(id)arg0;
- (id)lineView;
- (void)setLineView:(id)arg0;
- (void)setupUI;
- (id)bannerView;
- (void)setBannerView:(id)arg0;
- (id)activityImageView;
- (void)setActivityImageView:(id)arg0;
- (id)arrowImageView;
- (void)setArrowImageView:(id)arg0;

@end
