//
//     Generated by private class-dump
//

@class RxTwoTuple, UIViewController, NSString;
@protocol RTVRootFeedObserver, RTVMultipleDelegateInterface, RxInjector, AWEFeedContainerViewControllerProtocol, AWEFamiliarViewControllerProtocol;

@interface AWERTVRootFeedObserverCenter : NSObject <AWEAudioFocusProtocol, RTVRootFeedObserverCenterInterface> {
    BOOL _currentInFeed;
    id<RTVMultipleDelegateInterface, RTVRootFeedObserver> _observers;
    id<RxInjector> _injector;
    RxTwoTuple *_observeToken;
    UIViewController<AWEFeedContainerViewControllerProtocol> *_feedDataSource;
    UIViewController<AWEFamiliarViewControllerProtocol> *_familiarDataSource;
}

@property (readonly, nonatomic) id<RTVMultipleDelegateInterface, RTVRootFeedObserver> observers;
@property (readonly, weak, nonatomic) id<RxInjector> injector;
@property (retain, nonatomic) RxTwoTuple *observeToken;
@property (retain, nonatomic) UIViewController<AWEFeedContainerViewControllerProtocol> *feedDataSource;
@property (retain, nonatomic) UIViewController<AWEFamiliarViewControllerProtocol> *familiarDataSource;
@property (nonatomic) BOOL currentInFeed;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)rxAwakeFromPropertyInjection;
- (BOOL)audioIsPlaying;
- (void)audioPause;
- (void)notifyPlayerStartPlay:(id)arg0;
- (id)currentPlayingAweme;
- (void)__configFeedTabObserver;
- (void)__handleFeedContainerViewWillAppear:(id)arg0;
- (void)__handleFeedContainerViewWillDisappear:(id)arg0;
- (void)__handleFamiliarContainerWillAppear:(id)arg0;
- (void)__handleFamiliarContainerWillDisappear:(id)arg0;
- (id)feedDataSource;
- (id)familiarDataSource;
- (BOOL)currentInFeed;
- (void)__updateCurrentInFeed:(BOOL)arg0;
- (id)observeToken;
- (void)__invalidObserverToken;
- (void)__observeFeedContainerViewController:(id)arg0;
- (void)__observeFamiliarContainerViewController:(id)arg0;
- (void)__updateWithFeedDataSource:(id)arg0 faimiliarDataSource:(id)arg1;
- (void)setObserveToken:(id)arg0;
- (void)setFeedDataSource:(id)arg0;
- (void)setFamiliarDataSource:(id)arg0;
- (void)__doUpdateCurrentInFeed:(id)arg0;
- (void)setCurrentInFeed:(BOOL)arg0;
- (void).cxx_destruct;
- (id)observers;
- (id)injector;
- (void)addObserver:(id)arg0;
- (void)removeObserver:(id)arg0;

@end
