//
//     Generated by private class-dump
//

@class NSString, UIImageView, UILabel, UIView;

@interface AWERelationFollowGroupEntranceView : UIView <AWEFollowRelationGroupMessage, AWERelationFollowGroupEntranceProtocol> {
    BOOL _isAppear;
    UIView *_contentBgView;
    UIView *_iconBgView;
    UIImageView *_iconImage;
    UILabel *_titleLabel;
    UILabel *_countLabel;
    UIImageView *_arrowImage;
    UIView *_bottomLine;
    long long _groupCount;
}

@property (retain, nonatomic) UIView *contentBgView;
@property (retain, nonatomic) UIView *iconBgView;
@property (retain, nonatomic) UIImageView *iconImage;
@property (retain, nonatomic) UILabel *titleLabel;
@property (retain, nonatomic) UILabel *countLabel;
@property (retain, nonatomic) UIImageView *arrowImage;
@property (retain, nonatomic) UIView *bottomLine;
@property (nonatomic) long long groupCount;
@property (nonatomic) BOOL isAppear;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (BOOL)isAppear;
- (void)setIsAppear:(BOOL)arg0;
- (id)iconBgView;
- (void)setIconBgView:(id)arg0;
- (void)didFinishCreateGroup:(id)arg0 groupName:(id)arg1;
- (void)didFinishDeleteGroup:(id)arg0;
- (void)setupGroupCount:(long long)arg0;
- (double)userIconWidth;
- (void)viewClick;
- (id)contentBgView;
- (void)setContentBgView:(id)arg0;
- (id)iconImage;
- (id)init;
- (void).cxx_destruct;
- (id)titleLabel;
- (long long)groupCount;
- (void)setGroupCount:(long long)arg0;
- (void)dealloc;
- (void)setTitleLabel:(id)arg0;
- (void)setIconImage:(id)arg0;
- (id)countLabel;
- (void)setCountLabel:(id)arg0;
- (void)_setupView;
- (id)arrowImage;
- (void)setArrowImage:(id)arg0;
- (id)bottomLine;
- (void)setBottomLine:(id)arg0;
- (double)suggestedHeight;

@end
