//
//     Generated by private class-dump
//

@class NSString, UIImageView, AWERelationFollowCleanAvatarContainer, UILabel, UIView;

@interface AWERelationFollowCleanEntranceView : UIView <AWERelationFollowCleanEntranceProtocol> {
    BOOL _isAppear;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    UILabel *_numLabel;
    UIImageView *_arrowImage;
    AWERelationFollowCleanAvatarContainer *_avatorImageContainer;
    UIView *_bottomLine;
}

@property (retain, nonatomic) UILabel *titleLabel;
@property (retain, nonatomic) UILabel *subTitleLabel;
@property (retain, nonatomic) UILabel *numLabel;
@property (retain, nonatomic) UIImageView *arrowImage;
@property (retain, nonatomic) AWERelationFollowCleanAvatarContainer *avatorImageContainer;
@property (retain, nonatomic) UIView *bottomLine;
@property (nonatomic) BOOL isAppear;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (BOOL)isAppear;
- (void)setIsAppear:(BOOL)arg0;
- (double)userIconWidth;
- (void)viewClick;
- (BOOL)isStylyA;
- (id)avatorImageContainer;
- (id)numLabel;
- (void)setStyleAConstraint;
- (void)setStyleBConstraint;
- (void)setNumLabel:(id)arg0;
- (void)setAvatorImageContainer:(id)arg0;
- (id)init;
- (void).cxx_destruct;
- (id)titleLabel;
- (void)setTitleLabel:(id)arg0;
- (void)setupView;
- (id)subTitleLabel;
- (void)setSubTitleLabel:(id)arg0;
- (id)arrowImage;
- (void)setArrowImage:(id)arg0;
- (id)bottomLine;
- (void)setBottomLine:(id)arg0;
- (void)setupModel:(id)arg0;
- (double)suggestedHeight;

@end
