//
//     Generated by private class-dump
//

@interface AWERouterActivityAbilityInfo : AWERouterAbilityInfo

- (void)abilityAssemblyWithCompletion:(id /* block */)arg0;
- (void)p_videoDiaryAssembly;

@end
