//
//     Generated by private class-dump
//

@class NSString;

@interface AWERecordLiveModeResult : NSObject {
    BOOL _shouldShow;
    NSString *_reason;
}

@property (nonatomic) BOOL shouldShow;
@property (retain, nonatomic) NSString *reason;

- (void).cxx_destruct;
- (id)reason;
- (void)setReason:(id)arg0;
- (BOOL)shouldShow;
- (void)setShouldShow:(BOOL)arg0;

@end
