//
//     Generated by private class-dump
//

@class UITapGestureRecognizer, AWESnackBarViewContext, UIImageView, UILabel, UIButton;

@interface AWESnackBarView : UIView {
    UIImageView *_iconImageView;
    UILabel *_title;
    UIButton *_rightBtn;
    UITapGestureRecognizer *_tapGes;
    AWESnackBarViewContext *_context;
}

@property (retain, nonatomic) UIImageView *iconImageView;
@property (retain, nonatomic) UILabel *title;
@property (retain, nonatomic) UIButton *rightBtn;
@property (retain, nonatomic) UITapGestureRecognizer *tapGes;
@property (retain, nonatomic) AWESnackBarViewContext *context;

- (void)initSubViews;
- (id)rightBtn;
- (void)setRightBtn:(id)arg0;
- (id)tapGes;
- (void)setTapGes:(id)arg0;
- (void)didClickedSnackBar;
- (void)dismissSnackBarAnimated:(BOOL)arg0;
- (void)showSnackBarAnimated:(BOOL)arg0;
- (void)dismissSnackBarIfNeeded;
- (void)p_rightBtnDidPressed;
- (void)showSnackBarAfterDismissOnView:(id)arg0 oldContext:(id)arg1;
- (void)updateSnackBarShowingStatus:(BOOL)arg0 newContext:(id)arg1 oldContext:(id)arg2;
- (id)init;
- (void).cxx_destruct;
- (void)setContext:(id)arg0;
- (id)title;
- (id)context;
- (void)reset;
- (id)iconImageView;
- (void)setTitle:(id)arg0;
- (void)setIconImageView:(id)arg0;
- (void)updateWithContext:(id)arg0;

@end
