//
//     Generated by private class-dump
//

@class NSString, NSDictionary, AWEShareSaveAlbumDataCenter, UITableView;

@interface AWEShareSaveAlbumViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, AWEShareSaveAlbumDataCenterDelegate, AWEShareActionCellDelegate, AWEIMHalfScreenContainerScrollProtocol, AWEIMHalfScreenContainerVCDelegate, AWEShareSaveTableViewCellDelegate> {
    NSDictionary *_context;
    UITableView *_tableView;
    AWEShareSaveAlbumDataCenter *_dataCenter;
    id /* block */ _shareCompletion;
}

@property (copy, nonatomic) NSDictionary *context;
@property (retain, nonatomic) UITableView *tableView;
@property (retain, nonatomic) AWEShareSaveAlbumDataCenter *dataCenter;
@property (copy, nonatomic) id /* block */ shareCompletion;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)shareSaveAlbumViewControllerWithContext:(id)arg0 shareCompletion:(id /* block */)arg1 vcCreateCompletion:(id /* block */)arg2;

- (void)copyLink:(id /* block */)arg0;
- (id)dataCenter;
- (void)setDataCenter:(id)arg0;
- (void)shareImage;
- (void)p_addSubviews;
- (void)removeCellForRowAtIndexPath:(id)arg0;
- (void)p_applicationWillEnterForeground;
- (void)p_dismissWithCompletion:(id /* block */)arg0;
- (id /* block */)shareCompletion;
- (void)setShareCompletion:(id /* block */)arg0;
- (void)clickedButtonForCellModel:(id)arg0;
- (void)mediaDownloadCompleted:(long long)arg0;
- (void)mediaSaveAlbumCompleted:(BOOL)arg0;
- (void)didRemoveCellModelAtIndex:(unsigned long long)arg0;
- (void)dismissPanelIfNeeded;
- (void)didInsertCellModelAtIndex:(unsigned long long)arg0;
- (id)p_getDownloadAwemeModel;
- (id)initWithContext:(id)arg0 dataCenter:(id)arg1 shareCompletion:(id /* block */)arg2;
- (double)p_preferredVCHeight;
- (void)p_invokeShareCompletion:(unsigned long long)arg0;
- (void)p_setUpConstraints;
- (void)p_adjustTableContentInset;
- (void)p_trackPanelShow;
- (void)p_dismissWithAnimated:(BOOL)arg0 completion:(id /* block */)arg1;
- (void)p_sendMessageWithModel:(id)arg0;
- (void)p_sharePrivacyToShareList:(id)arg0 completion:(id /* block */)arg1;
- (void)p_tappedMoreFriends;
- (void)p_trackShareVideoWithPlatform:(id)arg0 enterMethod:(id)arg1;
- (void)p_tappedWithIMTransferViewModel:(id)arg0;
- (void)p_clickedButtonForDefaultThirdPlatformCellModel:(id)arg0;
- (void)p_clickedButtonForCreateGroupThirdPlatformCellModel:(id)arg0;
- (void)p_shareWithTableView:(id)arg0 indexPath:(id)arg1;
- (void)halfScreenContainerVCWillDismiss:(id)arg0;
- (void)shareSaveIMTableViewCellDidClickSendButton:(id)arg0;
- (void)didClickNoFolderNoticeViewWithCompletion:(id /* block */)arg0;
- (void)tableView:(id)arg0 didSelectRowAtIndexPath:(id)arg1;
- (void)setTableView:(id)arg0;
- (long long)tableView:(id)arg0 numberOfRowsInSection:(long long)arg1;
- (void).cxx_destruct;
- (id)tableView;
- (void)setContext:(id)arg0;
- (id)tableView:(id)arg0 cellForRowAtIndexPath:(id)arg1;
- (id)context;
- (double)tableView:(id)arg0 heightForRowAtIndexPath:(id)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (id)scrollView;
- (void)p_applicationDidEnterBackground:(id)arg0;
- (void)p_registerNotifications;

@end
