//
//     Generated by private class-dump
//

@protocol AWEStudioACCMusicMVTemplateModelProtocolModelBind <NSObject>

+ (Class)getACCMusicMVTemplateModelProtocolModelImplClass;
+ (id)getACCMusicMVTemplateModelProtocolModelImpl;

@end
