//
//     Generated by private class-dump
//

@class AWESharkLynxModel, AWESharkLynxConfig, BDXContext, NSString, UIView, NSDictionary, LynxView;
@protocol AWESharkLynxContainerViewDelegate, BDXViewContainerProtocol;

@interface AWESharkLynxContainerView : UIView <BDXContainerLifecycleProtocol, AWESharkLynxContainerProtocol> {
    BOOL _isReuse;
    BOOL _rootLayoutAnimationEnabled;
    id<AWESharkLynxContainerViewDelegate> _lynxContainerDelegate;
    NSString *_containerID;
    AWESharkLynxModel *_lynxModel;
    NSString *_sessionId;
    UIView<BDXViewContainerProtocol> *_lynxContainer;
    AWESharkLynxConfig *_containerConfig;
    BDXContext *_context;
    NSString *_channelName;
    NSDictionary *_extraParams;
}

@property (retain, nonatomic) UIView<BDXViewContainerProtocol> *lynxContainer;
@property (retain, nonatomic) AWESharkLynxConfig *containerConfig;
@property (nonatomic) BOOL rootLayoutAnimationEnabled;
@property (retain, nonatomic) BDXContext *context;
@property (copy, nonatomic) NSString *channelName;
@property (copy, nonatomic) NSDictionary *extraParams;
@property (weak, nonatomic) id<AWESharkLynxContainerViewDelegate> lynxContainerDelegate;
@property (readonly, nonatomic) LynxView *lynxView;
@property (readonly, copy, nonatomic) NSString *containerID;
@property (retain, nonatomic) AWESharkLynxModel *lynxModel;
@property (copy, nonatomic) NSString *sessionId;
@property (nonatomic) BOOL isReuse;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)container:(id)arg0 didFinishLoadWithURL:(id)arg1;
- (void)container:(id)arg0 didLoadFailedWithUrl:(id)arg1 error:(id)arg2;
- (void)containerDidFirstScreen:(id)arg0;
- (void)containerDidUpdate:(id)arg0;
- (void)sendEvent:(id)arg0 params:(id)arg1;
- (id)findViewWithName:(id)arg0;
- (id)extraParams;
- (void)setExtraParams:(id)arg0;
- (id)lynxView;
- (id)containerConfig;
- (id)lynxModel;
- (void)setLynxModel:(id)arg0;
- (id)lynxContainer;
- (id)__bdxParams;
- (void)setLynxContainer:(id)arg0;
- (void)setContainerConfig:(id)arg0;
- (id)initWithLynxModel:(id)arg0 extraParams:(id)arg1 delegate:(id)arg2 containerConfig:(id)arg3;
- (void)updateLynxModel:(id)arg0;
- (void)lynxViewWillShow;
- (void)lynxViewWillHide;
- (BOOL)isReuse;
- (void)setLynxContainerDelegate:(id)arg0;
- (void)setIsReuse:(BOOL)arg0;
- (void)updateWithLynxUrl:(id)arg0 rawData:(id)arg1 cardType:(long long)arg2 extraParams:(id)arg3;
- (id)lynxContainerDelegate;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0 lynxModel:(id)arg1 extraParams:(id)arg2 delegate:(id)arg3 containerConfig:(id)arg4;
- (void)asyncLoadLynxURL;
- (void)updateLynxModel:(id)arg0 extraParams:(id)arg1;
- (void)setRootLayoutAnimationEnabled:(BOOL)arg0;
- (void)enableRootLayoutAnimation:(BOOL)arg0;
- (BOOL)rootLayoutAnimationEnabled;
- (id)channelNameWithUrl:(id)arg0;
- (void)__setupLynxView;
- (void)__setupLynxContext;
- (id)initWithLynxModel:(id)arg0 extraParams:(id)arg1;
- (BOOL)__hasGeckoResouces;
- (void)setSessionId:(id)arg0;
- (void).cxx_destruct;
- (id)channelName;
- (id)containerID;
- (void)setContext:(id)arg0;
- (id)sessionId;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (id)context;
- (id)initWithCoder:(id)arg0;
- (void)setChannelName:(id)arg0;

@end
