//
//     Generated by private class-dump
//

@protocol AWESearchCardCommentConfigProtocol <NSObject>

+ (id)likeLabelTextFont;
+ (BOOL)isColorWhite;
+ (double)contentVerticalPadding;
+ (double)commentRightPadding;
+ (id)commentTextColor;
+ (id)likeLabelDiggedColor;
+ (id)likeLabelNormalTextColor;
+ (id)likeLabelNormalColor;
+ (double)commentLeftPadding;
+ (id)nameTextFont;
+ (id)commentHighlightTextColor;
+ (double)nameLabelHeight;
+ (double)nameCommentSpace;
+ (double)normalLikesLabelWidth;
+ (double)abnormalLikeLabelRPadding;
+ (id)commentHighlightTextFont;
+ (id)avatarBoderColor;
+ (id)likeLabelSelectedTextColor;
+ (id)defaultAvatarColor;
+ (double)avatarLeftMargin;
+ (long long)searchCardAuthorCommentAjustTypeExpr;
+ (id)likeButtonNormalIconColorString;
+ (double)adjustCommentRightPadding;
+ (id)imageStickerTextFont;
+ (id)commentImageTagTextColor;
+ (id)highlightColor;
+ (id)commentTextFont;
+ (id)nameTextColor;
+ (double)avatarWidth;

@end
