//
//     Generated by private class-dump
//

@class NSURL, NSString;

@interface AWESECAppJumpAppLinkPlugin : IWKPluginObject <IWKClassPlugin> {
    double _lastCrossOriginTimestamp;
    NSURL *_lastCrossOriginPageURL;
    NSURL *_lastCrossOriginRequestURL;
}

@property (nonatomic) double lastCrossOriginTimestamp;
@property (retain, nonatomic) NSURL *lastCrossOriginPageURL;
@property (retain, nonatomic) NSURL *lastCrossOriginRequestURL;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)inject;
+ (id)shared;

- (void)onAppDidEnterBackground:(id)arg0;
- (BOOL)isCrossOriginWithPrevURL:(id)arg0 nextURL:(id)arg1;
- (BOOL)applinkEnableWithParams:(id)arg0 ruleList:(id)arg1;
- (double)lastCrossOriginTimestamp;
- (void)setLastCrossOriginTimestamp:(double)arg0;
- (id)lastCrossOriginPageURL;
- (void)setLastCrossOriginPageURL:(id)arg0;
- (id)lastCrossOriginRequestURL;
- (void)setLastCrossOriginRequestURL:(id)arg0;
- (id)init;
- (void).cxx_destruct;
- (id)webView:(id)arg0 decidePolicyForNavigationAction:(id)arg1 decisionHandler:(id /* block */)arg2;
- (id)webView:(id)arg0 didCommitNavigation:(id)arg1;
- (long long)priority;

@end
