//
//     Generated by private class-dump
//

@class UILabel, AWESettingSectionModel;

@interface AWESettingsTableSectionHeaderView : UITableViewHeaderFooterView {
    BOOL _shouldShowSeperationLine;
    BOOL _useCardUIStyle;
    AWESettingSectionModel *_sectionModel;
    UILabel *_titleLabel;
}

@property (nonatomic) BOOL useCardUIStyle;
@property (retain, nonatomic) AWESettingSectionModel *sectionModel;
@property (retain, nonatomic) UILabel *titleLabel;
@property (nonatomic) BOOL shouldShowSeperationLine;

+ (id)identifier;

- (BOOL)useCardUIStyle;
- (void)setUseCardUIStyle:(BOOL)arg0;
- (id)sectionModel;
- (void)setSectionModel:(id)arg0;
- (void)setShouldShowSeperationLine:(BOOL)arg0;
- (BOOL)shouldShowSeperationLine;
- (void).cxx_destruct;
- (id)titleLabel;
- (void)setTitleLabel:(id)arg0;
- (id)initWithReuseIdentifier:(id)arg0;
- (void)disableUserInteraction;

@end
