//
//     Generated by private class-dump
//

@class NSNumber;

@interface AWEShareSchemaEpisodeExtraModel : AWEBaseApiModel {
    NSNumber *_episodeRecordType;
    NSNumber *_episodeStage;
    NSNumber *_episodeSubType;
    NSNumber *_episodeType;
}

@property (retain, nonatomic) NSNumber *episodeRecordType;
@property (retain, nonatomic) NSNumber *episodeStage;
@property (retain, nonatomic) NSNumber *episodeSubType;
@property (retain, nonatomic) NSNumber *episodeType;

+ (id)JSONKeyPathsByPropertyKey;

- (id)episodeStage;
- (void)setEpisodeStage:(id)arg0;
- (id)episodeRecordType;
- (void)setEpisodeRecordType:(id)arg0;
- (id)episodeSubType;
- (void)setEpisodeSubType:(id)arg0;
- (id)episodeType;
- (void).cxx_destruct;
- (void)setEpisodeType:(id)arg0;

@end
