//
//     Generated by private class-dump
//

@class NSArray, UIView, NSMutableArray, UILabel;

@interface AWESearchAlbumTileLayoutController : UIViewController {
    id /* block */ _albumTappedWithIndex;
    long long _lastTapIndex;
    NSMutableArray *_imageViewsArray;
    NSArray *_albumImages;
    UIView *_moreOverlay;
    UILabel *_moreOverlayText;
    unsigned long long _layoutType;
}

@property (retain, nonatomic) NSMutableArray *imageViewsArray;
@property (retain, nonatomic) NSArray *albumImages;
@property (nonatomic) long long lastTapIndex;
@property (retain, nonatomic) UIView *moreOverlay;
@property (retain, nonatomic) UILabel *moreOverlayText;
@property (nonatomic) unsigned long long layoutType;
@property (copy, nonatomic) id /* block */ albumTappedWithIndex;

+ (struct CGSize { double x0; double x1; })getSingleImageSize:(id)arg0 containerWidth:(double)arg1;
+ (struct CGSize { double x0; double x1; })getContainerSizeFromImages:(id)arg0 containerWidth:(double)arg1 layoutType:(unsigned long long)arg2;
+ (long long)getMaxCountWithLayoutType:(unsigned long long)arg0;

- (id)albumImages;
- (void)setAlbumImages:(id)arg0;
- (id)moreOverlay;
- (id)moreOverlayText;
- (void)moreOverlayTapped;
- (id)imageViewsArray;
- (void)setLastTapIndex:(long long)arg0;
- (id /* block */)albumTappedWithIndex;
- (void)updateImageFrame;
- (void)updateMoreOverlay;
- (void)buildRightBottomShapeLayerForView:(id)arg0;
- (long long)lastTapIndex;
- (void)updateTapIndex:(long long)arg0;
- (id)currentTransitionView;
- (void)setAlbumTappedWithIndex:(id /* block */)arg0;
- (void)setImageViewsArray:(id)arg0;
- (void)setMoreOverlay:(id)arg0;
- (void)setMoreOverlayText:(id)arg0;
- (void)updateLayoutType:(unsigned long long)arg0;
- (unsigned long long)layoutType;
- (void)setLayoutType:(unsigned long long)arg0;
- (id)init;
- (id)transitionContext;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (void)updateCornerRadius;
- (id)initWithLayoutType:(unsigned long long)arg0;
- (void)updateWithModel:(id)arg0;

@end
