//
//     Generated by private class-dump
//

@protocol AWEShareLive <NSObject>

- (id)shareLive:(id)arg0 withType:(id)arg1;
- (void)shareLandscapeLive:(id)arg0 withType:(id)arg1 willDismissHandler:(id /* block */)arg2;
- (id)showPanelWithLive:(id)arg0 configurationHandler:(id /* block */)arg1 onViewController:(id)arg2;
- (id)showPanelWithLive:(id)arg0 configurationHandler:(id /* block */)arg1 onViewController:(id)arg2;
- (void)shareImage:(id)arg0 onViewController:(id)arg1 dismissHandler:(id /* block */)arg2;
- (void)shareImage:(id)arg0 onViewController:(id)arg1 dismissHandler:(id /* block */)arg2;
- (id)showPanelWithFormat:(id)arg0 configurationHandler:(id /* block */)arg1 onViewController:(id)arg2;
- (id)showPanelWithFormat:(id)arg0 configurationHandler:(id /* block */)arg1 onViewController:(id)arg2;
- (void)showTokenAlertWithLive:(id)arg0 shareType:(id)arg1 pasteHandler:(id /* block */)arg2;
- (void)showTokenAlertWithLive:(id)arg0 shareType:(id)arg1 pasteHandler:(id /* block */)arg2;
- (id /* block */)showPosterPanelWithLive:(id)arg0 onViewController:(id)arg1;
- (id /* block */)showPosterPanelWithLive:(id)arg0 onViewController:(id)arg1;
- (void)showLandscapePanelWithLive:(id)arg0 onViewController:(id)arg1 willDismissHandler:(id /* block */)arg2;
- (void)showLandscapePanelWithLive:(id)arg0 onViewController:(id)arg1 willDismissHandler:(id /* block */)arg2;
- (void)showLandscapePanelWithLiveScreenshot:(id)arg0 onViewController:(id)arg1;
- (void)showLandscapePanelWithLiveScreenshot:(id)arg0 onViewController:(id)arg1;
- (id /* block */)showImageShareLandscpaePanelWithLive:(id)arg0 onViewController:(id)arg1 willDismissHandler:(id /* block */)arg2;
- (id /* block */)showImageShareLandscpaePanelWithLive:(id)arg0 onViewController:(id)arg1 willDismissHandler:(id /* block */)arg2;
- (double)landscapePanelWidth;
- (id /* block */)showShareLiveImagePanelWithLive:(id)arg0 onViewController:(id)arg1 dismissHandler:(id /* block */)arg2;
- (id /* block */)showShareLiveImagePanelWithLive:(id)arg0 onViewController:(id)arg1 dismissHandler:(id /* block */)arg2;
- (void)configLiveTokenWithContext:(id)arg0;
- (void)configLiveTokenWithContext:(id)arg0;
- (id)contextWithLive:(id)arg0;
- (id)contextWithLive:(id)arg0;

@end
