//
//     Generated by private class-dump
//

@class NSString;
@protocol ACCMVTemplateModelProtocol;

@interface AWESelectTemplateModel : NSObject {
    id<ACCMVTemplateModelProtocol> _tpModel;
    unsigned long long _type;
    NSString *_meta;
}

@property (retain, nonatomic) id<ACCMVTemplateModelProtocol> tpModel;
@property (nonatomic) unsigned long long type;
@property (copy, nonatomic) NSString *meta;

- (id)tpModel;
- (void)setTpModel:(id)arg0;
- (void)setMeta:(id)arg0;
- (id)meta;
- (void).cxx_destruct;
- (unsigned long long)type;
- (void)setType:(unsigned long long)arg0;

@end
