//
//     Generated by private class-dump
//

@class AWEMinorAlbum, NSArray;

@interface AWETeenGeneralBlockModel : AWEBaseApiModel {
    BOOL _hasMore;
    AWEMinorAlbum *_minorAlbum;
    NSArray *_elements;
    NSArray *_awemeList;
}

@property (retain, nonatomic) AWEMinorAlbum *minorAlbum;
@property (copy, nonatomic) NSArray *elements;
@property (copy, nonatomic) NSArray *awemeList;
@property (nonatomic) BOOL hasMore;

+ (id)awemeListJSONTransformer;
+ (id)elementsJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;

- (id)awemeList;
- (void)setAwemeList:(id)arg0;
- (void)setMinorAlbum:(id)arg0;
- (id)minorAlbum;
- (void)setElements:(id)arg0;
- (void).cxx_destruct;
- (id)elements;
- (void)setHasMore:(BOOL)arg0;
- (BOOL)hasMore;

@end
