//
//     Generated by private class-dump
//

@class AWETheaterPageContext, AWETheaterTracker;

@protocol AWETheaterSectionControllerProtocol <NSObject>

@property (retain, nonatomic) AWETheaterPageContext *context;
@property (retain, nonatomic) AWETheaterTracker *tracker;

- (id)tracker;
- (void)setTracker:(id)arg0;
- (void)setContext:(id)arg0;
- (id)context;

@end
