//
//     Generated by private class-dump
//

@interface AWETeenProfileRedDotEyeProtectionTask : AWETeenProfileRedDotTask

- (long long)type;
- (BOOL)shouldShow;
- (void)setShouldShow:(BOOL)arg0;

@end
