//
//     Generated by private class-dump
//

@protocol AWETeenSaveDataCenterDelegate <NSObject>

- (void)saveDataCenter:(id)arg0 downloadCompleted:(long long)arg1;
- (void)saveDataCenter:(id)arg0 saveToSysPhotosCompleted:(BOOL)arg1;
- (void)saveDataCenter:(id)arg0 needApplyPhotoPermission:(BOOL)arg1;

@end
