//
//     Generated by private class-dump
//

@class NSString;

@interface AWEUlikeJumpAppService : HTSService <AWEUlikeJumpAppService>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)routerToUlikeApplicationURL:(id)arg0 completion:(id /* block */)arg1;
+ (void)routerToUlikeZlinkURL:(id)arg0 params:(id)arg1 completion:(id /* block */)arg2;
+ (BOOL)presentUlikeInstallPage:(id)arg0;
+ (id)ulikeItunesID;
+ (id)ulikeZlink;

@end
