//
//     Generated by private class-dump
//

@class AWEUserProfileRecommendCellView;

@interface AWEUserProfileRecommendTableViewCell : UITableViewCell {
    AWEUserProfileRecommendCellView *_baseView;
}

@property (retain, nonatomic) AWEUserProfileRecommendCellView *baseView;

- (void)configWithUser:(id)arg0;
- (void)setHighlighted:(BOOL)arg0 animated:(BOOL)arg1;
- (id)initWithStyle:(long long)arg0 reuseIdentifier:(id)arg1;
- (void).cxx_destruct;
- (id)baseView;
- (void)setBaseView:(id)arg0;
- (void)layoutSubviews;

@end
