//
//     Generated by private class-dump
//

@class UIColor, NSString;

@protocol AWEUGPendantProgressProtocol <NSObject>

@property (readonly, nonatomic) unsigned long long status;
@property (retain, nonatomic) UIColor *progressColor;
@property (retain, nonatomic) UIColor *progressBackgroundColor;
@property (nonatomic) double progressWidth;
@property (nonatomic) double progressValue;
@property (copy, nonatomic) NSString *progressBGColorS;
@property (nonatomic) double cornerRadius;
@property (nonatomic) unsigned long long progressType;
@property (retain, nonatomic) UIColor *bgColor;

- (void)performUpdateFromState:(unsigned long long)arg0 toState:(unsigned long long)arg1 animated:(BOOL)arg2;
- (id)progressBGColorS;
- (void)setProgressBGColorS:(id)arg0;
- (unsigned long long)status;
- (double)cornerRadius;
- (void)setProgressValue:(double)arg0;
- (double)progressValue;
- (void)setCornerRadius:(double)arg0;
- (id)progressColor;
- (void)setProgressColor:(id)arg0;
- (id)progressBackgroundColor;
- (void)setProgressBackgroundColor:(id)arg0;
- (unsigned long long)progressType;
- (void)setProgressType:(unsigned long long)arg0;
- (void)updateProgress:(double)arg0;
- (id)bgColor;
- (void)setBgColor:(id)arg0;
- (double)progressWidth;
- (void)setProgressWidth:(double)arg0;

@optional

- (void)updateProgress:(double)arg0 animated:(BOOL)arg1;
- (void)performContentZoomAnimation:(BOOL)arg0;
- (void)setProgressColors:(id)arg0;

@end
