//
//     Generated by private class-dump
//

@class NSArray, NSDictionary, NSString, AWEUGPendantGradientInfo;

@interface AWEUGPendantEnhanceItem : MTLModel <MTLJSONSerializing> {
    NSArray *_texts;
    AWEUGPendantGradientInfo *_gradient;
}

@property (copy, nonatomic) NSArray *texts;
@property (retain, nonatomic) AWEUGPendantGradientInfo *gradient;
@property (readonly, copy, nonatomic) NSDictionary *dictionaryValue;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)JSONKeyPathsByPropertyKey;

- (void)setGradient:(id)arg0;
- (void).cxx_destruct;
- (id)gradient;
- (id)texts;
- (void)setTexts:(id)arg0;

@end
