//
//     Generated by private class-dump
//

@protocol AWEUserActionRevertMessage <NSObject>

@optional

- (void)receiveUserRevertAction:(id)arg0;
- (void)storePrepareRevertUserAction:(id)arg0;

@end
