//
//     Generated by private class-dump
//

@class UIView;

@interface AWEVerticalSeparatorView : UICollectionReusableView {
    UIView *_lineView;
}

@property (readonly, nonatomic) UIView *lineView;

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (id)lineView;

@end
