//
//     Generated by private class-dump
//

@class NSArray;

@interface AWEVideoPlayDanmakuGetByIdsResponseModel : AWEBaseApiModel {
    NSArray *_danmakuList;
}

@property (copy, nonatomic) NSArray *danmakuList;

+ (id)danmakuListJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;

- (id)danmakuList;
- (void)setDanmakuList:(id)arg0;
- (void).cxx_destruct;

@end
