//
//     Generated by private class-dump
//

@protocol AWEVideoPublishMusicSelectViewRecentMusicDelegate <NSObject>

- (void)recentMusicRetryFetchFirstPage;
- (BOOL)recentMusicIsProcessingFetchingData;
- (BOOL)recentMusicHasMore;
- (void)recentMusicFetchNextPage:(id /* block */)arg0;

@optional

- (id)recentMusicCurrCursor;

@end
