//
//     Generated by private class-dump
//

@class NSString;

@protocol BDAd <NSObject>

@property (copy, nonatomic) NSString *ad_id;
@property (copy, nonatomic) NSString *log_extra;

- (void)setAd_id:(id)arg0;
- (id)ad_id;
- (id)log_extra;
- (void)setLog_extra:(id)arg0;

@end
