//
//     Generated by private class-dump
//

@class BDImageView, BDASplashGiftMeetViewModel, UIView, BDASplashComplianceSlideUpTipsView, UILabel;

@interface BDASplashGiftMeetView : BDASplashComplianceBaseSlideView {
    BDASplashGiftMeetViewModel *_viewModel;
    UIView *_gradientView;
    BDASplashComplianceSlideUpTipsView *_tipsView;
    UILabel *_tipsLabel;
    UIView *_boxShadowView;
    BDImageView *_beltImageView;
    BDImageView *_giftImageView;
    BDImageView *_atmosphereAnimationImage;
}

@property (retain, nonatomic) BDASplashGiftMeetViewModel *viewModel;
@property (retain, nonatomic) UIView *gradientView;
@property (retain, nonatomic) BDASplashComplianceSlideUpTipsView *tipsView;
@property (retain, nonatomic) UILabel *tipsLabel;
@property (retain, nonatomic) UIView *boxShadowView;
@property (retain, nonatomic) BDImageView *beltImageView;
@property (retain, nonatomic) BDImageView *giftImageView;
@property (retain, nonatomic) BDImageView *atmosphereAnimationImage;

- (id)tipsLabel;
- (id)tipsView;
- (void)setTipsView:(id)arg0;
- (void)setTipsLabel:(id)arg0;
- (void)addGesture;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0 viewHolder:(id)arg1 viewModel:(id)arg2;
- (void)loadAnimation;
- (void)updateSubviewLayout;
- (void)setAtmosphereAnimationImage:(id)arg0;
- (id)atmosphereAnimationImage;
- (void)loadShadow;
- (id)giftImageView;
- (id)boxShadowView;
- (id)beltImageView;
- (void)setBoxShadowView:(id)arg0;
- (void)setBeltImageView:(id)arg0;
- (void)setGiftImageView:(id)arg0;
- (void).cxx_destruct;
- (void)setGradientView:(id)arg0;
- (void)setViewModel:(id)arg0;
- (id)viewModel;
- (void)updateConfig;
- (id)gradientView;
- (void)setupView;

@end
