//
//     Generated by private class-dump
//

@class NSString, NSArray, NSDictionary;

@interface BDATEventModel : NSObject {
    BOOL _nonstandard;
    NSArray *_urls;
    NSString *_logExtra;
    NSString *_cid;
    NSString *_label;
    double _expireTime;
    NSDictionary *_extraData;
    NSArray *_tokens;
    NSString *_timestamp;
    long long _tryTimes;
    long long _failureTimes;
}

@property (copy, nonatomic) NSString *timestamp;
@property (nonatomic) long long tryTimes;
@property (nonatomic) long long failureTimes;
@property (copy, nonatomic) NSArray *urls;
@property (copy, nonatomic) NSString *logExtra;
@property (copy, nonatomic) NSString *cid;
@property (copy, nonatomic) NSString *label;
@property (nonatomic) BOOL nonstandard;
@property (nonatomic) double expireTime;
@property (copy, nonatomic) NSDictionary *extraData;
@property (copy, nonatomic) NSArray *tokens;

- (id)logExtra;
- (void)setLogExtra:(id)arg0;
- (void)setNonstandard:(BOOL)arg0;
- (void)setTryTimes:(long long)arg0;
- (void)setFailureTimes:(long long)arg0;
- (BOOL)nonstandard;
- (long long)tryTimes;
- (long long)failureTimes;
- (id)urls;
- (id)tokens;
- (id)initWithDictionary:(id)arg0 error:(id *)arg1;
- (id)timestamp;
- (void).cxx_destruct;
- (void)setTokens:(id)arg0;
- (void)setLabel:(id)arg0;
- (id)toDictionary;
- (id)cid;
- (void)setTimestamp:(id)arg0;
- (void)setUrls:(id)arg0;
- (BOOL)isEqual:(id)arg0;
- (id)label;
- (double)expireTime;
- (void)setExpireTime:(double)arg0;
- (void)setExtraData:(id)arg0;
- (id)extraData;
- (void)setCid:(id)arg0;

@end
