//
//     Generated by private class-dump
//

@protocol BDCastSinkManagerDelegate <NSObject>

@optional

- (void)castSinkManager:(id)arg0 didStartWithSdkType:(long long)arg1 serviceInfo:(id)arg2;
- (void)castSinkManager:(id)arg0 didStopWithSdkType:(long long)arg1 serviceInfo:(id)arg2;
- (void)castSinkManager:(id)arg0 sdkType:(long long)arg1 onError:(id)arg2 serviceInfo:(id)arg3;
- (BOOL)castSinkManager:(id)arg0 sdkType:(long long)arg1 onPlay:(id)arg2 serviceInfo:(id)arg3;
- (BOOL)castSinkManager:(id)arg0 onPauseWithSdkType:(long long)arg1 serviceInfo:(id)arg2;
- (BOOL)castSinkManager:(id)arg0 sdkType:(long long)arg1 onResume:(id)arg2 serviceInfo:(id)arg3;
- (BOOL)castSinkManager:(id)arg0 onStopWithSdkType:(long long)arg1 serviceInfo:(id)arg2;
- (BOOL)castSinkManager:(id)arg0 sdkType:(long long)arg1 onSeek:(id)arg2 serviceInfo:(id)arg3;
- (BOOL)castSinkManager:(id)arg0 sdkType:(long long)arg1 onSetVolume:(id)arg2 serviceInfo:(id)arg3;
- (unsigned int)castSinkManager:(id)arg0 getVolumeWithSdkType:(long long)arg1 serviceInfo:(id)arg2;
- (BOOL)castSinkManager:(id)arg0 onAddVolumeWithSdkType:(long long)arg1 serviceInfo:(id)arg2;
- (BOOL)castSinkManager:(id)arg0 onSubVolumeWithSdkType:(long long)arg1 serviceInfo:(id)arg2;
- (BOOL)castSinkManager:(id)arg0 sdkType:(long long)arg1 onSpeed:(double)arg2 serviceInfo:(id)arg3;
- (id)castSinkManager:(id)arg0 getPlayStateWithSdkType:(long long)arg1 serviceInfo:(id)arg2;
- (id)castSinkManager:(id)arg0 sdkType:(long long)arg1 onRcvMessage:(id)arg2 serviceInfo:(id)arg3;
- (id)castSinkManager:(id)arg0 getBrowseDataWithSdkType:(long long)arg1 serviceInfo:(id)arg2;
- (void)castSinkManager:(id)arg0 onJoinLocalUserID:(id)arg1 roomID:(id)arg2 errorCode:(long long)arg3 joinType:(long long)arg4;
- (void)castSinkManager:(id)arg0 onFirstRemoteVideoFrameDecoded:(id)arg1 withFrameInfo:(id)arg2;
- (void)castSinkManager:(id)arg0 mirrorDisconnect:(long long)arg1 sourceIp:(id)arg2 message:(id)arg3;
- (void)castSinkManager:(id)arg0 onLatencyWithIp:(id)arg1 frameIndex:(unsigned long long)arg2 latencyMap:(id)arg3;
- (void)castSinkManager:(id)arg0 didOccurredError:(long long)arg1 message:(id)arg2 serverId:(long long)arg3;
- (void)castSinkManager:(id)arg0 onMirrorRemoteVideoData:(id)arg1;
- (void)castSinkManager:(id)arg0 onMirrorVideoData:(id)arg1;
- (void)castSinkManager:(id)arg0 didClientStateInfo:(id)arg1;
- (void)castSinkManager:(id)arg0 mirrorCancelRequest:(id)arg1;
- (void)castSinkManager:(id)arg0 onLeaveRemoteUserID:(id)arg1 reason:(unsigned long long)arg2;
- (BOOL)castSinkManager:(id)arg0 mirrorCastRequest:(id)arg1 token:(id)arg2;
- (void)castSinkManager:(id)arg0 mirrorConnect:(id)arg1 sourceIp:(id)arg2;
- (void)castSinkManager:(id)arg0 onMirrorAudioData:(id)arg1;
- (void)castSinkManager:(id)arg0 sourceIp:(id)arg1 stuckStat:(id)arg2;
- (void)castSinkManagerOnLeaveLocalUser:(id)arg0;
- (void)castSinkManager:(id)arg0 didStartedStateInfo:(id)arg1;
- (void)castSinkManager:(id)arg0 sdkType:(long long)arg1 onLog:(id)arg2 serviceInfo:(id)arg3;
- (void)castSinkManager:(id)arg0 onMirrorUpdateRtt:(int)arg1;
- (void)castSinkManager:(id)arg0 onJoinRemoteUserID:(id)arg1 roomID:(id)arg2;
- (void)castSinkManager:(id)arg0 sourceIp:(id)arg1 recvMeta:(id)arg2;
- (void)castSinkManager:(id)arg0 didStopStateInfo:(long long)arg1;
- (void)castSinkManager:(id)arg0 mirrorLogger:(id)arg1;
- (void)castSinkManager:(id)arg0 onMirrorError:(id)arg1;
- (void)castSinkManager:(id)arg0 currentlogStr:(id)arg1;

@end
