//
//     Generated by private class-dump
//

@interface BDCRLRUCacheNode : NSObject {
    BDCRLRUCacheNode *_prev;
    BDCRLRUCacheNode *_next;
    id _key;
    id _value;
}

@property (weak, nonatomic) BDCRLRUCacheNode *prev;
@property (weak, nonatomic) BDCRLRUCacheNode *next;
@property (retain, nonatomic) id key;
@property (retain, nonatomic) id value;

- (id)next;
- (id)key;
- (void)setNext:(id)arg0;
- (void).cxx_destruct;
- (id)value;
- (void)setPrev:(id)arg0;
- (id)prev;
- (void)setKey:(id)arg0;
- (void)setValue:(id)arg0;

@end
