//
//     Generated by private class-dump
//

@class NSString;

@interface BDHMXValidationDataCollector : NSObject <BDHMInnerEventListenerProtocol>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)shared;

- (void)onEventUploaded:(id)arg0;
- (void)onEventCreated:(id)arg0;
- (void)onEventTerminated:(id)arg0;
- (void)onEventUnSampled:(id)arg0;
- (void)collectValidationParamsFrom:(id)arg0 desc:(id)arg1;
- (id)transTerminatedReasonFrom:(long long)arg0;
- (id)getBidFromDict:(id)arg0;
- (void)uploadDataToPlatform:(id)arg0;

@end
