//
//     Generated by private class-dump
//

@class NSArray, NSMutableArray;
@protocol BDHMReportPlugin;

@interface BDHybridMonitorXCoreReporter : NSObject {
    NSMutableArray *_reportBlockList;
    NSArray *_dataCleaningKey;
    id<BDHMReportPlugin> _reportPlugin;
}

@property (retain, nonatomic) NSMutableArray *reportBlockList;
@property (retain, nonatomic) NSArray *dataCleaningKey;
@property (retain, nonatomic) id<BDHMReportPlugin> reportPlugin;

+ (id)shareInstance;

- (void)addGlobalReportBlock:(id /* block */)arg0;
- (void)reportSingleDic:(id)arg0 forService:(id)arg1 bid:(id)arg2 sampleInfo:(id)arg3;
- (void)reportSingleDic:(id)arg0 forService:(id)arg1 bid:(id)arg2;
- (void)setReportBlockList:(id)arg0;
- (id)reportBlockList;
- (id)alogFilterList;
- (BOOL)shouldReport:(id)arg0;
- (BOOL)isFilterForService:(id)arg0;
- (void)setDataCleaningKey:(id)arg0;
- (id)getTeaParams:(id)arg0 data:(id)arg1;
- (void)reportHMDTotal:(id)arg0;
- (void)reportAndFormatService:(id)arg0 bid:(id)arg1 data:(id)arg2 sampleInfo:(id)arg3;
- (void)dataCleaningWithDic:(id)arg0;
- (id)reportPlugin;
- (id)dataCleaningKey;
- (void)setReportPlugin:(id)arg0;
- (id)getEventType:(id)arg0;
- (void).cxx_destruct;

@end
