//
//     Generated by private class-dump
//

@class UIColor, NSString, BDLOCNativeAppMorePanelItemContext, UIImage, NSURL, NSNumber, BDLOCNativeAppMorePanel;

@interface BDLOCNativeAppMorePanelItemConfiguration : NSObject {
    BOOL _isAutoDismiss;
    NSString *_name;
    UIImage *_icon;
    NSURL *_iconURL;
    UIColor *_textColor;
    NSNumber *_alpha;
    id /* block */ _actionBlock;
    id /* block */ _actionBlockWithDismiss;
    long long _type;
    BDLOCNativeAppMorePanelItemContext *_context;
    BDLOCNativeAppMorePanel *_morePanel;
}

@property (copy, nonatomic) NSString *name;
@property (retain, nonatomic) UIImage *icon;
@property (retain, nonatomic) NSURL *iconURL;
@property (nonatomic) BOOL isAutoDismiss;
@property (copy, nonatomic) UIColor *textColor;
@property (copy, nonatomic) NSNumber *alpha;
@property (copy, nonatomic) id /* block */ actionBlock;
@property (copy, nonatomic) id /* block */ actionBlockWithDismiss;
@property (nonatomic) long long type;
@property (retain, nonatomic) BDLOCNativeAppMorePanelItemContext *context;
@property (retain, nonatomic) BDLOCNativeAppMorePanel *morePanel;

- (BOOL)isAutoDismiss;
- (void)setIsAutoDismiss:(BOOL)arg0;
- (id)morePanel;
- (void)setMorePanel:(id)arg0;
- (id /* block */)actionBlockWithDismiss;
- (void)setActionBlockWithDismiss:(id /* block */)arg0;
- (id)icon;
- (id)init;
- (void).cxx_destruct;
- (void)setAlpha:(id)arg0;
- (void)setIconURL:(id)arg0;
- (void)setContext:(id)arg0;
- (id)iconURL;
- (long long)type;
- (void)setType:(long long)arg0;
- (id)context;
- (void)setName:(id)arg0;
- (void)setIcon:(id)arg0;
- (id)alpha;
- (void)setTextColor:(id)arg0;
- (id /* block */)actionBlock;
- (id)name;
- (id)textColor;
- (void)setActionBlock:(id /* block */)arg0;

@end
