//
//     Generated by private class-dump
//

@class NSString, BDNovelAudioTextView, NSMutableSet, UILabel, UIScrollView, NSMutableArray;
@protocol BDNovelCommonVipPriceViewDelegate;

@interface BDNovelCommonVipPriceViewV2 : BDNovelCommonVipBaseChildView <BDNovelCommonVipCenterBlockViewDelegate, UIScrollViewDelegate> {
    id<BDNovelCommonVipPriceViewDelegate> _delegate;
    UILabel *_titleLabel;
    BDNovelAudioTextView *_openHistoryButton;
    UIScrollView *_priceScrollView;
    NSMutableArray *_priceViews;
    NSMutableSet *_showPriceSet;
    long long _currentSelect;
}

@property (retain, nonatomic) UILabel *titleLabel;
@property (retain, nonatomic) BDNovelAudioTextView *openHistoryButton;
@property (retain, nonatomic) UIScrollView *priceScrollView;
@property (retain, nonatomic) NSMutableArray *priceViews;
@property (retain, nonatomic) NSMutableSet *showPriceSet;
@property (nonatomic) long long currentSelect;
@property (weak, nonatomic) id<BDNovelCommonVipPriceViewDelegate> delegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)onOpenVipHistory;
- (void)sizeWithWith:(double)arg0;
- (void)beginDiscountAnimation:(BOOL)arg0;
- (long long)currentSelect;
- (long long)currentSelectIndex;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0 parentView:(id)arg1 viewModel:(id)arg2;
- (void)setPriceScrollView:(id)arg0;
- (void)setupPriceView;
- (id)priceScrollView;
- (id)priceViews;
- (void)updatePayInfoPosition;
- (void)setPriceViews:(id)arg0;
- (void)onBlockClick:(id)arg0;
- (void)setCurrentSelect:(long long)arg0;
- (id)showPriceSet;
- (void)onBlockViewCountDownEndAction;
- (void)setShowPriceSet:(id)arg0;
- (id)openHistoryButton;
- (void)setOpenHistoryButton:(id)arg0;
- (void).cxx_destruct;
- (id)titleLabel;
- (void)scrollViewDidScroll:(id)arg0;
- (id)delegate;
- (void)layoutSubviews;
- (void)setDelegate:(id)arg0;
- (void)setTitleLabel:(id)arg0;
- (void)updateWithViewModel:(id)arg0;

@end
