//
//     Generated by private class-dump
//

@class NSString, NSArray;

@interface BDNovelShareParam : NSObject {
    NSString *_shareTitle;
    NSString *_content;
    NSString *_imageUrl;
    NSString *_webPageURL;
    NSString *_repostSchema;
    NSString *_customSchema;
    NSString *_resourceId;
    NSString *_categoryName;
    NSArray *_customShareParams;
}

@property (copy, nonatomic) NSString *shareTitle;
@property (copy, nonatomic) NSString *content;
@property (copy, nonatomic) NSString *imageUrl;
@property (copy, nonatomic) NSString *webPageURL;
@property (copy, nonatomic) NSString *repostSchema;
@property (copy, nonatomic) NSString *customSchema;
@property (copy, nonatomic) NSString *resourceId;
@property (copy, nonatomic) NSString *categoryName;
@property (copy, nonatomic) NSArray *customShareParams;

- (id)resourceId;
- (void)setShareTitle:(id)arg0;
- (id)repostSchema;
- (void)setRepostSchema:(id)arg0;
- (id)customSchema;
- (void)setCustomSchema:(id)arg0;
- (void)setResourceId:(id)arg0;
- (id)customShareParams;
- (void)setCustomShareParams:(id)arg0;
- (void).cxx_destruct;
- (id)content;
- (void)setContent:(id)arg0;
- (id)webPageURL;
- (void)setWebPageURL:(id)arg0;
- (id)imageUrl;
- (void)setImageUrl:(id)arg0;
- (id)categoryName;
- (void)setCategoryName:(id)arg0;
- (id)shareTitle;

@end
