//
//     Generated by private class-dump
//

@class BDNovelReaderTitleView, BDNovelReaderCoverPlugin, BDNovelReaderBookEndPlugin;

@interface BDNovelReaderTitlePlugin : BDNovelReaderBasePlugin {
    BDNovelReaderTitleView *_scrollTitleView;
    BDNovelReaderCoverPlugin *_coverPlugin;
    BDNovelReaderBookEndPlugin *_endPlugin;
    unsigned long long _oldPageMode;
}

@property (retain, nonatomic) BDNovelReaderTitleView *scrollTitleView;
@property (retain, nonatomic) BDNovelReaderCoverPlugin *coverPlugin;
@property (retain, nonatomic) BDNovelReaderBookEndPlugin *endPlugin;
@property (nonatomic) unsigned long long oldPageMode;

+ (void)managerDidFirstStart;

- (id)pluginRequestReaderUI:(id)arg0;
- (void)pluginReaderPageViewControllerDidAppear:(id)arg0 pageContext:(id)arg1;
- (id)pluginReaderVCRequestReaderPageUI:(id)arg0 pageContext:(id)arg1 layoutLines:(id)arg2;
- (void)pluginReaderConfigChange:(id)arg0;
- (id)coverPlugin;
- (void)setOldPageMode:(unsigned long long)arg0;
- (id)scrollTitleView;
- (id)p_getTitleString:(id)arg0;
- (BOOL)p_disableShowTitleWithPageContext:(id)arg0;
- (void)p_updateScrollTitleShowState;
- (unsigned long long)oldPageMode;
- (id)endPlugin;
- (void)setScrollTitleView:(id)arg0;
- (void)setCoverPlugin:(id)arg0;
- (void)setEndPlugin:(id)arg0;
- (void).cxx_destruct;

@end
