//
//     Generated by private class-dump
//

@protocol BDNovelVCProtocol <NSObject>

- (void)configCurrentVC:(id)arg0 statusBarWhite:(BOOL)arg1;
- (id)routeScheme;
- (BOOL)webShouldHandleRoute:(id)arg0;

@optional

- (void)routeURL:(id)arg0 userInfo:(id)arg1;
- (void)disableDragBack:(id)arg0 disable:(BOOL)arg1;
- (void)setNavigationBarVisible:(id)arg0 visible:(BOOL)arg1;
- (void)configExitGesture:(id)arg0 shouldStopExit:(id /* block */)arg1;
- (long long)getReaderVCType:(id)arg0;

@end
