//
//     Generated by private class-dump
//

@class NSString;

@interface BDNovelReaderChapterRequest : NSObject {
    NSString *_bookId;
    NSString *_itemId;
    id /* block */ _completionHandler;
}

@property (copy, nonatomic) NSString *bookId;
@property (copy, nonatomic) NSString *itemId;
@property (copy, nonatomic) id /* block */ completionHandler;

- (void).cxx_destruct;
- (void)setCompletionHandler:(id /* block */)arg0;
- (id /* block */)completionHandler;
- (id)itemId;
- (void)setItemId:(id)arg0;
- (id)bookId;
- (void)setBookId:(id)arg0;

@end
