//
//     Generated by private class-dump
//

@protocol BDNovelReaderLoadingViewProtocol <BDReaderInsertViewProtocol>

@property (nonatomic) BOOL darkMode;

- (void)startAnimation;
- (void)stopAnimation;
- (void)setDarkMode:(BOOL)arg0;
- (BOOL)darkMode;

@end
