//
//     Generated by private class-dump
//

@class NSString, BDNovelConfig;

@interface BDNovelAdapter : NSObject <BDNovelAdapterProtocol> {
    BDNovelConfig *_novelConfig;
}

@property (retain, nonatomic) BDNovelConfig *novelConfig;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)setUp;
+ (id)shareInstance;

- (void)innerSetup;
- (id)novelConfig;
- (void)setNovelConfig:(id)arg0;
- (void).cxx_destruct;

@end
