//
//     Generated by private class-dump
//

@class NSMutableDictionary, NSString, BDPObjectReusePool, NSMutableSet;

@interface BDPAppPageFactory : NSObject <BDPAppPageFactoryProtocol, BDPAppPreloadCacheDataSource, BDPIndustrySDKMessage> {
    BOOL _disabled;
    BDPObjectReusePool *_pagePool;
    NSMutableDictionary *_preloadPages;
    NSMutableSet *_loadingPages;
    id _token;
}

@property (retain, nonatomic) NSMutableDictionary *preloadPages;
@property (retain, nonatomic) NSMutableSet *loadingPages;
@property (weak, nonatomic) id token;
@property (nonatomic) BOOL disabled;
@property (retain, nonatomic) BDPObjectReusePool *pagePool;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)bootstrapLaunch;
+ (void)tryReleaseAllPreloadAppPage;
+ (id)getPreloadDataSource;
+ (BOOL)supportPreloadForType:(long long)arg0;
+ (void)tryReleasePreloadAppPageForRenderType:(id)arg0;
+ (id)sharedManager;

- (id)preloadPages;
- (void)setPreloadPages:(id)arg0;
- (void)tryPreloadAppPage:(id)arg0;
- (void)preloadObjectWithModel:(id)arg0 schema:(id)arg1 reader:(id)arg2 completion:(id /* block */)arg3;
- (BOOL)preloadCache:(id)arg0 shouldPreloadNextWithExistingObject:(id)arg1;
- (void)preloadCache:(id)arg0 willReleaseObject:(id)arg1;
- (id)pagePool;
- (void)industrySDKDidUpdated:(id)arg0;
- (void)buildAppPageFactory;
- (void)releaseTerminatedPreloadAppPage:(id)arg0;
- (void)recieveInterruptionNotification:(id)arg0;
- (id)getPreloadAppPageWithUniqueID:(id)arg0 renderType:(id)arg1 caller:(id)arg2;
- (BOOL)isWebViewPreloadInterrupted;
- (void)tryPreloadAppPageForAllTypesWithCaller:(id)arg0;
- (BOOL)enablePreloadForType:(id)arg0;
- (id)createAppPageForRenderType:(id)arg0 caller:(id)arg1;
- (void)releaseAllPreloadedAppPage;
- (void)releasePreloadedAppPageForRenderType:(id)arg0;
- (id)getReusePageWithRenderType:(id)arg0;
- (id)loadingPages;
- (id)getPreloadAppPageForRenderType:(id)arg0;
- (id)appPageWithUniqueID:(id)arg0 renderType:(id)arg1 caller:(id)arg2;
- (BOOL)hasPreLoadAppPageAndPageReadyWithRenderType:(id)arg0;
- (void)setPagePool:(id)arg0;
- (void)setLoadingPages:(id)arg0;
- (BOOL)disabled;
- (void)setDisabled:(BOOL)arg0;
- (id)init;
- (void).cxx_destruct;
- (void)setToken:(id)arg0;
- (id)token;
- (void)dealloc;

@end
