//
//     Generated by private class-dump
//

@class NSString;

@interface BDPCDDynamicCardUIPropsExtraModel : BDPCDDynamicCardUIPropsModel {
    NSString *_imgUrl;
    long long _imageType;
}

@property (copy, nonatomic) NSString *imgUrl;
@property (nonatomic) long long imageType;

- (id)imgUrl;
- (void)setImgUrl:(id)arg0;
- (void).cxx_destruct;
- (long long)imageType;
- (id)initWithDict:(id)arg0;
- (void)setImageType:(long long)arg0;

@end
