//
//     Generated by private class-dump
//

@class NSString, BDPUniqueID;

@interface BDPHostEventListener : NSObject {
    NSString *_event;
    NSString *_jsEvent;
    BDPUniqueID *_uniqueID;
}

@property (retain, nonatomic) BDPUniqueID *uniqueID;
@property (copy, nonatomic) NSString *jsEvent;
@property (copy, nonatomic) NSString *event;

- (id)jsEvent;
- (void)setJsEvent:(id)arg0;
- (void)setEvent:(id)arg0;
- (id)event;
- (void).cxx_destruct;
- (id)uniqueID;
- (void)setUniqueID:(id)arg0;

@end
