//
//     Generated by private class-dump
//

@class UIColor;

@interface BDPMapSubPolylineModel : BDPBasePluginModel {
    BOOL _dottedLine;
    UIColor *_color;
    double _lineWidth;
}

@property (copy, nonatomic) UIColor *color;
@property (nonatomic) double lineWidth;
@property (nonatomic) BOOL dottedLine;

- (void)setDottedLine:(BOOL)arg0;
- (BOOL)dottedLine;
- (id)initWithPolylineModel:(id)arg0;
- (id)color;
- (void).cxx_destruct;
- (double)lineWidth;
- (void)setLineWidth:(double)arg0;
- (void)setColor:(id)arg0;

@end
