//
//     Generated by private class-dump
//

@class NSString, UIImage, NSURL;

@interface BDPMorePanelFriendAndContactModel : NSObject {
    BOOL _isGroupChat;
    BOOL _isLastObject;
    BOOL _isSelected;
    NSString *_name;
    UIImage *_avatarImage;
    NSURL *_iconUrl;
    long long _groupCapacity;
}

@property (nonatomic) BOOL isGroupChat;
@property (nonatomic) BOOL isLastObject;
@property (nonatomic) BOOL isSelected;
@property (copy, nonatomic) NSString *name;
@property (retain, nonatomic) UIImage *avatarImage;
@property (retain, nonatomic) NSURL *iconUrl;
@property (nonatomic) long long groupCapacity;

- (id)iconUrl;
- (void)setIconUrl:(id)arg0;
- (void)setGroupCapacity:(long long)arg0;
- (void)setIsLastObject:(BOOL)arg0;
- (BOOL)isLastObject;
- (long long)groupCapacity;
- (id)init;
- (void)setIsSelected:(BOOL)arg0;
- (void).cxx_destruct;
- (void)setName:(id)arg0;
- (id)name;
- (BOOL)isSelected;
- (void)setAvatarImage:(id)arg0;
- (id)avatarImage;
- (BOOL)isGroupChat;
- (void)setIsGroupChat:(BOOL)arg0;

@end
