//
//     Generated by private class-dump
//

@class NSMutableDictionary;

@interface BDPolicyPipelineManager : NSObject {
    NSMutableDictionary *_pipelines;
}

@property (retain, nonatomic) NSMutableDictionary *pipelines;

+ (id)sharedInstance;

- (void)registerPipeline:(id)arg0 forSpace:(id)arg1;
- (void)registerPipeline:(id)arg0 forPipelineUid:(id)arg1;
- (void)removePipelineforPipelineUid:(id)arg0;
- (id)getPipelineWithUid:(id)arg0;
- (void)removePipelineforSpace:(id)arg0;
- (void)removeAllPipelines;
- (id)getPipelineForCertUnit:(id)arg0;
- (id)init;
- (void).cxx_destruct;
- (void)setPipelines:(id)arg0;
- (id)pipelines;

@end
