//
//     Generated by private class-dump
//

@class NSString;

@interface BDPRTCRenderView : UIView {
    NSString *_userId;
    long long _mode;
    long long _devicePosition;
}

@property (copy, nonatomic) NSString *userId;
@property (nonatomic) long long mode;
@property (nonatomic) long long devicePosition;

- (void).cxx_destruct;
- (long long)devicePosition;
- (long long)mode;
- (void)setDevicePosition:(long long)arg0;
- (void)setMode:(long long)arg0;
- (id)userId;
- (void)setUserId:(id)arg0;

@end
