//
//     Generated by private class-dump
//

@class NSString;

@interface BDPStarkRuntime : BDPRuntime {
    NSString *_frontendSDKVersion;
    NSString *_mpLoadEventKey;
}

@property (copy, nonatomic) NSString *mpLoadEventKey;
@property (copy, nonatomic) NSString *frontendSDKVersion;

- (void)setupGameContext;
- (void)eventMpJsLoadStart;
- (void)updateUniqueID:(id)arg0;
- (id)initWithCoreCompleteBlk:(id /* block */)arg0;
- (id)frontendSDKVersion;
- (void)setFrontendSDKVersion:(id)arg0;
- (void)setMpLoadEventKey:(id)arg0;
- (id)mpLoadEventKey;
- (void).cxx_destruct;

@end
