//
//     Generated by private class-dump
//

@class UIImage;

@interface BDPWebPImageFrame : NSObject {
    UIImage *_image;
    double _duration;
}

@property (retain, nonatomic) UIImage *image;
@property (nonatomic) double duration;

+ (id)frameWithImage:(id)arg0 duration:(double)arg1;

- (void).cxx_destruct;
- (id)image;
- (double)duration;
- (void)setImage:(id)arg0;
- (void)setDuration:(double)arg0;

@end
