//
//     Generated by private class-dump
//

@class NSDictionary;

@interface BDReaderPageChangeInfo : NSObject {
    BOOL _isForward;
    unsigned long long _pageActionType;
    unsigned long long _changeFrom;
    NSDictionary *_extra;
}

@property (nonatomic) unsigned long long pageActionType;
@property (nonatomic) BOOL isForward;
@property (nonatomic) unsigned long long changeFrom;
@property (copy, nonatomic) NSDictionary *extra;

- (void)setExtra:(id)arg0;
- (unsigned long long)pageActionType;
- (void)setChangeFrom:(unsigned long long)arg0;
- (unsigned long long)changeFrom;
- (void)setPageActionType:(unsigned long long)arg0;
- (BOOL)isForward;
- (void).cxx_destruct;
- (id)extra;
- (void)setIsForward:(BOOL)arg0;

@end
