//
//     Generated by private class-dump
//

@class NSString, NSMutableArray, CLLocationManager;

@interface BDUGLocationAuthorizationTask : NSObject <CLLocationManagerDelegate> {
    struct _opaque_pthread_mutex_t { long long __sig; char __opaque[56]; } _requestAuthCallbacksMutex;
    struct _opaque_pthread_mutex_t { long long __sig; char __opaque[56]; } _getAuthStatusCallbacksMutex;
    struct _opaque_pthread_mutex_t { long long __sig; char __opaque[56]; } _authStatusMutex;
    struct _opaque_pthread_mutex_t { long long __sig; char __opaque[56]; } _accuracyAuthMutex;
    struct _opaque_pthread_mutex_t { long long __sig; char __opaque[56]; } _authStatusTrustMutex;
    struct _opaque_pthread_mutex_t { long long __sig; char __opaque[56]; } _authStatusSyncCountMutex;
    BOOL _authStatusTrust;
    CLLocationManager *_locationManager;
    long long _authStatus;
    long long _authAccuracy;
    unsigned long long _authStatusSyncCount;
    NSMutableArray *_requestAuthCallbacks;
    NSMutableArray *_currentAuthStatusCallbacks;
}

@property (retain) CLLocationManager *locationManager;
@property long long authStatus;
@property long long authAccuracy;
@property (nonatomic) BOOL authStatusTrust;
@property (nonatomic) unsigned long long authStatusSyncCount;
@property (retain, nonatomic) NSMutableArray *requestAuthCallbacks;
@property (retain, nonatomic) NSMutableArray *currentAuthStatusCallbacks;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)sharedTask;

- (BOOL)isAuthorizationStatusEnabled;
- (void)onReceivedDidEnterBackgroundNotification:(id)arg0;
- (void)_getCurrentLocationAuthorizationStatusWithChangeToForeground:(BOOL)arg0 completion:(id /* block */)arg1;
- (void)setAuthStatusTrust:(BOOL)arg0;
- (unsigned long long)authStatusSyncCount;
- (void)setAuthStatusSyncCount:(unsigned long long)arg0;
- (BOOL)authStatusTrust;
- (id)currentAuthStatusCallbacks;
- (long long)currentAuthorizationStatus;
- (void)getCurrentLocationAuthorizationStatusWithCompletion:(id /* block */)arg0;
- (void)setAuthAccuracy:(long long)arg0;
- (long long)authAccuracy;
- (long long)currentAuthorizationAccuracy;
- (id)requestAuthCallbacks;
- (void)_accuracyAuthorizationCallbackWithAccuracyAuthorization:(long long)arg0;
- (void)_currentLocationAuthorizationStatusCallbackWithAuthorizationStatus:(int)arg0;
- (void)_toggleAllAuthCallbacksWithAuthorizationStatus:(int)arg0;
- (void)_delegateCallbackWithAuthorizationStatus:(long long)arg0;
- (void)_monitorAuthorizationStatusChangeWithAuthorizationStatus:(long long)arg0;
- (void)isAuthorizationStatusEnabledWithCompletion:(id /* block */)arg0;
- (void)currentAccuracyStatusWithCompletion:(id /* block */)arg0;
- (void)requestTemporaryFullAccuracyAuthorizationWithPurposeKey:(id)arg0 cert:(id)arg1 completion:(id /* block */)arg2;
- (void)requestWhenInUseAuthorizationWithCert:(id)arg0 completion:(id /* block */)arg1;
- (void)setRequestAuthCallbacks:(id)arg0;
- (void)setCurrentAuthStatusCallbacks:(id)arg0;
- (void)onReceivedWillEnterForegroundNotification:(id)arg0;
- (id)init;
- (void)locationManager:(id)arg0 didChangeAuthorizationStatus:(int)arg1;
- (void).cxx_destruct;
- (void)setLocationManager:(id)arg0;
- (void)dealloc;
- (id)locationManager;
- (void)locationManagerDidChangeAuthorization:(id)arg0;
- (long long)authStatus;
- (void)setAuthStatus:(long long)arg0;

@end
