//
//     Generated by private class-dump
//

@class UIImageView, UILabel, UIView, BDUGLuckyDogToastModel;

@interface BDUGLuckyDogToast : UIView {
    BDUGLuckyDogToastModel *_model;
    UIView *_contentView;
    UILabel *_titleLab;
    UIImageView *_imageView;
    double _contentHeight;
    struct CGSize { double width; double height; } _textSize;
}

@property (retain, nonatomic) UIView *contentView;
@property (retain, nonatomic) UILabel *titleLab;
@property (retain, nonatomic) UIImageView *imageView;
@property (retain, nonatomic) BDUGLuckyDogToastModel *model;
@property (nonatomic) struct CGSize { double width; double height; } textSize;
@property (nonatomic) double contentHeight;

- (id)titleLab;
- (void)setTitleLab:(id)arg0;
- (id)imageWithImageName:(id)arg0;
- (id)initWithModel:(id)arg0;
- (void)setModel:(id)arg0;
- (void).cxx_destruct;
- (double)contentHeight;
- (id)model;
- (id)imageView;
- (void)setImageView:(id)arg0;
- (id)contentView;
- (void)layoutSubviews;
- (void)setContentHeight:(double)arg0;
- (void)setContentView:(id)arg0;
- (struct CGSize { double x0; double x1; })textSize;
- (void)setTextSize:(struct CGSize { double x0; double x1; })arg0;

@end
