//
//     Generated by private class-dump
//

@class NSString;

@interface BDWebResourceLoaderURLProtocol : NSURLProtocol <BDWebURLSchemeProtocolClass>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (BOOL)canInitWithSchemeTask:(id)arg0;
+ (id)canonicalRequestForRequest:(id)arg0;
+ (id)sharedCache;

- (void)stopLoading;
- (void)startLoading;

@end
