//
//     Generated by private class-dump
//

@class NSString, NSDictionary, NSArray;

@interface BDXBridgeUploadFileParam : NSObject {
    BOOL _needCommonParams;
    NSString *_urlString;
    NSDictionary *_headers;
    NSDictionary *_params;
    NSArray *_formDataBody;
}

@property (copy, nonatomic) NSString *urlString;
@property (copy, nonatomic) NSDictionary *headers;
@property (copy, nonatomic) NSDictionary *params;
@property (copy, nonatomic) NSArray *formDataBody;
@property (nonatomic) BOOL needCommonParams;

- (void)setNeedCommonParams:(BOOL)arg0;
- (BOOL)needCommonParams;
- (id)formDataBody;
- (void)setFormDataBody:(id)arg0;
- (id)urlString;
- (void)setHeaders:(id)arg0;
- (void).cxx_destruct;
- (id)headers;
- (void)setUrlString:(id)arg0;
- (id)params;
- (void)setParams:(id)arg0;

@end
