//
//     Generated by private class-dump
//

@class NSString;

@interface BDXBridgeMomentSpringReceiveRedPacketMethodParamModel : BDXBridgeModel {
    NSString *_awemeId;
}

@property (copy, nonatomic) NSString *awemeId;

+ (id)requiredKeyPaths;
+ (id)JSONKeyPathsByPropertyKey;

- (void)setAwemeId:(id)arg0;
- (id)awemeId;
- (void).cxx_destruct;

@end
