//
//     Generated by private class-dump
//

@interface BDXBridgeGetCurrentGCJLocationMethod : BDXBridgeMethod

+ (id)metaInfo;

- (void)callWithParamModel:(id)arg0 completionHandler:(id /* block */)arg1;
- (Class)paramModelClass;
- (Class)resultModelClass;
- (id)gcjLocationParamsWithParamModel:(id)arg0 locationModel:(id)arg1 isPopSelect:(BOOL)arg2;
- (void)handlerGetGCJCurrentLocationWithParamModel:(id)arg0 completion:(id /* block */)arg1;
- (long long)authType;
- (id)methodName;

@end
