//
//     Generated by private class-dump
//

@class NSNumber;

@interface BDXBridgeLocalServiceOptimizationStrategyJato : BDXBridgeModel {
    NSNumber *_enableJato;
    NSNumber *_enableCloseClassVerify;
    NSNumber *_enableBlockGC;
    NSNumber *_duration;
}

@property (retain, nonatomic) NSNumber *enableJato;
@property (retain, nonatomic) NSNumber *enableCloseClassVerify;
@property (retain, nonatomic) NSNumber *enableBlockGC;
@property (retain, nonatomic) NSNumber *duration;

+ (id)JSONKeyPathsByPropertyKey;

- (id)enableJato;
- (void)setEnableJato:(id)arg0;
- (id)enableCloseClassVerify;
- (void)setEnableCloseClassVerify:(id)arg0;
- (id)enableBlockGC;
- (void)setEnableBlockGC:(id)arg0;
- (void).cxx_destruct;
- (id)duration;
- (void)setDuration:(id)arg0;

@end
