//
//     Generated by private class-dump
//

@protocol BDXLynxFoldHeaderViewProDelegate;

@interface BDXLynxFoldHeaderViewPro : LynxUI {
    BOOL _fold;
    id<BDXLynxFoldHeaderViewProDelegate> _delegate;
    struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } _headerViewFrame;
}

@property (nonatomic) struct CGRect { struct CGPoint { double x; double y; } origin; struct CGSize { double width; double height; } size; } headerViewFrame;
@property (readonly, nonatomic) BOOL fold;
@property (weak, nonatomic) id<BDXLynxFoldHeaderViewProDelegate> delegate;

+ (void)lynxLazyLoad;

- (void)layoutDidFinished;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })headerViewFrame;
- (void)setHeaderViewFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (void).cxx_destruct;
- (id)delegate;
- (void)setDelegate:(id)arg0;
- (id)createView;
- (BOOL)fold;

@end
