//
//     Generated by private class-dump
//

@protocol BDXPopupEventProtocol;

@protocol BDXPopupContainerProtocol <BDXContainerProtocol>

@property (nonatomic, weak) id<BDXPopupEventProtocol> popupEventDelegate;

- (id)popupEventDelegate;
- (void)setPopupEventDelegate:(id)arg0;
- (BOOL)close:(id)arg0 animated:(BOOL)arg1;
- (void)closeWithParams:(id)arg0 animated:(BOOL)arg1 completion:(id /* block */)arg2;
- (void)closeWithParams:(id)arg0 animated:(BOOL)arg1 completion:(id /* block */)arg2;
- (BOOL)close:(id)arg0 completion:(id /* block */)arg1;
- (BOOL)close:(id)arg0 animated:(BOOL)arg1 completion:(id /* block */)arg2;
- (BOOL)close:(id)arg0;

@optional

- (void)popupShowAnimationFinished;
- (void)adjustHeightWithHeightPercent:(id)arg0 animated:(BOOL)arg1 draggable:(BOOL)arg2 completion:(id /* block */)arg3;
- (void)adjustHeightWithHeightPercent:(id)arg0 animated:(BOOL)arg1 draggable:(BOOL)arg2 completion:(id /* block */)arg3;
- (void)popupShow;

@end
