//
//     Generated by private class-dump
//

@class LynxTemplateData, NSString, NSArray, NSDictionary;

@interface BDXPreCreateTemplateRenderConfig : NSObject {
    NSString *_schema;
    NSArray *_elements;
    LynxTemplateData *_initialData;
    NSDictionary *_globalProps;
}

@property (copy, nonatomic) NSString *schema;
@property (copy, nonatomic) NSArray *elements;
@property (retain, nonatomic) LynxTemplateData *initialData;
@property (copy, nonatomic) NSDictionary *globalProps;

- (id)initialData;
- (void)setInitialData:(id)arg0;
- (void)setGlobalProps:(id)arg0;
- (id)globalProps;
- (void)setSchema:(id)arg0;
- (void)setElements:(id)arg0;
- (void).cxx_destruct;
- (id)elements;
- (id)schema;

@end
