//
//     Generated by private class-dump
//

@class NSString, BitrateUrlStructV2;

@interface BitrateMetaStructV2 : GPBMessage

@property (retain, nonatomic) BitrateUrlStructV2 *URLList;
@property (nonatomic) BOOL hasURLList;
@property (copy, nonatomic) NSString *encodedType;
@property (nonatomic) BOOL hasEncodedType;
@property (copy, nonatomic) NSString *mediaType;
@property (nonatomic) BOOL hasMediaType;
@property (copy, nonatomic) NSString *logoType;
@property (nonatomic) BOOL hasLogoType;
@property (copy, nonatomic) NSString *definition;
@property (nonatomic) BOOL hasDefinition;
@property (copy, nonatomic) NSString *quality;
@property (nonatomic) BOOL hasQuality;
@property (copy, nonatomic) NSString *qualityDesc;
@property (nonatomic) BOOL hasQualityDesc;
@property (copy, nonatomic) NSString *format;
@property (nonatomic) BOOL hasFormat;
@property (nonatomic) long long width;
@property (nonatomic) BOOL hasWidth;
@property (nonatomic) long long height;
@property (nonatomic) BOOL hasHeight;
@property (nonatomic) long long bitrate;
@property (nonatomic) BOOL hasBitrate;
@property (copy, nonatomic) NSString *codecType;
@property (nonatomic) BOOL hasCodecType;
@property (nonatomic) long long size;
@property (nonatomic) BOOL hasSize;
@property (nonatomic) long long fps;
@property (nonatomic) BOOL hasFps;
@property (copy, nonatomic) NSString *fileId;
@property (nonatomic) BOOL hasFileId;
@property (copy, nonatomic) NSString *fileHash;
@property (nonatomic) BOOL hasFileHash;
@property (copy, nonatomic) NSString *subInfo;
@property (nonatomic) BOOL hasSubInfo;

+ (id)descriptor;

@end
