//
//     Generated by private class-dump
//

@class NSString, NSMutableArray, UserConsumeOption;

@interface ChatMsgConfig : IESLivePBBaseMessage

@property (copy, nonatomic) NSString *chatModelDescribe;
@property (retain, nonatomic) NSMutableArray *chatModelArray;
@property (readonly, nonatomic) unsigned long long chatModelArray_Count;
@property (retain, nonatomic) NSMutableArray *fansLevelArray;
@property (readonly, nonatomic) unsigned long long fansLevelArray_Count;
@property (retain, nonatomic) NSMutableArray *labelLevelArray;
@property (readonly, nonatomic) unsigned long long labelLevelArray_Count;
@property (retain, nonatomic) UserConsumeOption *userConsume;
@property (nonatomic) BOOL hasUserConsume;

+ (id)descriptor;

@end
