//
//     Generated by private class-dump
//

@class CJPayButton, CJPayVerifyPasswordViewModel;

@interface CJPayHalfVerifyPasswordBaseViewController : CJPayHalfPageBaseViewController {
    BOOL _nonFirstAppear;
    CJPayVerifyPasswordViewModel *_viewModel;
    CJPayButton *_topRightButton;
}

@property (retain, nonatomic) CJPayVerifyPasswordViewModel *viewModel;
@property (nonatomic) BOOL nonFirstAppear;
@property (retain, nonatomic) CJPayButton *topRightButton;

- (id)topRightButton;
- (void)setTopRightButton:(id)arg0;
- (void)closeWithAnimation:(BOOL)arg0 comletion:(id /* block */)arg1;
- (id)initWithAnimationType:(unsigned long long)arg0 viewModel:(id)arg1;
- (void)p_screenShotDetected;
- (void)p_clearPasswordInput;
- (void)setNonFirstAppear:(BOOL)arg0;
- (id)p_pageTitleStr;
- (void)p_setupOtherVerifyBtn;
- (void)p_screenCaptureDetected:(id)arg0;
- (BOOL)nonFirstAppear;
- (BOOL)p_isShowBioVerify;
- (BOOL)p_isBioPayAvailable;
- (BOOL)resignFirstResponder;
- (void)viewDidAppear:(BOOL)arg0;
- (void).cxx_destruct;
- (id)initWithViewModel:(id)arg0;
- (void)viewWillDisappear:(BOOL)arg0;
- (void)viewDidDisappear:(BOOL)arg0;
- (void)setViewModel:(id)arg0;
- (id)viewModel;
- (void)dealloc;
- (void)viewDidLoad;
- (void)back;

@end
