//
//     Generated by private class-dump
//

@class NSArray, NSString, UILabel, UIView, UITableView;

@interface CJPayWithDrawResultProgressView : UIView <UITableViewDataSource> {
    NSArray *_items;
    UILabel *_titleLabel;
    UITableView *_tableView;
    UIView *_sepView;
}

@property (retain, nonatomic) UILabel *titleLabel;
@property (retain, nonatomic) UITableView *tableView;
@property (retain, nonatomic) UIView *sepView;
@property (copy, nonatomic) NSArray *items;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)sepView;
- (void)setSepView:(id)arg0;
- (void)p_setupUI;
- (void)setItems:(id)arg0;
- (void)setTableView:(id)arg0;
- (long long)tableView:(id)arg0 numberOfRowsInSection:(long long)arg1;
- (void).cxx_destruct;
- (id)tableView;
- (id)items;
- (id)tableView:(id)arg0 cellForRowAtIndexPath:(id)arg1;
- (id)titleLabel;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (void)didMoveToWindow;
- (void)setTitleLabel:(id)arg0;

@end
