//
//     Generated by private class-dump
//

@protocol CKBeautyServiceSubscriberProtocol <NSObject>

@optional

- (void)willChangeBeautyApplyingState:(BOOL)arg0;
- (void)didChangeBeautyOnState:(BOOL)arg0;
- (void)sidebarFloatingViewDidAppear;
- (void)sidebarFloatingViewDidDisappear;
- (void)beautyPanelViewDidAppear;
- (void)beautyPanelViewDidDisappear;
- (void)didFinishDownloadingAllItems;

@end
