//
//     Generated by private class-dump
//

@class CommonPictureTextHighlightResponse_Response;

@interface CommonPictureTextHighlightResponse : IESLivePBBaseMessage

@property (retain, nonatomic) CommonPictureTextHighlightResponse_Response *data_p;
@property (nonatomic) BOOL hasData_p;

+ (id)descriptor;

@end
