//
//     Generated by private class-dump
//

@class NSString, NSMutableArray;
@protocol CSJWebViewDynamicRenderInterface;

@interface CSJWebViewDynamicRenderOperation : NSOperation <CSJWebViewDynamicRenderDelegate> {
    BOOL _executing;
    BOOL _finished;
    BOOL _haveDone;
    id<CSJWebViewDynamicRenderInterface> _implementation;
    long long _renderIndex;
    double _beginTime;
    double _endTime;
    NSMutableArray *_logFlowArray;
}

@property (nonatomic, getter=isExecuting) BOOL executing;
@property (nonatomic, getter=isFinished) BOOL finished;
@property (nonatomic) long long renderIndex;
@property (nonatomic) double beginTime;
@property (nonatomic) double endTime;
@property (retain, nonatomic) NSMutableArray *logFlowArray;
@property (nonatomic) BOOL haveDone;
@property (retain, nonatomic) id<CSJWebViewDynamicRenderInterface> implementation;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (long long)renderIndex;
- (void)webViewWillRenderInImplementation:(id)arg0;
- (void)webViewDidRenderInImplementation:(id)arg0;
- (void)setRenderIndex:(long long)arg0;
- (void)pbu_addFlowLogWithMsg:(id)arg0;
- (void)done_3501;
- (BOOL)haveDone;
- (void)setHaveDone:(BOOL)arg0;
- (id)logFlowArray;
- (void)setLogFlowArray:(id)arg0;
- (void)setFinished:(BOOL)arg0;
- (BOOL)isFinished;
- (id)implementation;
- (BOOL)isConcurrent;
- (void)setImplementation:(id)arg0;
- (void).cxx_destruct;
- (BOOL)isExecuting;
- (void)setBeginTime:(double)arg0;
- (double)endTime;
- (void)start;
- (void)dealloc;
- (void)setEndTime:(double)arg0;
- (void)setExecuting:(BOOL)arg0;
- (double)beginTime;
- (id)initWithImplementation:(id)arg0;

@end
