//
//     Generated by private class-dump
//

@class NSString, DitoPageContext;
@protocol DitoExtensionContainerProtocol;

@interface DitoPerformanceChainExtension : NSObject <DitoExtensionProtocol, DitoViewControllerLifeCycleProtocol, DitoViewControllerLifeCycleProtocol_Private, DitoComponentDelegateProtocol_Private> {
    DitoPageContext *_context;
    id<DitoExtensionContainerProtocol> _container;
}

@property (weak, nonatomic) DitoPageContext *context;
@property (weak, nonatomic) id<DitoExtensionContainerProtocol> container;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)configWithRouterParamDict:(id)arg0;
- (void)didLoadPageModel:(id)arg0;
- (void)viewDealloc;
- (void)didEndReload;
- (void)didSendRequest;
- (void)didEndRequestWithResponse:(id)arg0 error:(id)arg1;
- (void)didMergePageModel:(id)arg0 update:(id)arg1 result:(id)arg2;
- (void)componentViewWillShow:(id)arg0;
- (void)componentViewDidCompleteShow:(id)arg0;
- (void)componentViewWillCreatedOfTag:(id)arg0;
- (void)componentViewDidCreatedOfTag:(id)arg0 componentView:(id)arg1;
- (void)componentView:(id)arg0 willUpdateViewModel:(id)arg1;
- (void)componentView:(id)arg0 didUpdateViewModel:(id)arg1;
- (void)initializeExtension;
- (void)_componentViewModelWillCreatedWithNode:(id)arg0;
- (void)_componentViewModelDidCreatedWithNode:(id)arg0;
- (id)container;
- (void).cxx_destruct;
- (void)setContext:(id)arg0;
- (void)setContainer:(id)arg0;
- (id)context;

@end
