//
//     Generated by private class-dump
//

@class NSString;

@interface DUXDynamicIconColorProvider : NSObject <DUXIconColorProtocol> {
    id /* block */ _provider;
}

@property (copy, nonatomic) id /* block */ provider;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)dynamicIconColorWithBlock:(id /* block */)arg0;

- (id)dux_colorWithTheme:(long long)arg0;
- (id)dux_color;
- (void)setProvider:(id /* block */)arg0;
- (id /* block */)provider;
- (void).cxx_destruct;

@end
