//
//     Generated by private class-dump
//

@class DUXSlidingScrollView, NSString, DUXTabBar, NSMutableArray;
@protocol DUXTabBarProtocol, DUXTabBarContainerDelegate;

@interface DUXTabBarContainerController : UIViewController <UIScrollViewDelegate> {
    BOOL _slideEnabled;
    BOOL _isViewAppearing;
    BOOL _isViewAppeared;
    BOOL _isScrolling;
    BOOL _isScrollingWhileDisappear;
    DUXTabBar<DUXTabBarProtocol> *_tabbarView;
    DUXSlidingScrollView *_contentScrollView;
    long long _selectedIndex;
    id<DUXTabBarContainerDelegate> _delegate;
    id /* block */ _indexChangeBlock;
    NSMutableArray *_viewControllers;
    long long _scrollPreIndex;
    long long _animatingDestinationIndex;
    NSMutableArray *_transitionAppearArray;
    NSMutableArray *_transitionDisappearArray;
    NSMutableArray *_appearCompleteArray;
}

@property (retain, nonatomic) NSMutableArray *viewControllers;
@property (nonatomic) BOOL isViewAppearing;
@property (nonatomic) BOOL isViewAppeared;
@property (nonatomic) BOOL isScrolling;
@property (nonatomic) BOOL isScrollingWhileDisappear;
@property (nonatomic) long long scrollPreIndex;
@property (nonatomic) long long animatingDestinationIndex;
@property (retain, nonatomic) NSMutableArray *transitionAppearArray;
@property (retain, nonatomic) NSMutableArray *transitionDisappearArray;
@property (retain, nonatomic) NSMutableArray *appearCompleteArray;
@property (retain, nonatomic) DUXTabBar<DUXTabBarProtocol> *tabbarView;
@property (retain, nonatomic) DUXSlidingScrollView *contentScrollView;
@property (nonatomic) BOOL slideEnabled;
@property (nonatomic) long long selectedIndex;
@property (weak, nonatomic) id<DUXTabBarContainerDelegate> delegate;
@property (copy, nonatomic) id /* block */ indexChangeBlock;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)tabbarView;
- (void)setTabbarView:(id)arg0;
- (void)setIsViewAppearing:(BOOL)arg0;
- (void)setupContainer;
- (void)setIndexChangeBlock:(id /* block */)arg0;
- (id)currentVCAtIndex:(long long)arg0;
- (id)initWithSelectedIndex:(long long)arg0;
- (BOOL)isViewAppeared;
- (void)setIsViewAppeared:(BOOL)arg0;
- (long long)numberOfControllers;
- (id)controllerAtIndex:(long long)arg0;
- (void)vcHasCompleteAppear:(id)arg0;
- (void)setIsScrollingWhileDisappear:(BOOL)arg0;
- (void)correctSelectedIndexIfNeededWithScrollView:(id)arg0;
- (BOOL)isScrollingWhileDisappear;
- (void)vcHasCompleteDisappear:(id)arg0;
- (void)_makeControllersDidAppear;
- (id)appearCompleteArray;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })viewFrameAtIndex:(long long)arg0;
- (id)transitionAppearArray;
- (id)transitionDisappearArray;
- (void)addViewController:(id)arg0 atIndex:(long long)arg1;
- (long long)nextIndexForScrollView:(id)arg0;
- (long long)animatingDestinationIndex;
- (void)updateScrollIndexControllerWithTransitionType:(long long)arg0 index:(long long)arg1;
- (void)_makeViewControllerVisibleAtIndex:(long long)arg0 transitionType:(long long)arg1;
- (id /* block */)indexChangeBlock;
- (void)setTransitionAppearArray:(id)arg0;
- (void)setScrollPreIndex:(long long)arg0;
- (void)_makeControllersWillAppearAtPreIndex:(long long)arg0 currentIndex:(long long)arg1;
- (void)setAnimatingDestinationIndex:(long long)arg0;
- (void)updateSelectedIndexWithScrollView:(id)arg0;
- (long long)scrollPreIndex;
- (void)setTransitionDisappearArray:(id)arg0;
- (void)setAppearCompleteArray:(id)arg0;
- (void)scollViewScrollToIndex:(long long)arg0;
- (long long)_currentIndexForScrollView:(id)arg0;
- (void)setIsScrolling:(BOOL)arg0;
- (id)viewControllers;
- (void)setViewControllers:(id)arg0;
- (id)init;
- (void)viewDidAppear:(BOOL)arg0;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)arg0;
- (void)setSelectedIndex:(long long)arg0;
- (BOOL)isScrolling;
- (void)viewWillDisappear:(BOOL)arg0;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (void)scrollViewDidEndScrollingAnimation:(id)arg0;
- (void)viewDidDisappear:(BOOL)arg0;
- (void)scrollViewDidScroll:(id)arg0;
- (id)delegate;
- (void)scrollViewDidEndDragging:(id)arg0 willDecelerate:(BOOL)arg1;
- (id)contentScrollView;
- (void)viewWillAppear:(BOOL)arg0;
- (void)setDelegate:(id)arg0;
- (void)scrollViewWillBeginDragging:(id)arg0;
- (void)viewDidLoad;
- (long long)selectedIndex;
- (BOOL)slideEnabled;
- (void)setSlideEnabled:(BOOL)arg0;
- (void)setContentScrollView:(id)arg0;
- (void)scrollToIndex:(long long)arg0 animated:(BOOL)arg1;
- (BOOL)isViewAppearing;
- (void)reloadViewControllers;

@end
