//
//     Generated by private class-dump
//

@class NSString;

@protocol DVEMediaContextNLEInterfaceDelegate <NSObject>

@property (copy, nonatomic) NSString *draftFolder;

- (id)mediaDelegateAssetFromSlot:(id)arg0;
- (id)mediaDelegateGetAbsolutePathWithResource:(id)arg0;
- (id)draftFolder;
- (void)setDraftFolder:(id)arg0;

@end
