//
//     Generated by private class-dump
//

@class NSString;

@interface DYBindContext : NSObject {
    BOOL _isRebind;
    NSString *_enterFrom;
    NSString *_enterMethod;
    unsigned long long _useType;
    id /* block */ _didFinishBindBlock;
    id /* block */ _didCancelBindBlock;
    NSString *_title;
}

@property (retain, nonatomic) NSString *enterFrom;
@property (retain, nonatomic) NSString *enterMethod;
@property (nonatomic) unsigned long long useType;
@property (copy, nonatomic) id /* block */ didFinishBindBlock;
@property (copy, nonatomic) id /* block */ didCancelBindBlock;
@property (nonatomic) BOOL isRebind;
@property (retain, nonatomic) NSString *title;

+ (id)instanceWithBlock:(id /* block */)arg0;

- (void)setEnterFrom:(id)arg0;
- (void)setEnterMethod:(id)arg0;
- (id)enterMethod;
- (id)enterFrom;
- (void)setDidCancelBindBlock:(id /* block */)arg0;
- (void)setDidFinishBindBlock:(id /* block */)arg0;
- (void)setUseType:(unsigned long long)arg0;
- (id /* block */)didFinishBindBlock;
- (id /* block */)didCancelBindBlock;
- (BOOL)isRebind;
- (void)setIsRebind:(BOOL)arg0;
- (void).cxx_destruct;
- (id)initWithBlock:(id /* block */)arg0;
- (id)title;
- (void)setTitle:(id)arg0;
- (unsigned long long)useType;

@end
