//
//     Generated by private class-dump
//

@class DYASecurityTicketModel, DYLoginNextActionButton, UILabel, DYLoginInputView;

@interface DYIDVerifyViewController : UIViewController {
    DYASecurityTicketModel *_ticketModel;
    id /* block */ _finishBlock;
    id /* block */ _cancelBlock;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    UILabel *_errorTipLabel;
    DYLoginInputView *_codeInputView;
    DYLoginNextActionButton *_nextButton;
}

@property (retain, nonatomic) DYASecurityTicketModel *ticketModel;
@property (copy, nonatomic) id /* block */ finishBlock;
@property (copy, nonatomic) id /* block */ cancelBlock;
@property (retain, nonatomic) UILabel *titleLabel;
@property (retain, nonatomic) UILabel *subTitleLabel;
@property (retain, nonatomic) UILabel *errorTipLabel;
@property (retain, nonatomic) DYLoginInputView *codeInputView;
@property (retain, nonatomic) DYLoginNextActionButton *nextButton;

+ (id)instanceWithSharkTicket:(id)arg0 finishBlock:(id /* block */)arg1 cancelBlock:(id /* block */)arg2;

- (void)backAction:(id)arg0;
- (id)errorTipLabel;
- (void)setErrorTipLabel:(id)arg0;
- (void)nextAction:(id)arg0;
- (id)ticketModel;
- (void)setTicketModel:(id)arg0;
- (id)codeInputView;
- (void)setCodeInputView:(id)arg0;
- (void)handleError:(id)arg0;
- (id /* block */)cancelBlock;
- (void).cxx_destruct;
- (id)titleLabel;
- (void)setCancelBlock:(id /* block */)arg0;
- (void)viewDidLoad;
- (void)setTitleLabel:(id)arg0;
- (id)nextButton;
- (void)setNextButton:(id)arg0;
- (id)subTitleLabel;
- (void)setSubTitleLabel:(id)arg0;
- (id /* block */)finishBlock;
- (void)setFinishBlock:(id /* block */)arg0;

@end
