//
//     Generated by private class-dump
//

@class NSString, DYRouterModel;

@interface DYPhoneBindAuthorizeLoginManager : NSObject <DYPhoneBindManagerProtocol> {
    NSString *_enterFrom;
    unsigned long long _platform;
    NSString *_carrier;
    id /* block */ _cancelBlock;
    id /* block */ _finishBlock;
    long long _verifiedEnv;
    DYRouterModel *_routerModel;
}

@property (copy, nonatomic) NSString *enterFrom;
@property (nonatomic) unsigned long long platform;
@property (copy, nonatomic) NSString *carrier;
@property (copy, nonatomic) id /* block */ cancelBlock;
@property (copy, nonatomic) id /* block */ finishBlock;
@property (nonatomic) long long verifiedEnv;
@property (retain, nonatomic) DYRouterModel *routerModel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)setEnterFrom:(id)arg0;
- (id)enterFrom;
- (id)routerModel;
- (void)setRouterModel:(id)arg0;
- (void)handleError:(id)arg0 model:(id)arg1 completion:(id /* block */)arg2;
- (void)showCancelAuthAlert;
- (id)configNextURL:(id)arg0;
- (void)showConflictH5Alert:(id)arg0;
- (void)setVerifiedEnv:(long long)arg0;
- (void)logWithEvent:(id)arg0 params:(id)arg1;
- (void)finishBindPhoneWithPlatform:(unsigned long long)arg0;
- (long long)verifiedEnv;
- (id)initWithEnterFrom:(id)arg0 platform:(unsigned long long)arg1;
- (id)initWithEnterFrom:(id)arg0 platform:(unsigned long long)arg1 routerModel:(id)arg2;
- (long long)getVerifyCodeType;
- (void)authLoginSuccess;
- (void)authLoginFail;
- (void)requestBindPhoneNumber:(id)arg0 code:(id)arg1 ticket:(id)arg2 completion:(id /* block */)arg3;
- (void)requestSendCodeWithPhoneNumber:(id)arg0 type:(long long)arg1 completion:(id /* block */)arg2;
- (void)requestSendVoiceCodeWithPhoneNumber:(id)arg0 ticket:(id)arg1 type:(long long)arg2 completion:(id /* block */)arg3;
- (id /* block */)cancelBlock;
- (void).cxx_destruct;
- (void)setPlatform:(unsigned long long)arg0;
- (unsigned long long)platform;
- (void)setCancelBlock:(id /* block */)arg0;
- (id)carrier;
- (void)setCarrier:(id)arg0;
- (id /* block */)finishBlock;
- (void)setFinishBlock:(id /* block */)arg0;

@end
