//
//     Generated by private class-dump
//

@class GPBInt64Array;

@interface ECOMTIMPBNMarkMsgUnreadCountReportResponseBody : GPBMessage

@property (nonatomic) BOOL setTotalStatus;
@property (nonatomic) BOOL hasSetTotalStatus;
@property (retain, nonatomic) GPBInt64Array *failedTagListArray;
@property (readonly, nonatomic) unsigned long long failedTagListArray_Count;

+ (id)descriptor;

@end
