//
//     Generated by private class-dump
//

@class NSString, FlexActivity_Content;

@interface FlexActivity_ContentGroup : IESLivePBBaseMessage

@property (copy, nonatomic) NSString *subTitle;
@property (retain, nonatomic) FlexActivity_Content *content;
@property (nonatomic) BOOL hasContent;

+ (id)descriptor;

@end
