//
//     Generated by private class-dump
//

@interface FlowKit.AppSettingPopoverTableView : UIView <UITableViewDelegate, UITableViewDataSource> {
    void /* unknown type, empty encoding */ tableView;
    void /* unknown type, empty encoding */ dataSource;
    void /* unknown type, empty encoding */ lastSelectedIndexPath;
    void /* unknown type, empty encoding */ handleSelectedAction;
}

- (void)tableView:(id)arg0 didSelectRowAtIndexPath:(id)arg1;
- (long long)tableView:(id)arg0 numberOfRowsInSection:(long long)arg1;
- (id)tableView:(id)arg0 cellForRowAtIndexPath:(id)arg1;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (id)initWithCoder:(id)arg0;

@end
