//
//     Generated by private class-dump
//

@class GetLikeIconListResponse_ResponseData;

@interface GetLikeIconListResponse : IESLivePBBaseMessage

@property (retain, nonatomic) GetLikeIconListResponse_ResponseData *data_p;
@property (nonatomic) BOOL hasData_p;

+ (id)descriptor;

@end
