//
//     Generated by private class-dump
//

@class GetPersonalKaraokeMediaInfoResponse_ResponseData;

@interface GetPersonalKaraokeMediaInfoResponse : IESLivePBBaseMessage

@property (retain, nonatomic) GetPersonalKaraokeMediaInfoResponse_ResponseData *data_p;
@property (nonatomic) BOOL hasData_p;

+ (id)descriptor;

@end
