//
//     Generated by private class-dump
//

@class NSString, NSArray, NSDictionary, NSData, NSURL;

@interface HGNetworkRequestParam : NSObject {
    unsigned long long _engineType;
    long long _methodType;
    NSString *_URLString;
    NSArray *_URLStrings;
    unsigned long long _retryCount;
    NSDictionary *_requestQuery;
    NSData *_requestBody;
    NSDictionary *_allHTTPHeaderFields;
    double _timeoutInterval;
    long long _requestType;
    long long _requestFrom;
    unsigned long long _tagType;
    long long _options;
    id *_progress;
    id /* block */ _didFinishCollectingMetricsHandler;
    NSURL *_downloadDestinationURL;
    id /* block */ _downloadHeaderCallback;
    id /* block */ _downloadDataCallback;
    id /* block */ _didCompleteCallback;
    NSDictionary *_commonMonitorParams;
}

@property (nonatomic) unsigned long long engineType;
@property (nonatomic) long long methodType;
@property (copy, nonatomic) NSString *URLString;
@property (copy, nonatomic) NSArray *URLStrings;
@property (nonatomic) unsigned long long retryCount;
@property (copy, nonatomic) NSDictionary *requestQuery;
@property (copy, nonatomic) NSData *requestBody;
@property (copy, nonatomic) NSDictionary *allHTTPHeaderFields;
@property (nonatomic) double timeoutInterval;
@property (nonatomic) long long requestType;
@property (nonatomic) long long requestFrom;
@property (nonatomic) unsigned long long tagType;
@property (nonatomic) long long options;
@property (nonatomic) id *progress;
@property (copy, nonatomic) id /* block */ didFinishCollectingMetricsHandler;
@property (retain, nonatomic) NSURL *downloadDestinationURL;
@property (copy, nonatomic) id /* block */ downloadHeaderCallback;
@property (copy, nonatomic) id /* block */ downloadDataCallback;
@property (copy, nonatomic) id /* block */ didCompleteCallback;
@property (copy, nonatomic) NSDictionary *commonMonitorParams;

+ (id)paramWithEngineType:(unsigned long long)arg0;

- (id)commonParams;
- (void)setMethodType:(long long)arg0;
- (long long)methodType;
- (id)commonMonitorParams;
- (void)setRequestQuery:(id)arg0;
- (void)setDownloadHeaderCallback:(id /* block */)arg0;
- (void)setDownloadDataCallback:(id /* block */)arg0;
- (void)setRequestFrom:(long long)arg0;
- (void)setCommonMonitorParams:(id)arg0;
- (void)setDidFinishCollectingMetricsHandler:(id /* block */)arg0;
- (id /* block */)downloadHeaderCallback;
- (id /* block */)downloadDataCallback;
- (id)generateRequest;
- (id)processHeader;
- (id)requestQuery;
- (void)setURLStrings:(id)arg0;
- (long long)requestFrom;
- (id /* block */)didFinishCollectingMetricsHandler;
- (id /* block */)didCompleteCallback;
- (void)setDidCompleteCallback:(id /* block */)arg0;
- (id)URLString;
- (id)requestBody;
- (id)init;
- (void)setTimeoutInterval:(double)arg0;
- (void)setRequestType:(long long)arg0;
- (unsigned long long)tagType;
- (unsigned long long)engineType;
- (void).cxx_destruct;
- (long long)requestType;
- (void)setRetryCount:(unsigned long long)arg0;
- (unsigned long long)retryCount;
- (void)setOptions:(long long)arg0;
- (double)timeoutInterval;
- (id *)progress;
- (long long)options;
- (void)setProgress:(id *)arg0;
- (void)setEngineType:(unsigned long long)arg0;
- (id)allHTTPHeaderFields;
- (void)setAllHTTPHeaderFields:(id)arg0;
- (void)setURLString:(id)arg0;
- (id)downloadDestinationURL;
- (void)setTagType:(unsigned long long)arg0;
- (void)setRequestBody:(id)arg0;
- (void)setDownloadDestinationURL:(id)arg0;
- (id)URLStrings;

@end
