//
//     Generated by private class-dump
//

@class NSString;

@interface HGOfflinePackage : NSObject {
    NSString *_md5;
    NSString *_packageUrl;
    NSString *_packagePath;
    NSString *_packageName;
}

@property (copy, nonatomic) NSString *md5;
@property (copy, nonatomic) NSString *packageUrl;
@property (copy, nonatomic) NSString *packagePath;
@property (copy, nonatomic) NSString *packageName;

- (id)packagePath;
- (void)setPackageUrl:(id)arg0;
- (void)setPackagePath:(id)arg0;
- (id)packageUrl;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg0;
- (unsigned long long)hash;
- (id)packageName;
- (BOOL)isEqual:(id)arg0;
- (id)md5;
- (void)setMd5:(id)arg0;
- (void)setPackageName:(id)arg0;

@end
