//
//     Generated by private class-dump
//

@protocol HGAwemeRoomInfoPluginDelegate;

@interface HGPluginRoomInfo : HGPluginBase {
    id<HGAwemeRoomInfoPluginDelegate> _roomInfoPlugin;
}

@property (retain, nonatomic) id<HGAwemeRoomInfoPluginDelegate> roomInfoPlugin;

- (id)roomInfoPlugin;
- (void)setRoomInfoPlugin:(id)arg0;
- (void)getRoomInfoWithParam:(id)arg0 callback:(id /* block */)arg1 instance:(id)arg2;
- (void).cxx_destruct;
- (BOOL)isLogin;

@end
