//
//     Generated by private class-dump
//

@class NSArray, NSDictionary, HMDApplicationSession, NSString, NSObject, HMDRecordStore;
@protocol OS_dispatch_queue;

@interface HMDSessionTracker : NSObject <HMDApplicationSessionUpdate> {
    double _startTimestamp;
    BOOL _isRunning;
    HMDApplicationSession *_currentSession;
    NSDictionary *_lastestSessionDicAtLastLaunch;
    NSObject<OS_dispatch_queue> *_sessionQueue;
    NSObject<OS_dispatch_queue> *_outdateQueryQueue;
    HMDRecordStore *_store;
    double _lastUpdateTime;
    NSArray *_cacheSessionsTimestamp;
}

@property (retain) HMDApplicationSession *currentSession;
@property (retain) NSDictionary *lastestSessionDicAtLastLaunch;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *sessionQueue;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *outdateQueryQueue;
@property BOOL isRunning;
@property (retain, nonatomic) HMDRecordStore *store;
@property (nonatomic) double lastUpdateTime;
@property (retain, nonatomic) NSArray *cacheSessionsTimestamp;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)latestSessionDicAtLastLaunch;
+ (id)latestSessionAtLastLaunch;
+ (void)initialize;
+ (id)currentSession;
+ (id)sharedInstance;
+ (id)rootPath;

- (void)cleanupWithAndConditions:(id)arg0;
- (id)eternalSessionID;
- (id)lastTimeEternalSessionID;
- (void)outdateSessionTimestampWithMaxCount:(long long)arg0 interval:(double)arg1 complete:(id /* block */)arg2;
- (void)didUpdateWithSessionDic:(id)arg0;
- (void)didUpdateForProperty:(id)arg0;
- (void)setOutdateQueryQueue:(id)arg0;
- (void)updateLastTimeEternalSessionIDFile;
- (void)addObserverForInjectedInfo;
- (void)recordSession:(id)arg0 sessionIDChanged:(BOOL)arg1 isSetUp:(BOOL)arg2;
- (void)recordSession:(id)arg0 sessionIDChanged:(BOOL)arg1;
- (id)outdateQueryQueue;
- (id)cacheSessionsTimestamp;
- (id)getSessionsInAscendingOrder;
- (void)setCacheSessionsTimestamp:(id)arg0;
- (double)startTimetag;
- (void)cleanupWithAndConditons:(id)arg0;
- (BOOL)needStartupImmediatelly;
- (id)lastestSessionDicAtLastLaunch;
- (void)setLastestSessionDicAtLastLaunch:(id)arg0;
- (void)setIsRunning:(BOOL)arg0;
- (BOOL)isRunning;
- (double)lastUpdateTime;
- (id)currentSession;
- (id)init;
- (void).cxx_destruct;
- (id)store;
- (id)sessionQueue;
- (void)setup;
- (void)setStore:(id)arg0;
- (void)setLastUpdateTime:(double)arg0;
- (void)setCurrentSession:(id)arg0;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)arg0 ofObject:(id)arg1 change:(id)arg2 context:(void *)arg3;
- (Class)storeClass;
- (void)setSessionQueue:(id)arg0;

@end
