//
//     Generated by private class-dump
//

@class NSString;

@interface HMURLSessionManager : NSObject <HMNetworkProtocol>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)requestWithModel:(id)arg0 callback:(id /* block */)arg1;
- (id)requestWithModel:(id)arg0;

@end
