//
//     Generated by private class-dump
//

@class NSString;

@interface HTSLiveRoomAuthStatus_RoomAuthOffReasons : IESLivePBBaseMessage

@property (copy, nonatomic) NSString *gift;

+ (id)descriptor;

@end
