//
//     Generated by private class-dump
//

@class HTSLiveUser, NSString, HTSLiveBadge, HTSLiveImage, HTSLiveMemberGoal, NSMutableArray, HTSLiveAnchorPriceInfo;

@interface HTSLivePanelData : IESLivePBBaseMessage

@property (retain, nonatomic) HTSLiveUser *anchor;
@property (nonatomic) BOOL hasAnchor;
@property (nonatomic) BOOL isMember;
@property (nonatomic) long long expiredTime;
@property (nonatomic) long long accompanyTime;
@property (retain, nonatomic) HTSLiveBadge *badge;
@property (nonatomic) BOOL hasBadge;
@property (nonatomic) long long level;
@property (retain, nonatomic) HTSLiveUser *user;
@property (nonatomic) BOOL hasUser;
@property (retain, nonatomic) NSMutableArray *customArray;
@property (readonly, nonatomic) unsigned long long customArray_Count;
@property (retain, nonatomic) NSMutableArray *commonArray;
@property (readonly, nonatomic) unsigned long long commonArray_Count;
@property (copy, nonatomic) NSString *payText;
@property (nonatomic) long long diamondCount;
@property (copy, nonatomic) NSString *extra;
@property (nonatomic) long long goodsId;
@property (nonatomic) long long buyTime;
@property (nonatomic) int memberType;
@property (nonatomic) BOOL canRenew;
@property (nonatomic) BOOL anchorIsInit;
@property (copy, nonatomic) NSString *notice;
@property (copy, nonatomic) NSString *tabTip;
@property (retain, nonatomic) NSMutableArray *broadCastArray;
@property (readonly, nonatomic) unsigned long long broadCastArray_Count;
@property (nonatomic) long long anchorSignupStatus;
@property (nonatomic) long long openNum;
@property (retain, nonatomic) HTSLiveImage *panelImg;
@property (nonatomic) BOOL hasPanelImg;
@property (retain, nonatomic) HTSLiveMemberGoal *memberGoal;
@property (nonatomic) BOOL hasMemberGoal;
@property (retain, nonatomic) NSMutableArray *notifyMessageArray;
@property (readonly, nonatomic) unsigned long long notifyMessageArray_Count;
@property (nonatomic) BOOL groupSetDone;
@property (nonatomic) long long groupSetAddType;
@property (nonatomic) long long groupMemberTotalCount;
@property (retain, nonatomic) NSMutableArray *subscribeTagsArray;
@property (readonly, nonatomic) unsigned long long subscribeTagsArray_Count;
@property (retain, nonatomic) HTSLiveAnchorPriceInfo *anchorPriceInfo;
@property (nonatomic) BOOL hasAnchorPriceInfo;
@property (nonatomic) long long advancedReviewFailNum;
@property (nonatomic) long long diyPrivilegeReviewFailNum;
@property (retain, nonatomic) NSMutableArray *openPagePrivilegeArray;
@property (readonly, nonatomic) unsigned long long openPagePrivilegeArray_Count;
@property (retain, nonatomic) NSMutableArray *advancedPrivilegeArray;
@property (readonly, nonatomic) unsigned long long advancedPrivilegeArray_Count;
@property (retain, nonatomic) NSMutableArray *notifyInfoArray;
@property (readonly, nonatomic) unsigned long long notifyInfoArray_Count;
@property (retain, nonatomic) NSMutableArray *basicPrivilegesArray;
@property (readonly, nonatomic) unsigned long long basicPrivilegesArray_Count;
@property (nonatomic) long long memberCount;

+ (id)descriptor;

@end
