//
//     Generated by private class-dump
//

@class NSString;

@interface IESECRelationTextConfigModel : MTLModel <MTLJSONSerializing> {
    NSString *_text;
    NSString *_textColor;
    double _fontSize;
    long long _fontWidth;
    NSString *_backgroundColor;
}

@property (copy, nonatomic) NSString *text;
@property (copy, nonatomic) NSString *textColor;
@property (nonatomic) double fontSize;
@property (nonatomic) long long fontWidth;
@property (copy, nonatomic) NSString *backgroundColor;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)JSONKeyPathsByPropertyKey;

- (void)setFontWidth:(long long)arg0;
- (long long)fontWidth;
- (id)init;
- (void).cxx_destruct;
- (void)setFontSize:(double)arg0;
- (void)setText:(id)arg0;
- (id)copyWithZone:(struct _NSZone { } *)arg0;
- (double)fontSize;
- (id)text;
- (id)backgroundColor;
- (void)setTextColor:(id)arg0;
- (void)setBackgroundColor:(id)arg0;
- (id)textColor;

@end
