//
//     Generated by private class-dump
//

@protocol IESECStoreFilterCollectionViewCellDelegate <NSObject>

- (void)switchButtonTapped;
- (id)popupManager;
- (void)switchButtonShowed;
- (void)selectButtonShowed:(id)arg0;
- (void)selectButtonTapped:(id)arg0;
- (void)liveProductButtonShowed:(id)arg0;
- (void)liveProductButtonTapped:(id)arg0 model:(id)arg1;
- (id)mainScrollView;

@optional

- (void)filterCollectionViewCell:(id)arg0 selectedSortModel:(id)arg1 order:(long long)arg2;

@end
