//
//     Generated by private class-dump
//

@interface IESECLiveEcGetCartStateMethodImpl : IESECLiveEcGetCartStateMethod

- (void)callWithParamModel:(id)arg0 completionHandler:(id /* block */)arg1;

@end
