//
//     Generated by private class-dump
//

@class NSTimer, NSMutableDictionary;

@interface IESECLiveRandomDelayTimer : NSObject {
    NSTimer *_delayTimer;
    NSMutableDictionary *_delayTimerManager;
}

@property (retain, nonatomic) NSTimer *delayTimer;
@property (retain, nonatomic) NSMutableDictionary *delayTimerManager;

- (void)startRandomTimerWithDuration:(long long)arg0 completion:(id /* block */)arg1;
- (void)startDelayRequestWithType:(id)arg0 completion:(id /* block */)arg1;
- (void)startRandomTimerWithMin:(long long)arg0 maxLimit:(long long)arg1 uniqueKey:(id)arg2 completion:(id /* block */)arg3;
- (void)startRandomTimerWithMin:(long long)arg0 maxLimit:(long long)arg1 completion:(id /* block */)arg2;
- (id)delayTimerManager;
- (long long)arc4randomFrom:(long long)arg0 to:(long long)arg1;
- (void)setDelayTimerManager:(id)arg0;
- (void)setDelayTimer:(id)arg0;
- (void).cxx_destruct;
- (void)cancelTimer;
- (id)delayTimer;
- (void)dealloc;

@end
