//
//     Generated by private class-dump
//

@class NSArray, UIView, IESECSliceXElement, IESECSliceXElementViewContext;

@protocol IESECSliceXElementView <IESECSliceXFlexProtocol, IESECSliceXElementViewLifecycle>

@property (readonly, nonatomic) IESECSliceXElementViewContext *context;
@property (readonly, nonatomic) IESECSliceXElement *element;
@property (readonly, nonatomic) UIView *bgView;
@property (readonly, nonatomic) NSArray *elementViews;

- (id)elementViews;
- (BOOL)updateWithSliceXElement:(id)arg0 error:(id *)arg1;
- (id)element;
- (id)context;
- (id)bgView;

@end
