//
//     Generated by private class-dump
//

@class NSString, NSArray;

@interface IESECGoodsDetailAuthorReputationModel : MTLModel <MTLJSONSerializing> {
    float _score;
    NSString *_text;
    unsigned long long _level;
    NSString *_sales;
    NSString *_percent;
    NSArray *_salesNum;
    NSString *_scoreNormalText;
}

@property (copy, nonatomic) NSString *text;
@property (nonatomic) float score;
@property (nonatomic) unsigned long long level;
@property (copy, nonatomic) NSString *sales;
@property (copy, nonatomic) NSString *percent;
@property (copy, nonatomic) NSArray *salesNum;
@property (copy, nonatomic) NSString *scoreNormalText;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)JSONKeyPathsByPropertyKey;

- (id)sales;
- (void)setSales:(id)arg0;
- (id)salesNum;
- (void)setSalesNum:(id)arg0;
- (id)scoreNormalText;
- (void)setScoreNormalText:(id)arg0;
- (void)setLevel:(unsigned long long)arg0;
- (void)setScore:(float)arg0;
- (unsigned long long)level;
- (float)score;
- (void).cxx_destruct;
- (void)setText:(id)arg0;
- (id)text;
- (id)percent;
- (void)setPercent:(id)arg0;

@end
