//
//     Generated by private class-dump
//

@class NSString, UIImage, UIView;
@protocol IESECVideoPlayerControllerDelegate;

@protocol IESECVideoPlayerProtocol <NSObject>

@property (readonly, copy, nonatomic) NSString *videoID;
@property (readonly, nonatomic) UIView *playerView;
@property (nonatomic) BOOL repeated;
@property (nonatomic) BOOL mute;
@property (nonatomic) unsigned long long videoPlayerFillMode;
@property (nonatomic) double volume;
@property (nonatomic) BOOL pauseOnResignActive;
@property (weak, nonatomic) id<IESECVideoPlayerControllerDelegate> delegate;
@property (readonly, nonatomic) BOOL isPlaying;
@property (readonly, nonatomic) BOOL isPause;
@property (readonly, nonatomic) double currentPlayTime;
@property (readonly, nonatomic) double duration;
@property (readonly, nonatomic) double playableDuration;
@property (readonly, nonatomic) double durationWatched;
@property (nonatomic) double playbackSpeed;
@property (nonatomic) BOOL enableHardDecode;
@property (readonly, nonatomic) UIImage *currentSnapShot;
@property (nonatomic) BOOL needCookie;
@property (nonatomic) BOOL playAmbient;

- (double)currentPlayTime;
- (id)initWithVideoID:(id)arg0 andPlayURLs:(id)arg1;
- (BOOL)enableHardDecode;
- (void)setEnableHardDecode:(BOOL)arg0;
- (BOOL)isPause;
- (void)setCurrentPlaybackTime:(double)arg0 complete:(id /* block */)arg1;
- (void)setNeedCookie:(BOOL)arg0;
- (BOOL)needCookie;
- (void)seekToProgress:(double)arg0;
- (void)reloadVideoID:(id)arg0 playURLs:(id)arg1;
- (void)setVideoPlayerFillMode:(unsigned long long)arg0;
- (void)setPlayAmbient:(BOOL)arg0;
- (void)reloadLocalURL:(id)arg0;
- (void)playWithoutPlayback;
- (void)setPauseOnResignActive:(BOOL)arg0;
- (BOOL)playAmbient;
- (BOOL)pauseOnResignActive;
- (unsigned long long)videoPlayerFillMode;
- (id)currentSnapShot;
- (BOOL)mute;
- (double)volume;
- (void)stop;
- (double)duration;
- (id)delegate;
- (BOOL)isPlaying;
- (void)setVolume:(double)arg0;
- (id)playerView;
- (void)setDelegate:(id)arg0;
- (void)play;
- (void)pause;
- (void)setMute:(BOOL)arg0;
- (double)playbackSpeed;
- (void)setPlaybackSpeed:(double)arg0;
- (BOOL)repeated;
- (void)setRepeated:(BOOL)arg0;
- (void)prepareToPlay;
- (void)addPeriodicTimeObserverForInterval:(double)arg0 queue:(id)arg1 usingBlock:(id /* block */)arg2;
- (double)durationWatched;
- (double)playableDuration;
- (id)videoID;

@optional

- (void)setPlayerSubTag:(id)arg0;
- (void)setPlayerTag:(id)arg0;
- (void)setupStartPlayTime:(double)arg0;
- (void)setupCacheSecondDuration:(int)arg0;

@end
