//
//     Generated by private class-dump
//

@class NSString;

@interface IESECGoodsDetailLeftPanGuideMetaModel : MTLModel <MTLJSONSerializing> {
    NSString *_jumpUrl;
}

@property (copy, nonatomic) NSString *jumpUrl;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)JSONKeyPathsByPropertyKey;

- (id)jumpUrl;
- (void)setJumpUrl:(id)arg0;
- (void).cxx_destruct;

@end
