//
//     Generated by private class-dump
//

@class IESECLiveContext, NSString, IESECTracker;
@protocol IESECShopAfterLiveCardProviderService, IESECWindowAfterLiveCardProviderService;

@interface IESECLiveAfterLiveCardProviderImpl : NSObject <IESECLiveAfterLiveCardProvider> {
    id<IESECShopAfterLiveCardProviderService> _shopProvider;
    id<IESECWindowAfterLiveCardProviderService> _windowProvider;
    IESECLiveContext *_liveContext;
    IESECTracker *_tracker;
}

@property (retain, nonatomic) IESECTracker *tracker;
@property (retain, nonatomic) IESECLiveContext *liveContext;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)setLiveContext:(id)arg0;
- (id)liveContext;
- (id)afterLiveCardWithData:(id)arg0 container:(id)arg1;
- (id)tracker;
- (void)setTracker:(id)arg0;
- (void).cxx_destruct;

@end
