//
//     Generated by private class-dump
//

@class NSArray, NSString;

@interface IESECGoodsDetailTipsSectionModel : NSObject {
    NSString *_sectionTitle;
    NSArray *_tipsModel;
    NSArray *_tips;
    NSArray *_tipsObject;
}

@property (copy, nonatomic) NSArray *tips;
@property (retain, nonatomic) NSArray *tipsObject;
@property (copy, nonatomic) NSString *sectionTitle;
@property (copy, nonatomic) NSArray *tipsModel;

- (id)tipsModel;
- (void)setTipsModel:(id)arg0;
- (void)addTipsFromArray:(id)arg0;
- (id)tipsObject;
- (void)setTipsObject:(id)arg0;
- (id)tips;
- (void).cxx_destruct;
- (void)setTips:(id)arg0;
- (id)sectionTitle;
- (void)setSectionTitle:(id)arg0;

@end
