//
//     Generated by private class-dump
//

@class NSArray;

@interface IESECCommentSKUViewModel : NSObject {
    NSArray *_skuModelArray;
}

@property (retain, nonatomic) NSArray *skuModelArray;

- (id)skuModelArray;
- (void)setSkuModelArray:(id)arg0;
- (void).cxx_destruct;

@end
