//
//     Generated by private class-dump
//

@class NSNumber;

@interface IESECPriceStringBuilder : IESECPriceStringConfiguration {
    id /* block */ _price;
    id /* block */ _prefix;
    id /* block */ _suffix;
    id /* block */ _addCrossLine;
    id /* block */ _hideIfNeed;
    id /* block */ _useSuffix;
    id /* block */ _maxPrice;
    id /* block */ _waitToShowPrice;
    NSNumber *_originPrice;
    id /* block */ _buildPriceBlock;
    id /* block */ _buildPrefixBlock;
    id /* block */ _buildSuffixBlock;
    id /* block */ _useSuffixBlock;
    id /* block */ _addCrossLineBlock;
    id /* block */ _hideIfNeedBlock;
    id /* block */ _maxPriceBlock;
    id /* block */ _waitToShowPriceBlock;
}

@property (copy, nonatomic) NSNumber *originPrice;
@property (copy, nonatomic) id /* block */ buildPriceBlock;
@property (copy, nonatomic) id /* block */ buildPrefixBlock;
@property (copy, nonatomic) id /* block */ buildSuffixBlock;
@property (copy, nonatomic) id /* block */ useSuffixBlock;
@property (copy, nonatomic) id /* block */ addCrossLineBlock;
@property (copy, nonatomic) id /* block */ hideIfNeedBlock;
@property (copy, nonatomic) id /* block */ maxPriceBlock;
@property (copy, nonatomic) id /* block */ waitToShowPriceBlock;
@property (copy, nonatomic) id /* block */ price;
@property (copy, nonatomic) id /* block */ prefix;
@property (copy, nonatomic) id /* block */ suffix;
@property (copy, nonatomic) id /* block */ addCrossLine;
@property (copy, nonatomic) id /* block */ hideIfNeed;
@property (copy, nonatomic) id /* block */ useSuffix;
@property (copy, nonatomic) id /* block */ maxPrice;
@property (copy, nonatomic) id /* block */ waitToShowPrice;

- (id)originPrice;
- (void)setOriginPrice:(id)arg0;
- (id /* block */)maxPrice;
- (void)setMaxPrice:(id /* block */)arg0;
- (void)removeBlock;
- (id /* block */)useSuffix;
- (id /* block */)addCrossLine;
- (id /* block */)hideIfNeed;
- (id)prefixAttributedString:(id)arg0;
- (id)tagAttributedString;
- (id)buildPrice:(id)arg0;
- (void)setBuildPriceBlock:(id /* block */)arg0;
- (id)buildPrefix:(id)arg0;
- (void)setBuildPrefixBlock:(id /* block */)arg0;
- (id)suffixAttributedString:(id)arg0;
- (void)setBuildSuffixBlock:(id /* block */)arg0;
- (id /* block */)buildPrefixBlock;
- (id /* block */)buildSuffixBlock;
- (void)setUseSuffixBlock:(id /* block */)arg0;
- (id)buildCrossLinePrice:(id)arg0;
- (void)setAddCrossLineBlock:(id /* block */)arg0;
- (void)setHideIfNeedBlock:(id /* block */)arg0;
- (id /* block */)useSuffixBlock;
- (id /* block */)buildPriceBlock;
- (id /* block */)addCrossLineBlock;
- (id /* block */)hideIfNeedBlock;
- (id /* block */)waitToShowPrice;
- (void)setAddCrossLine:(id /* block */)arg0;
- (void)setHideIfNeed:(id /* block */)arg0;
- (void)setUseSuffix:(id /* block */)arg0;
- (void)setWaitToShowPrice:(id /* block */)arg0;
- (id /* block */)maxPriceBlock;
- (void)setMaxPriceBlock:(id /* block */)arg0;
- (id /* block */)waitToShowPriceBlock;
- (void)setWaitToShowPriceBlock:(id /* block */)arg0;
- (id /* block */)price;
- (id /* block */)prefix;
- (void).cxx_destruct;
- (void)setSuffix:(id /* block */)arg0;
- (void)setPrefix:(id /* block */)arg0;
- (id /* block */)build;
- (id /* block */)suffix;
- (void)setPrice:(id /* block */)arg0;

@end
