//
//     Generated by private class-dump
//

@class NSMutableArray;
@protocol IESECShopProductsSelectButtonContainerDelegate;

@interface IESECShopProductsSelectButtonContainer : UIView {
    NSMutableArray *_buttons;
    id<IESECShopProductsSelectButtonContainerDelegate> _delegate;
}

@property (weak, nonatomic) id<IESECShopProductsSelectButtonContainerDelegate> delegate;

- (double)tagViewWidthWithCount:(long long)arg0;
- (void)handleTagDidClick:(id)arg0;
- (void)updateWithSelectButtons:(id)arg0;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (id)delegate;
- (void)layoutSubviews;
- (void)setDelegate:(id)arg0;

@end
