//
//     Generated by private class-dump
//

@class IESGCPDIContainer, IESGCPWidgetLoader;

@interface IESGCPBaseContainer : NSObject {
    long long _scene;
    IESGCPDIContainer *_diContainer;
    IESGCPWidgetLoader *_widgetLoader;
}

@property (nonatomic) long long scene;
@property (retain, nonatomic) IESGCPDIContainer *diContainer;
@property (retain, nonatomic) IESGCPWidgetLoader *widgetLoader;

- (id)initWithScene:(long long)arg0 diContext:(id)arg1 parentDI:(id)arg2;
- (void)createWidgets;
- (void)destroyContainer;
- (id)widgetLoader;
- (id)diContainer;
- (void)setDiContainer:(id)arg0;
- (void)setWidgetLoader:(id)arg0;
- (void)setScene:(long long)arg0;
- (void).cxx_destruct;
- (long long)scene;

@end
