//
//     Generated by private class-dump
//

@class IESGCPGetXplayResolutionInfoDataModel;

@interface IESGCPGetXplayResolutionInfoResultModel : IESLiveBridgeModel {
    IESGCPGetXplayResolutionInfoDataModel *_data;
}

@property (retain, nonatomic) IESGCPGetXplayResolutionInfoDataModel *data;

+ (id)modelCustomPropertyMapper;

- (id)data;
- (void).cxx_destruct;
- (void)setData:(id)arg0;

@end
