//
//     Generated by private class-dump
//

@class NSString;

@interface IESGCPVideoPlayManagerProvider_Douyin : NSObject <AWEGCPVideoPlayManagerProtocol>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (void)requestAwemeItemsWithIDs:(id)arg0 completion:(id /* block */)arg1;
+ (id)transformGameAwemeModelIESGCPGameFeedItems:(id)arg0;
+ (id)transformAwemeModelFromLiveRoom:(id)arg0;
+ (id)transformAwemeModelFromJsonString:(id)arg0;
+ (id)transformGameAwemeModelFromAwemeModel:(id)arg0 contentType:(int)arg1 mixId:(id)arg2;

@end
