//
//     Generated by private class-dump
//

@class NSString;

@interface IESGCPURLSchemaHandlerImpl : NSObject <IESGCPURLSchemaHandler>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)openURL:(id)arg0 userInfo:(id)arg1 completion:(id /* block */)arg2;
- (id)appendTrackerRouterInfoIfNeeded:(id)arg0;
- (BOOL)canOpenURL:(id)arg0;
- (void)openURL:(id)arg0;

@end
