//
//     Generated by private class-dump
//

@interface IESGCPXPlayGameFunctionPanelResolutionItem : IESGCPXPlayGameFunctionPanelItem

- (id)resolutionValueItems;
- (void)_switchResolution:(id)arg0;
- (id)imageName;
- (id)title;
- (id /* block */)action;

@end
