//
//     Generated by private class-dump
//

@class NSString;

@interface IESGCPPBCommentPrimaryTag : GPBMessage

@property (copy, nonatomic) NSString *tagId;
@property (copy, nonatomic) NSString *tagName;
@property (nonatomic) long long commentCount;

+ (id)descriptor;

- (id)tagString;

@end
