//
//     Generated by private class-dump
//

@class IESGCPReserveServiceImpl;

@interface IESGCPReserveWidget : IESGCPBaseWidget {
    IESGCPReserveServiceImpl *_serviceImpl;
}

@property (retain, nonatomic) IESGCPReserveServiceImpl *serviceImpl;

- (void)widgetBindService;
- (id)serviceImpl;
- (void)setServiceImpl:(id)arg0;
- (void).cxx_destruct;

@end
