//
//     Generated by private class-dump
//

@class NSMutableArray;

@interface IESGCPPBGetGameCPUserInfoByGUIDResponse_Data : GPBMessage

@property (retain, nonatomic) NSMutableArray *userInfoArray;
@property (readonly, nonatomic) unsigned long long userInfoArray_Count;

+ (id)descriptor;

@end
