//
//     Generated by private class-dump
//

@interface IESGurdPackagesTLBRequest : IESGurdMultiAccessKeysRequest {
    long long _requestType;
}

- (id)logInfo;
- (id)requestMetaDictionary;
- (id)statisticData;
- (BOOL)isParamsValid;
- (id)init;
- (void)setRequestType:(long long)arg0;
- (long long)requestType;

@end
