//
//     Generated by private class-dump
//

@protocol IESGCPDetailFilterViewDelegate <NSObject>

@optional

- (void)trackFilterViewExposedHandlerEventWithfilterCollectionView:(id)arg0 Index:(long long)arg1;
- (void)makeViewTrackNodeWithfilterCollectionView:(id)arg0 filterViewCell:(id)arg1 index:(long long)arg2 label:(id)arg3;
- (void)filterCollectionView:(id)arg0 didSelectAtIndexPath:(id)arg1;
- (void)filterCollectionView:(id)arg0 didDeselectItemAtIndexPath:(id)arg1;
- (void)filterCollectionView:(id)arg0 cellForItemAtIndexPath:(id)arg1 cell:(id)arg2;

@end
