//
//     Generated by private class-dump
//

@protocol IESLiveCaptureAction <NSObject>

@optional

- (void)stopAudioCapture;
- (void)startAudioCapture;
- (void)startVideoCapture;
- (void)stopVideoCapture;

@end
