//
//     Generated by private class-dump
//

@protocol IESLiveLinkmicSettingService <NSObject>

- (void)getBoolValueWithKey:(int)arg0 callback:(id /* block */)arg1;
- (void)getIntValueWithKey:(int)arg0 callback:(id /* block */)arg1;
- (void)getAllKeyWithCallback:(id /* block */)arg0;
- (void)getAllKeyWithCallback:(id /* block */)arg0 end:(id /* block */)arg1;
- (void)fetchSettingIfNeed:(id /* block */)arg0;
- (BOOL)getLocalBool:(int)arg0;
- (int)getLocalInt:(int)arg0;
- (id)getLocalValue:(int)arg0;
- (void)addListener:(id)arg0 keys:(id)arg1 callback:(id /* block */)arg2;
- (void)addListenerForAllKeys:(id)arg0 callback:(id /* block */)arg1;
- (void)addListenerForAllKeys:(id)arg0 callback:(id /* block */)arg1 onceMessage:(id /* block */)arg2;
- (void)updateSetting:(id)arg0 extParams:(id)arg1 callback:(id /* block */)arg2;
- (void)fetchAudienceSettings:(id)arg0 callback:(id /* block */)arg1;
- (void)updateAudienceSettings:(int)arg0 status:(int)arg1 callback:(id /* block */)arg2;
- (void)fetchSettingIgnoreCache:(id /* block */)arg0;
- (void)setNeedUpdateCache;
- (void)addCacheWithKey:(int)arg0 value:(BOOL)arg1;
- (void)removeCacheWithKey:(int)arg0;
- (void)removeListener:(id)arg0;

@end
