//
//     Generated by private class-dump
//

@interface IESLiveInteractLocalVideoStats : NSObject {
    double _sentKBitrate;
}

@property (nonatomic) double sentKBitrate;

- (void)setSentKBitrate:(double)arg0;
- (double)sentKBitrate;

@end
