//
//     Generated by private class-dump
//

@class HTSLiveUser;
@protocol IESLiveWebPDecoder;

@interface IESLiveInteractGiftAnimationInfo : NSObject {
    HTSLiveUser *_user;
    long long _durationMs;
    id<IESLiveWebPDecoder> _webpDecoder;
    double _radians;
    unsigned long long _type;
    id /* block */ _finishRenderCompletionBlock;
    id /* block */ _interruptPlayBlock;
    struct CGPoint { double x; double y; } _fromPoint;
    struct CGPoint { double x; double y; } _toPoint;
    struct CGSize { double width; double height; } _size;
}

@property (retain, nonatomic) HTSLiveUser *user;
@property (nonatomic) long long durationMs;
@property (retain, nonatomic) id<IESLiveWebPDecoder> webpDecoder;
@property (nonatomic) struct CGPoint { double x; double y; } fromPoint;
@property (nonatomic) struct CGPoint { double x; double y; } toPoint;
@property (nonatomic) double radians;
@property (nonatomic) struct CGSize { double width; double height; } size;
@property (nonatomic) unsigned long long type;
@property (copy, nonatomic) id /* block */ finishRenderCompletionBlock;
@property (copy, nonatomic) id /* block */ interruptPlayBlock;

- (id)webpDecoder;
- (id /* block */)finishRenderCompletionBlock;
- (void)setInterruptPlayBlock:(id /* block */)arg0;
- (id /* block */)interruptPlayBlock;
- (void)setWebpDecoder:(id)arg0;
- (void)setFinishRenderCompletionBlock:(id /* block */)arg0;
- (void)setRadians:(double)arg0;
- (void)setUser:(id)arg0;
- (void)setFromPoint:(struct CGPoint { double x0; double x1; })arg0;
- (id)user;
- (void).cxx_destruct;
- (unsigned long long)type;
- (void)setType:(unsigned long long)arg0;
- (struct CGSize { double x0; double x1; })size;
- (void)setSize:(struct CGSize { double x0; double x1; })arg0;
- (struct CGPoint { double x0; double x1; })fromPoint;
- (double)radians;
- (long long)durationMs;
- (void)setDurationMs:(long long)arg0;
- (struct CGPoint { double x0; double x1; })toPoint;
- (void)setToPoint:(struct CGPoint { double x0; double x1; })arg0;

@end
