//
//     Generated by private class-dump
//

@protocol IESLiveMultiTabViewDelegate <NSObject>

- (void)multiTabViewDidScrollToTabId:(long long)arg0;
- (void)multiTabViewDidScroll:(id)arg0;

@optional

- (void)multiTabViewDidScrollToTabId:(long long)arg0 fromTabId:(long long)arg1;
- (void)multiTabBubbleAction:(id)arg0 didAppear:(BOOL)arg1 actionType:(id)arg2;

@end
