//
//     Generated by private class-dump
//

@class IESLiveLinkMicAudienceGetUserFollowRelationResponse_ResponseData;

@interface IESLiveLinkMicAudienceGetUserFollowRelationResponse : IESLivePBBaseMessage

@property (retain, nonatomic) IESLiveLinkMicAudienceGetUserFollowRelationResponse_ResponseData *data_p;
@property (nonatomic) BOOL hasData_p;

+ (id)descriptor;

@end
