//
//     Generated by private class-dump
//

@class NSNumber, NSDictionary, NSString;

@interface IESLiveInteractionCropData : MTLModel <MTLJSONSerializing> {
    NSNumber *_cropH;
    NSNumber *_cropW;
    NSNumber *_cropX;
    NSNumber *_cropY;
    NSNumber *_strideH;
    NSNumber *_strideW;
}

@property (retain, nonatomic) NSNumber *cropH;
@property (retain, nonatomic) NSNumber *cropW;
@property (retain, nonatomic) NSNumber *cropX;
@property (retain, nonatomic) NSNumber *cropY;
@property (retain, nonatomic) NSNumber *strideH;
@property (retain, nonatomic) NSNumber *strideW;
@property (readonly, copy, nonatomic) NSDictionary *dictionaryValue;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)JSONKeyPathsByPropertyKey;

- (id)cropW;
- (id)cropH;
- (id)strideW;
- (id)strideH;
- (void)setStrideH:(id)arg0;
- (void)setStrideW:(id)arg0;
- (void)setCropH:(id)arg0;
- (void)setCropW:(id)arg0;
- (void)setCropX:(id)arg0;
- (void)setCropY:(id)arg0;
- (void).cxx_destruct;
- (id)cropX;
- (id)cropY;

@end
