//
//     Generated by private class-dump
//

@protocol IESLiveCommunityInteractModuleAdapter <NSObject>

- (id)communityInteractSubInterface;

@optional

- (unsigned long long)currentInteractiveScene;
- (struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })streamRect;

@end
