//
//     Generated by private class-dump
//

@interface IESLiveSetAdminPermissionResultMethodImpl : IESLiveSetAdminPermissionResultMethod

- (void)callWithParamModel:(id)arg0 completionHandler:(id /* block */)arg1;

@end
