//
//     Generated by private class-dump
//

@class IESLiveGameOpenPlatformAudienceDebugHandler;
@protocol IESLiveRoomService, IESLiveGameOpenPlatformContext;

@interface IESLiveGameOpenPlatformAudienceStore : NSObject {
    id<IESLiveRoomService> _room;
    IESLiveGameOpenPlatformAudienceDebugHandler *_debugHandler;
    id<IESLiveGameOpenPlatformContext> _openPlatformContext;
}

@property (retain, nonatomic) id<IESLiveRoomService> room;
@property (retain, nonatomic) IESLiveGameOpenPlatformAudienceDebugHandler *debugHandler;
@property (retain, nonatomic) id<IESLiveGameOpenPlatformContext> openPlatformContext;

- (void)didSetAttachingDIContext;
- (id)initWithComponentContext:(id)arg0 eventContext:(id)arg1 room:(id)arg2;
- (id)debugHandler;
- (void)setDebugHandler:(id)arg0;
- (id)openPlatformContext;
- (void)setOpenPlatformContext:(id)arg0;
- (void).cxx_destruct;
- (id)room;
- (void)setRoom:(id)arg0;

@end
