//
//     Generated by private class-dump
//

@class NSDictionary, NSString, IESLatchFlatSchema;

@interface IESLatchTemplateInput : NSObject <IESLatchTemplateInput> {
    NSDictionary *variables;
    IESLatchFlatSchema *schema;
    NSString *name;
    NSString *traceId;
    NSDictionary *globalProps;
}

@property (copy, nonatomic) NSDictionary *variables;
@property (copy, nonatomic) NSString *name;
@property (retain, nonatomic) IESLatchFlatSchema *schema;
@property (copy, nonatomic) NSString *traceId;
@property (retain, nonatomic) NSDictionary *globalProps;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)setGlobalProps:(id)arg0;
- (id)globalProps;
- (void)setTraceId:(id)arg0;
- (void)setSchema:(id)arg0;
- (void).cxx_destruct;
- (id)traceId;
- (void)setName:(id)arg0;
- (id)schema;
- (id)name;
- (id)variables;
- (void)setVariables:(id)arg0;

@end
