//
//     Generated by private class-dump
//

@class NSString, UIView;
@protocol IESHYContainerProtocol;

@interface IESLivePortalLynxView : UIView <IESHYHybridViewLifecycleProtocol> {
    UIView<IESHYContainerProtocol> *_hybridContainer;
    id /* block */ _action;
    NSString *_clsName;
}

@property (copy, nonatomic) NSString *clsName;
@property (retain, nonatomic) UIView<IESHYContainerProtocol> *hybridContainer;
@property (copy, nonatomic) id /* block */ action;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)hybridContainer;
- (void)setHybridContainer:(id)arg0;
- (void)viewDidChangeIntrinsicContentSize:(struct CGSize { double x0; double x1; })arg0;
- (void)viewDidLoadFailedWithUrl:(id)arg0 error:(id)arg1;
- (void)onTapped;
- (void)buildWithType:(unsigned long long)arg0 param:(id)arg1;
- (void)buildLynxContainerWithUrl:(id)arg0 params:(id)arg1 clsName:(id)arg2;
- (void)setClsName:(id)arg0;
- (id)clsName;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (void)setAction:(id /* block */)arg0;
- (id /* block */)action;

@end
