//
//     Generated by private class-dump
//

@class NSNumber, NSString;

@interface IESLiveGetDownloadGiftAssetsParamModel : IESLiveBridgeModel {
    NSNumber *_assetId;
    NSString *_source;
}

@property (retain, nonatomic) NSNumber *assetId;
@property (copy, nonatomic) NSString *source;

+ (id)modelCustomPropertyMapper;

- (id)source;
- (void).cxx_destruct;
- (id)assetId;
- (void)setAssetId:(id)arg0;
- (void)setSource:(id)arg0;

@end
