//
//     Generated by private class-dump
//

@class NSNumber, IESLiveInteractiveLinkService;
@protocol IESLiveRoomServiceAdapter;

@interface IESLiveInteractiveUserServiceConfig : NSObject {
    BOOL _isAnchor;
    BOOL _enableDataVersionCheck;
    id<IESLiveRoomServiceAdapter> _roomModel;
    unsigned long long _scene;
    NSNumber *_channelID;
    NSNumber *_roomID;
    Class _modelClass;
    IESLiveInteractiveLinkService *_linkService;
    unsigned long long _fullLinkModule;
}

@property (retain, nonatomic) id<IESLiveRoomServiceAdapter> roomModel;
@property (nonatomic) unsigned long long scene;
@property (retain, nonatomic) NSNumber *channelID;
@property (nonatomic) BOOL isAnchor;
@property (retain, nonatomic) NSNumber *roomID;
@property (nonatomic) Class modelClass;
@property (retain, nonatomic) IESLiveInteractiveLinkService *linkService;
@property (nonatomic) unsigned long long fullLinkModule;
@property (nonatomic) BOOL enableDataVersionCheck;

- (id)roomModel;
- (void)setIsAnchor:(BOOL)arg0;
- (void)setRoomModel:(id)arg0;
- (id)linkService;
- (void)setLinkService:(id)arg0;
- (void)setEnableDataVersionCheck:(BOOL)arg0;
- (BOOL)enableDataVersionCheck;
- (unsigned long long)fullLinkModule;
- (void)setFullLinkModule:(unsigned long long)arg0;
- (id)init;
- (void)setScene:(unsigned long long)arg0;
- (id)channelID;
- (void).cxx_destruct;
- (BOOL)isAnchor;
- (Class)modelClass;
- (void)setModelClass:(Class)arg0;
- (void)setChannelID:(id)arg0;
- (unsigned long long)scene;
- (id)roomID;
- (void)setRoomID:(id)arg0;

@end
