//
//     Generated by private class-dump
//

@class HTSLiveAvatarImageView, HTSLiveUser;

@interface IESLiveMyLiveEntryView : UIButton {
    HTSLiveUser *_user;
    HTSLiveAvatarImageView *_avatarImageView;
}

@property (retain, nonatomic) HTSLiveUser *user;
@property (retain, nonatomic) HTSLiveAvatarImageView *avatarImageView;

- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0 user:(id)arg1;
- (void)loadAvatarAndBorder;
- (void)setUser:(id)arg0;
- (id)user;
- (void).cxx_destruct;
- (struct CGSize { double x0; double x1; })intrinsicContentSize;
- (id)avatarImageView;
- (void)setAvatarImageView:(id)arg0;
- (void)setupViews;
- (void)updateUser:(id)arg0;

@end
