//
//     Generated by private class-dump
//

@protocol IESLiveOpenPlatformExplainCardActions <NSObject>

@optional

- (void)closeExplainCardWithAppId:(id)arg0;
- (void)tapExplainCardWithAppId:(id)arg0 schema:(id)arg1;
- (void)explainCardDidShowOvertime:(id)arg0;
- (void)shouldShowExplainCard:(id)arg0;

@end
