//
//     Generated by private class-dump
//

@class NSTimer, IESLiveLinkMicProfitRoomBattleRandomMatchMatchingContent, HTSLiveLinkmicRoomBattleMatchSuccessContent, NSMutableArray, NSNumber;

@interface IESLiveRoomBattleMatchWaitingContent : NSObject {
    BOOL _hasSpeedup;
    IESLiveLinkMicProfitRoomBattleRandomMatchMatchingContent *_matchingContent;
    double _startWaitingTime;
    long long _expectedWaitingTime;
    long long _waitingTime;
    NSNumber *_realWaitingTime;
    HTSLiveLinkmicRoomBattleMatchSuccessContent *_successContent;
    NSTimer *_timer;
    NSMutableArray *_timeoutActions;
}

@property (retain, nonatomic) NSTimer *timer;
@property (retain, nonatomic) NSMutableArray *timeoutActions;
@property (retain, nonatomic) IESLiveLinkMicProfitRoomBattleRandomMatchMatchingContent *matchingContent;
@property (nonatomic) double startWaitingTime;
@property (nonatomic) long long expectedWaitingTime;
@property (nonatomic) long long waitingTime;
@property (retain, nonatomic) NSNumber *realWaitingTime;
@property (retain, nonatomic) HTSLiveLinkmicRoomBattleMatchSuccessContent *successContent;
@property (nonatomic) BOOL hasSpeedup;

- (long long)waitingTime;
- (void)setWaitingTime:(long long)arg0;
- (id)matchingContent;
- (void)setMatchingContent:(id)arg0;
- (void)setHasSpeedup:(BOOL)arg0;
- (void)startWaiting:(long long)arg0 timeoutAction:(id /* block */)arg1;
- (void)stopWaitingTimer;
- (void)setSuccessContent:(id)arg0;
- (void)setExpectedWaitingTime:(long long)arg0;
- (id)successContent;
- (long long)expectedWaitingTime;
- (id)realWaitingTime;
- (BOOL)hasSpeedup;
- (void)startWaitingTimer;
- (id)timeoutActions;
- (void)setStartWaitingTime:(double)arg0;
- (void)setTimeoutActions:(id)arg0;
- (double)startWaitingTime;
- (void)setRealWaitingTime:(id)arg0;
- (id)timer;
- (BOOL)isFinished;
- (void).cxx_destruct;
- (void)setTimer:(id)arg0;
- (void)dealloc;

@end
