//
//     Generated by private class-dump
//

@protocol IESLiveSubscription, IESLivePublisher;

@interface IESLiveTakeUntilPublisher : IESLivePublisher {
    id<IESLivePublisher> _upstream;
    id<IESLiveSubscription> _externalSubscription;
}

@property (retain, nonatomic) id<IESLivePublisher> upstream;
@property (retain, nonatomic) id<IESLiveSubscription> externalSubscription;

- (void)subscribe:(id)arg0 bindingToSubscription:(id)arg1;
- (id)initWithUpstream:(id)arg0 subscription:(id)arg1;
- (id)externalSubscription;
- (void)setExternalSubscription:(id)arg0;
- (id)upstream;
- (void).cxx_destruct;
- (void)setUpstream:(id)arg0;

@end
