//
//     Generated by private class-dump
//

@class IESLiveInnerFeedContext, NSString;

@interface IESLiveInnerFeedAudienceVCLifeCycleController : NSObject <IESLiveInnerFeedDisplayAction> {
    BOOL _enterRoomOptimize;
    IESLiveInnerFeedContext *_context;
}

@property (retain, nonatomic) IESLiveInnerFeedContext *context;
@property (nonatomic) BOOL enterRoomOptimize;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)didSetAttachingDIContext;
- (void)setEnterRoomOptimize:(BOOL)arg0;
- (void)innerFeedWillEndDragging:(id)arg0 withVelocity:(struct CGPoint { double x0; double x1; })arg1 targetContentOffset:(inout struct CGPoint { double x0; double x1; } *)arg2;
- (BOOL)enterRoomOptimize;
- (id)initWithContext:(id)arg0;
- (void).cxx_destruct;
- (void)setContext:(id)arg0;
- (id)context;

@end
