//
//     Generated by private class-dump
//

@class NSArray, IESLiveRedeemResponseModelExtra, NSDictionary, NSString;

@interface IESLiveRedeemResponseModel : IESLiveDynamicMTLModel <MTLJSONSerializing> {
    IESLiveRedeemResponseModelExtra *_extra;
}

@property (retain, nonatomic) NSArray *redeemModels;
@property (retain, nonatomic) IESLiveRedeemResponseModelExtra *extra;
@property (readonly, copy, nonatomic) NSDictionary *dictionaryValue;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)redeemModelsJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;

- (void)setExtra:(id)arg0;
- (void).cxx_destruct;
- (id)extra;

@end
