//
//     Generated by private class-dump
//

@protocol IESLiveSlideBeautyViewModelDelegate <NSObject>

- (void)removeBeautyTemplate;
- (void)changeBeautySwitchStatus:(BOOL)arg0;
- (void)cameraDidRemoveCurrentMakeup;
- (void)removeMakeupByTemplate;
- (void)refreshBeautyResetButtonStatus;
- (void)slidePickerViewDidClearRedDot:(id)arg0;
- (void)slidePickerView:(id)arg0 didApplyMakeup:(id)arg1;
- (void)slidePickerView:(id)arg0 didExpandItem:(id)arg1 toItems:(id)arg2 selectedIndex:(long long)arg3;
- (void)slidePickerView:(id)arg0 didClickBackButton:(id)arg1;
- (void)slidePickerView:(id)arg0 didSelectTemplete:(id)arg1;

@end
