//
//     Generated by private class-dump
//

@class NSNumber;

@interface IESLiveMoveGoldboxLocationMethodPanelSizeModel : IESLiveBridgeModel {
    NSNumber *_height;
    NSNumber *_weight;
}

@property (retain, nonatomic) NSNumber *height;
@property (retain, nonatomic) NSNumber *weight;

+ (id)modelCustomPropertyMapper;

- (id)weight;
- (void)setWeight:(id)arg0;
- (void).cxx_destruct;
- (id)height;
- (void)setHeight:(id)arg0;

@end
