//
//     Generated by private class-dump
//

@protocol IESLiveFunctionSquareCategoryTableViewCellDelegate <NSObject>

- (void)contentCellDidSelectItem:(id)arg0;
- (void)contentCellWillShowRowNode:(id)arg0;
- (void)contentCellDidScrollToIndex:(long long)arg0;
- (void)contentCellDidScrollWithContentOffset:(double)arg0;

@end
