//
//     Generated by private class-dump
//

@class NSString, NSMapTable, HTSLiveRoom;
@protocol IESLiveRoomService, IESLiveInteractionAsyncResourceLoader;

@interface IESLiveBigPartyPreStreamAdapterWrapper : NSObject <IESLiveBigPartyPreStreamStageHelperAdapter, IESLiveBigPartyPreStreamStageRoomThemeUpdater, IESLiveBigPartyPreStreamStageRoomGetterAdapter, IESLiveInteractionAsyncResourceLoader, IESLiveInteractionAsyncResourceLoading> {
    id<IESLiveInteractionAsyncResourceLoader> _asyncResourceLoader;
    NSMapTable *_currentThemeDataMap;
    id<IESLiveRoomService> _roomModel;
    HTSLiveRoom *_liveRoomModel;
}

@property (retain, nonatomic) NSMapTable *currentThemeDataMap;
@property (retain, nonatomic) id<IESLiveRoomService> roomModel;
@property (retain, nonatomic) HTSLiveRoom *liveRoomModel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak, nonatomic) id<IESLiveInteractionAsyncResourceLoader> asyncResourceLoader;

- (id)roomModel;
- (id)liveRoomModel;
- (void)setLiveRoomModel:(id)arg0;
- (void)setRoomModel:(id)arg0;
- (void)setAsyncResourceLoader:(id)arg0;
- (id)asyncResourceLoader;
- (void)asyncLoadResourceUsingBlock:(id /* block */)arg0;
- (void)updateRoomThemeData:(id)arg0;
- (id)currentThemeDataMap;
- (BOOL)isAnchorWithUserID:(id)arg0;
- (void)updateRoomThemeImage:(id)arg0;
- (void)updateRoomThemeIconMics:(id)arg0;
- (id)roomForStage;
- (void)setCurrentThemeDataMap:(id)arg0;
- (void).cxx_destruct;
- (void)updateModel:(id)arg0;

@end
