//
//     Generated by private class-dump
//

@class IESLiveIMWebSocketFetcher, IESLiveIMBaseChannel, NSString, IESLiveIMConfig, NSDictionary, IESLiveIMHTTPFetcher;
@protocol IESLiveIMClientParamsConfig, IESLiveIMClientDataReceiver;

@interface IESLiveIMClientWrapper : NSObject <IESLiveIMChannelDelegate> {
    BOOL _isStarted;
    id<IESLiveIMClientParamsConfig> _paramsConfig;
    id<IESLiveIMClientDataReceiver> _dataReceiver;
    IESLiveIMConfig *_imConfig;
    IESLiveIMBaseChannel *_imChannel;
    IESLiveIMWebSocketFetcher *_wsFetcher;
    IESLiveIMHTTPFetcher *_httpFetcher;
    NSString *_pushServer;
    NSString *_cursor;
    NSString *_internalExt;
    NSDictionary *_routeParams;
}

@property (nonatomic) BOOL isStarted;
@property (retain, nonatomic) IESLiveIMConfig *imConfig;
@property (weak, nonatomic) id<IESLiveIMClientParamsConfig> paramsConfig;
@property (weak, nonatomic) id<IESLiveIMClientDataReceiver> dataReceiver;
@property (retain, nonatomic) IESLiveIMBaseChannel *imChannel;
@property (retain, nonatomic) IESLiveIMWebSocketFetcher *wsFetcher;
@property (retain, nonatomic) IESLiveIMHTTPFetcher *httpFetcher;
@property (copy, nonatomic) NSString *pushServer;
@property (copy, nonatomic) NSString *cursor;
@property (copy, nonatomic) NSString *internalExt;
@property (copy, nonatomic) NSDictionary *routeParams;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)setupWithConfig:(id)arg0;
- (void)logEvent:(id)arg0 params:(id)arg1;
- (void)setRouteParams:(id)arg0;
- (id)routeParams;
- (void)setParamsConfig:(id)arg0;
- (id)paramsConfig;
- (id)pushServer;
- (void)setPushServer:(id)arg0;
- (void)channel:(id)arg0 received:(id)arg1;
- (void)channel:(id)arg0 closed:(id)arg1;
- (id)assembleHttpQuerys:(id)arg0;
- (id)assembleHttpFetcherParams:(id)arg0;
- (id)assembleHttpHeaders:(id)arg0;
- (id)httpBodyField;
- (void)setHttpFetcher:(id)arg0;
- (id)httpFetcher;
- (id)imConfig;
- (id)defaultWebsocketUrl;
- (id)assembleWsFetcherHeaders:(id)arg0;
- (id)assembleWsFetcherParams:(id)arg0;
- (void)setWsFetcher:(id)arg0;
- (id)wsFetcher;
- (void)setImConfig:(id)arg0;
- (void)setupHttpFetcherWithConfig:(id)arg0;
- (void)setupWsFetcherWithConfig:(id)arg0;
- (void)setImChannel:(id)arg0;
- (id)imChannel;
- (BOOL)isWebsocketFirst;
- (void)setInternalExt:(id)arg0;
- (id)dataReceiver;
- (id)initWithNetConfig:(id)arg0 imConfig:(id)arg1;
- (void)setDataReceiver:(id)arg0;
- (id)internalExt;
- (id)cursor;
- (BOOL)isStarted;
- (void).cxx_destruct;
- (void)reconnect;
- (void)stop;
- (id)httpUrl;
- (void)start;
- (void)setCursor:(id)arg0;
- (void)setIsStarted:(BOOL)arg0;

@end
