//
//     Generated by private class-dump
//

@class IESLiveInnerFeedContext, NSString;

@interface IESLiveInnerFeedCommerceSlardarController : NSObject <IESLiveInnerFeedDisplayAction> {
    IESLiveInnerFeedContext *_context;
}

@property (retain, nonatomic) IESLiveInnerFeedContext *context;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)didSetAttachingDIContext;
- (void)innerFeedWillDisplayObject:(id)arg0 atIndex:(long long)arg1;
- (void)innerFeedDidEndDisplayObject:(id)arg0 atIndex:(long long)arg1;
- (id)initWithContext:(id)arg0;
- (void).cxx_destruct;
- (void)setContext:(id)arg0;
- (id)context;
- (void)dealloc;

@end
