//
//     Generated by private class-dump
//

@class IESLiveRevenueInteractPlayAnchorModel;

@interface IESLiveMultiLinkerBaseBattleScoreView : UIView {
    BOOL _isShowingEggTipsOrNotice;
    BOOL _isDoingTeamTask;
    BOOL _isFocus;
    id /* block */ _clickBlock;
    IESLiveRevenueInteractPlayAnchorModel *_model;
    id /* block */ _clickSubContent;
}

@property (copy, nonatomic) id /* block */ clickBlock;
@property (nonatomic) BOOL isShowingEggTipsOrNotice;
@property (nonatomic) BOOL isDoingTeamTask;
@property (nonatomic) BOOL isFocus;
@property (retain, nonatomic) IESLiveRevenueInteractPlayAnchorModel *model;
@property (copy, nonatomic) id /* block */ clickSubContent;

- (void)setClickBlock:(id /* block */)arg0;
- (id /* block */)clickBlock;
- (void)addTapGesture;
- (void)clickInfoView;
- (void)updateScoreWithModel:(id)arg0;
- (void)updateScoreLabelText:(id)arg0 showingTipsOrNotice:(BOOL)arg1;
- (void)updateLayoutToSmallViewStyle:(BOOL)arg0;
- (void)refreshMidIconURLList:(id)arg0 subContent:(id)arg1;
- (void)setIsDoingTeamTask:(BOOL)arg0;
- (void)updateUIInFinalPKPhase;
- (void)updateUIInPunish;
- (void)doRankChangeAnimationWithFromRank:(long long)arg0 toRank:(long long)arg1 completion:(id /* block */)arg2;
- (void)updateHiddenScore:(BOOL)arg0 hiddenRank:(BOOL)arg1;
- (BOOL)isShowingEggTipsOrNotice;
- (void)setIsShowingEggTipsOrNotice:(BOOL)arg0;
- (BOOL)isDoingTeamTask;
- (id /* block */)clickSubContent;
- (void)setClickSubContent:(id /* block */)arg0;
- (void)setModel:(id)arg0;
- (id)init;
- (void).cxx_destruct;
- (id)model;
- (void)setIsFocus:(BOOL)arg0;
- (BOOL)isFocus;

@end
