//
//     Generated by private class-dump
//

@class UILabel, FLAnimatedImageView;

@interface IESLiveFeedBannerCell : UICollectionViewCell {
    FLAnimatedImageView *_bannerImage;
    UILabel *_tipLabel;
}

@property (retain, nonatomic) FLAnimatedImageView *bannerImage;
@property (retain, nonatomic) UILabel *tipLabel;

- (void)updateWithBannerModel:(id)arg0;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x0; double x1; } x0; struct CGSize { double x0; double x1; } x1; })arg0;
- (void)prepareForReuse;
- (id)tipLabel;
- (void)setTipLabel:(id)arg0;
- (void)setupUI;
- (id)bannerImage;
- (void)setBannerImage:(id)arg0;

@end
