//
//     Generated by private class-dump
//

@class IESLiveInteractiveUserService, IESLiveScreencastLinkerModel, NSString;
@protocol IESLiveRoomService, IESLiveScreencastLinkAnchorParticipationInfo;

@protocol IESLiveScreencastLinkerAnchorProvider <IESLiveScreencastLinkerAnchorLifeCycle>

@property (retain, nonatomic) id<IESLiveRoomService> room;
@property (retain, nonatomic) IESLiveScreencastLinkerModel *linkerModel;
@property (nonatomic) unsigned long long finishReason;
@property (readonly, nonatomic) IESLiveInteractiveUserService *userService;
@property (weak, nonatomic) id<IESLiveScreencastLinkAnchorParticipationInfo> anchorParticipationInfo;
@property (copy, nonatomic) NSString *remoteAnchorLinkmicIdStr;
@property (copy, nonatomic) NSString *notificationContent;

- (void)setFinishReason:(unsigned long long)arg0;
- (unsigned long long)finishReason;
- (id)userService;
- (id)linkerModel;
- (void)setLinkerModel:(id)arg0;
- (id)room;
- (void)setRoom:(id)arg0;

@optional

- (id)anchorParticipationInfo;
- (void)setAnchorParticipationInfo:(id)arg0;
- (id)notificationContent;
- (void)setNotificationContent:(id)arg0;
- (void)reportCommonTrackerWithEvent:(id)arg0 extra:(id)arg1;
- (BOOL)getLocalLinkMuteStatus;
- (id)remoteAnchorLinkmicIdStr;
- (void)setRemoteAnchorLinkmicIdStr:(id)arg0;

@end
