//
//     Generated by private class-dump
//

@protocol IESLiveGameOpenPlatformContainerServiceObserver <NSObject>

- (void)containerCommunicationService:(id)arg0 notifyContainerWithEvent:(id)arg1 params:(id)arg2;

@end
