//
//     Generated by private class-dump
//

@class NSString;

@interface IESLiveUserUtilsAdapterImpl : IESLiveBaseAdapter <IESLiveUserUtilsAdapter>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)getDisplayNameWithNickName:(id)arg0 desensitizedNickName:(id)arg1 displayID:(id)arg2 userID:(id)arg3 underUISetting:(BOOL)arg4;
- (id)getDisplayNameWithNickName:(id)arg0 displayID:(id)arg1 userID:(id)arg2 underUISetting:(BOOL)arg3;
- (id)getDisplayNameWithNickName:(id)arg0 displayID:(id)arg1 userID:(id)arg2 onlyUnderUIAspectSetting:(BOOL)arg3;
- (id)getDisplayTextOnlyUnderUIAsepctSetting:(BOOL)arg0 useHost:(BOOL)arg1 user:(id)arg2;
- (id)getDisplayTextOnlyUnderUIAsepctSetting:(BOOL)arg0 checkSensitive:(BOOL)arg1 user:(id)arg2;
- (id)getRealtimeLocationCityWithUser:(id)arg0;
- (id)getDisplayTextWithUser:(id)arg0;
- (id)getAtUserDisplayTextUnderUISetting:(BOOL)arg0 user:(id)arg1;
- (id)getUserNicknameByReplaceByDotFromUser:(id)arg0;

@end
