//
//     Generated by private class-dump
//

@class NSArray, UIImageView, NSString, UILabel, UIButton;

@interface IESLivePadCastLoginView : UIView {
    BOOL _isCancel;
    NSArray *_avatarImageURLs;
    NSString *_nickName;
    id /* block */ _cancelBlock;
    id /* block */ _confirmBlock;
    long long _cancelButtonTimeLeft;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    UIImageView *_avatarImageView;
    UILabel *_nickNameLabel;
    UIButton *_cancelButton;
    UIButton *_confirmButton;
    UIButton *_closeButton;
}

@property (nonatomic) long long cancelButtonTimeLeft;
@property (retain, nonatomic) UILabel *titleLabel;
@property (retain, nonatomic) UILabel *subTitleLabel;
@property (retain, nonatomic) UIImageView *avatarImageView;
@property (retain, nonatomic) UILabel *nickNameLabel;
@property (retain, nonatomic) UIButton *cancelButton;
@property (retain, nonatomic) UIButton *confirmButton;
@property (retain, nonatomic) UIButton *closeButton;
@property (nonatomic) BOOL isCancel;
@property (retain, nonatomic) NSArray *avatarImageURLs;
@property (copy, nonatomic) NSString *nickName;
@property (copy, nonatomic) id /* block */ cancelBlock;
@property (copy, nonatomic) id /* block */ confirmBlock;

- (id /* block */)confirmBlock;
- (void)setConfirmBlock:(id /* block */)arg0;
- (id)nickNameLabel;
- (void)setNickNameLabel:(id)arg0;
- (void)setCancelButtonTimeLeft:(long long)arg0;
- (void)updateCancelButtonTitle;
- (void)cutDownCancelButtonTimeLeft;
- (long long)cancelButtonTimeLeft;
- (void)setAvatarImageURLs:(id)arg0;
- (id)avatarImageURLs;
- (void)setCancelButton:(id)arg0;
- (id)init;
- (void)setNickName:(id)arg0;
- (id /* block */)cancelBlock;
- (void).cxx_destruct;
- (id)cancelButton;
- (id)titleLabel;
- (id)nickName;
- (void)cancelAction;
- (void)setCancelBlock:(id /* block */)arg0;
- (void)setTitleLabel:(id)arg0;
- (void)setupUI;
- (id)avatarImageView;
- (void)setAvatarImageView:(id)arg0;
- (BOOL)isCancel;
- (void)setIsCancel:(BOOL)arg0;
- (id)confirmButton;
- (void)setConfirmButton:(id)arg0;
- (id)subTitleLabel;
- (void)setSubTitleLabel:(id)arg0;
- (id)closeButton;
- (void)setCloseButton:(id)arg0;

@end
