//
//     Generated by private class-dump
//

@class IESLiveLinkMicListResponse_ResponseData;

@interface IESLiveLinkMicListResponse : IESLivePBBaseMessage

@property (retain, nonatomic) IESLiveLinkMicListResponse_ResponseData *data_p;
@property (nonatomic) BOOL hasData_p;

+ (id)descriptor;

@end
