//
//     Generated by private class-dump
//

@class NSString;
@protocol IESLiveContainerRouter, IESLiveInteractiveAdminActions;

@interface IESLiveUserPreviewJSBHandler : NSObject <IESLivePiperHandlerProtocol> {
    id<IESLiveContainerRouter> _containerRouter;
    id<IESLiveInteractiveAdminActions> _adminInteractiveActions;
}

@property (retain, nonatomic) id<IESLiveContainerRouter> containerRouter;
@property (retain, nonatomic) id<IESLiveInteractiveAdminActions> adminInteractiveActions;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (void)registerHandlerWithBridge:(id)arg0;
- (id)containerRouter;
- (void)setContainerRouter:(id)arg0;
- (void)closeContainer:(id)arg0 animate:(BOOL)arg1 completion:(id /* block */)arg2;
- (id)adminInteractiveActions;
- (void)setAdminInteractiveActions:(id)arg0;
- (void).cxx_destruct;

@end
