//
//     Generated by private class-dump
//

@protocol IESMMAudioProcessProtocol <NSObject>

@property (nonatomic) BOOL useAudioEffectSticker;
@property (nonatomic) BOOL effectNodeInAudioChainIsOn;
@property (nonatomic) BOOL useAudioBackend;

- (BOOL)effectNodeInAudioChainIsOn;
- (void)setEffectNodeInAudioChainIsOn:(BOOL)arg0;
- (BOOL)setMusicPlayMode:(long long)arg0;
- (BOOL)useAudioEffectSticker;
- (BOOL)useAudioBackend;
- (void)setAudioSampleRate:(int)arg0 channel:(int)arg1;
- (BOOL)needProcessAudio;
- (void)processAudio:(struct opaqueCMSampleBuffer { } *)arg0;
- (void)finishAudioProcess;
- (BOOL)needResolveAudio;
- (void)resolveAudio:(struct opaqueCMSampleBuffer { } *)arg0;
- (void)finishAudioResolve;
- (void)sendAudioBuffer:(struct AudioBuffer { unsigned int x0; unsigned int x1; void *x2; })arg0;
- (void)setUseAudioEffectSticker:(BOOL)arg0;
- (void)setUseAudioBackend:(BOOL)arg0;

@end
