//
//     Generated by private class-dump
//

@class NSString;

@interface IESMMAudioPitchConfigV2 : IESMMAudioEffectConfig {
    int _sampleRate;
    int _channel;
    NSString *_effectPath;
    NSString *_infoData;
}

@property (copy, nonatomic) NSString *effectPath;
@property (copy, nonatomic) NSString *infoData;
@property (nonatomic) int sampleRate;
@property (nonatomic) int channel;

- (id)effectPath;
- (void)setEffectPath:(id)arg0;
- (void)setInfoData:(id)arg0;
- (id)toDicInfo;
- (void)setupDefaultValues;
- (int)channel;
- (void).cxx_destruct;
- (int)sampleRate;
- (void)setChannel:(int)arg0;
- (id)copyWithZone:(struct _NSZone { } *)arg0;
- (id)description;
- (void)setSampleRate:(int)arg0;
- (id)infoData;

@end
