//
//     Generated by private class-dump
//

@class IESOuterTestConfig;

@interface IESOuterTest : NSObject {
    IESOuterTestConfig *_config;
}

@property (retain, nonatomic) IESOuterTestConfig *config;

+ (id)secureLinkBaseUrl;
+ (void)updateUIStyle:(long long)arg0;
+ (void)popupOuterTestNewVersionIfNeededWithTraceParams:(id /* block */)arg0 frequencyControl:(id /* block */)arg1 popupBlock:(id /* block */)arg2;
+ (void)popupOuterTestNewVersionIfNeededWithTraceParams:(id /* block */)arg0 frequencyControl:(id /* block */)arg1 popupBlock:(id /* block */)arg2;
+ (void)joinOuterTestNewVersionIfNeededWithTraceParams:(id /* block */)arg0 frequencyControl:(id /* block */)arg1 popupBlock:(id /* block */)arg2;
+ (void)joinOuterTestNewVersionIfNeededWithTraceParams:(id /* block */)arg0 frequencyControl:(id /* block */)arg1 popupBlock:(id /* block */)arg2;
+ (void)joinOuterTestNewVersionTask:(id)arg0 withTraceParams:(id /* block */)arg1 popupBlock:(id /* block */)arg2;
+ (void)joinOuterTestNewVersionTask:(id)arg0 withTraceParams:(id /* block */)arg1 popupBlock:(id /* block */)arg2;
+ (id)packageInstallGuideControllerWithDownloadURL:(id)arg0 traceEvent:(id)arg1 traceParams:(id)arg2;
+ (id)packageInstallGuideControllerWithDownloadURL:(id)arg0 traceEvent:(id)arg1 traceParams:(id)arg2;
+ (void)openOuterTestWebViewWithURLStr:(id)arg0 params:(id)arg1 fromController:(id)arg2;
+ (void)openOuterTestWebViewWithURLStr:(id)arg0 params:(id)arg1 fromController:(id)arg2;
+ (id)jsbDomainAllowList;
+ (BOOL)enableSecLink;
+ (void)popupOuterTestNewVersionIfNeededWithCustomHeaders:(id)arg0 traceParams:(id /* block */)arg1 frequencyControl:(id /* block */)arg2 popupBlock:(id /* block */)arg3;
+ (id)sloganString;
+ (void)configBDWebSecLink;
+ (id)secureLinkDefaultBaseUrl;
+ (void)initialize;
+ (id)sharedInstance;
+ (void)updateLocale:(id)arg0;
+ (void)setup:(id /* block */)arg0;

- (void)setConfig:(id)arg0;
- (void).cxx_destruct;
- (id)config;

@end
