//
//     Generated by private class-dump
//

@class NSMutableDictionary, IESBridgeEngine, IESBridgeEngine_Deprecated, NSMutableSet, UIView;
@protocol IESBridgeExecutor;

@interface IESPiper : NSObject {
    int _uniqueID;
    NSMutableSet *_publicCallSet;
    NSMutableSet *_protectedSet;
    NSMutableSet *_privateSet;
    UIView<IESBridgeExecutor> *_webView;
    IESBridgeEngine_Deprecated *_deprecatedBridgeEngine;
    NSMutableDictionary *_callbackHandlers;
}

@property (readonly, nonatomic) IESBridgeEngine *bridgeEngine;
@property (retain, nonatomic) IESBridgeEngine_Deprecated *deprecatedBridgeEngine;
@property (retain, nonatomic) NSMutableDictionary *callbackHandlers;
@property (nonatomic) int uniqueID;
@property (readonly, nonatomic) NSMutableSet *publicCallSet;
@property (readonly, nonatomic) NSMutableSet *protectedSet;
@property (readonly, nonatomic) NSMutableSet *privateSet;
@property (weak, nonatomic) UIView<IESBridgeExecutor> *webView;

+ (id)currentJSSDKVersion;

- (id)bridgeEngine;
- (void)invokeJSWithEventID:(id)arg0 parameters:(id)arg1 finishBlock:(id /* block */)arg2;
- (void)registerHandlerBlock:(id /* block */)arg0 forJSMethod:(id)arg1 authType:(unsigned long long)arg2;
- (void)invokeJSWithCallbackID:(id)arg0 parameters:(id)arg1;
- (id)publicCallSet;
- (id)protectedSet;
- (id)privateSet;
- (void)registerJS2NativeHandlerBlock:(id /* block */)arg0 forJSMethod:(id)arg1 authType:(unsigned long long)arg2;
- (void)processIFrameMessage:(id)arg0;
- (id)deprecatedBridgeEngine;
- (void)setDeprecatedBridgeEngine:(id)arg0;
- (id)callbackHandlers;
- (void)setCallbackHandlers:(id)arg0;
- (void)registerJS2NativeHandlerBlock:(id /* block */)arg0 forJSMethod:(id)arg1 authType:(unsigned long long)arg2 methodNamespace:(id)arg3;
- (void)registerHandlerBlock:(id /* block */)arg0 forJSMethod:(id)arg1 authType:(unsigned long long)arg2 methodNamespace:(id)arg3;
- (id)getNewUnqiueID;
- (void)setWebView:(id)arg0;
- (id)webView;
- (void).cxx_destruct;
- (int)uniqueID;
- (void)setUniqueID:(int)arg0;
- (void)flushMessages;
- (id)initWithWebView:(id)arg0;

@end
