//
//     Generated by private class-dump
//

@class IESPortraitProducer;

@interface IESSolariaServerPortraitProducer : NSObject {
    IESPortraitProducer *_delegate;
}

@property (retain, nonatomic) IESPortraitProducer *delegate;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (id)delegate;
- (void)setDelegate:(id)arg0;

@end
