//
//     Generated by private class-dump
//

@class NSString;

@interface LSIMChatDetailBizCFactory : NSObject <LSListCellAndVMFactory>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)cellAndVMModelFromBaseMessageModel:(id)arg0;
+ (id)findCellAndVMModelWithOriginDict:(id)arg0 withKey:(id)arg1;
+ (void)createModelsCacheIfNeeded;
+ (id)cellVMWithCellModel:(id)arg0;
+ (id)registerCellAndVMModels;

@end
