//
//     Generated by private class-dump
//

@protocol LunaCyclePageDataSource <NSObject>

- (id)pageCycle:(id)arg0 createCycleItem:(id)arg1;
- (id)pageCycleCurrentModel:(id)arg0;
- (id)pageCycle:(id)arg0 preModelOfcurrent:(id)arg1;
- (id)pageCycle:(id)arg0 nextModelOfcurrent:(id)arg1;
- (id)pageCyclePlayingModel:(id)arg0;

@end
