//
//     Generated by private class-dump
//

@protocol NLETemplateMattingDelegate <NSObject>

- (void)templateMattingOnProgress:(double)arg0;
- (void)templateMattingOnSuccess;
- (void)templateMattingOnError:(id)arg0 error:(id)arg1;

@end
