//
//     Generated by private class-dump
//

@class NunkiSafeCache;

@interface NunkiConditionCache : NSObject {
    NunkiSafeCache *_cacheDic;
}

@property (retain, nonatomic) NunkiSafeCache *cacheDic;

- (id)cacheDic;
- (void)setCacheDic:(id)arg0;
- (id)conditionConfigForKey:(id)arg0;
- (void)setFactorsConfig:(id)arg0 forKey:(id)arg1;
- (id)init;
- (void).cxx_destruct;

@end
