//
//     Generated by private class-dump
//

@class NSString;

@interface PaidLiveTicketRecommendResponse_RecommendTicketDetail_PriceInfo : IESLivePBBaseMessage

@property (copy, nonatomic) NSString *amount;
@property (copy, nonatomic) NSString *currency;
@property (nonatomic) long long pos;

+ (id)descriptor;

@end
