//
//     Generated by private class-dump
//

@interface PIAOfflineResourceObtainer : NSObject

+ (void)obtainResourceWithURL:(id)arg0 completion:(id /* block */)arg1;
+ (id)obtainResourceSyncWithURL:(id)arg0 error:(id *)arg1;

@end
