//
//     Generated by private class-dump
//

@class NSArray, NSString, NSOperationQueue, SNICFNetworkManager;

@interface PoPGatewayNetwork : NSObject {
    NSOperationQueue *queue;
    NSString *_secertKey;
    NSString *_acesskeyId;
    NSString *_cerityIdAsKey;
    NSString *_cerityIdACKey;
    double _timeoutForInit;
    double _timeoutForVerify;
    SNICFNetworkManager *_cfNetworkManager;
    NSArray *_backupHostList;
}

@property (retain, nonatomic) SNICFNetworkManager *cfNetworkManager;
@property (copy, nonatomic) NSArray *backupHostList;
@property (nonatomic) double timeoutForInit;
@property (nonatomic) double timeoutForVerify;

+ (id)getIPAddressWithHost:(id)arg0;
+ (id)getAddressFromArray:(struct __CFArray { } *)arg0;

- (id)dictionaryToJson:(id)arg0;
- (id)urlEncode:(id)arg0;
- (id)aes256_decryptKey:(id)arg0 withSource:(id)arg1;
- (void)setCfNetworkManager:(id)arg0;
- (BOOL)isPRE;
- (id)addValue:(id)arg0 forKey:(id)arg1 to:(id)arg2;
- (id)getBackupServerAddress;
- (void)httpPost:(id)arg0 action:(id)arg1 extraHeader:(id)arg2 param:(id)arg3 degradeEndpoint:(id)arg4 ak:(id)arg5 sk:(id)arg6 completionBlock:(id /* block */)arg7;
- (id)backupHostList;
- (id)changeFirstword:(id)arg0;
- (id)getSignature:(id)arg0 data:(id)arg1;
- (id)formatIso8601Date;
- (id)computeSignature:(id)arg0 secret:(id)arg1;
- (double)timeoutForInit;
- (double)timeoutForVerify;
- (id)cfNetworkManager;
- (void)doPOPRequest:(id)arg0 action:(id)arg1 param:(id)arg2 ak:(id)arg3 sk:(id)arg4 completionBlock:(id /* block */)arg5;
- (id)aes256_decryptKey:(id)arg0 withData:(id)arg1;
- (void)verifySendContent:(id)arg0 completionBlock:(id /* block */)arg1;
- (void)sendOCRContent:(id)arg0 completionBlock:(id /* block */)arg1;
- (void)bizSendContent:(id)arg0 completionBlock:(id /* block */)arg1;
- (void)sendLogContent:(id)arg0 extraHeader:(id)arg1 completionBlock:(id /* block */)arg2;
- (void)sendInitFaceVerifyContent:(id)arg0 keyName:(id)arg1 initKey:(id)arg2 initSimpleValue:(id)arg3 completionBlock:(id /* block */)arg4;
- (void)setTimeoutForInit:(double)arg0;
- (void)setTimeoutForVerify:(double)arg0;
- (void)setBackupHostList:(id)arg0;
- (id)init;
- (void).cxx_destruct;
- (void)dealloc;
- (id)encode:(id)arg0;
- (id)getServerAddress;

@end
