//
//     Generated by private class-dump
//

@class NSString, UrlStructV2;

@interface ReplyToAwemeStructV2 : GPBMessage

@property (copy, nonatomic) NSString *awemeId;
@property (nonatomic) BOOL hasAwemeId;
@property (copy, nonatomic) NSString *desc;
@property (nonatomic) BOOL hasDesc;
@property (copy, nonatomic) NSString *authorNickname;
@property (nonatomic) BOOL hasAuthorNickname;
@property (retain, nonatomic) UrlStructV2 *cover;
@property (nonatomic) BOOL hasCover;
@property (copy, nonatomic) NSString *secUserId;
@property (nonatomic) BOOL hasSecUserId;
@property (copy, nonatomic) NSString *aliasCommentId;
@property (nonatomic) BOOL hasAliasCommentId;
@property (nonatomic) int awemeType;
@property (nonatomic) BOOL hasAwemeType;
@property (nonatomic) BOOL isAvailable;
@property (nonatomic) BOOL hasIsAvailable;
@property (retain, nonatomic) UrlStructV2 *authorAvatar;
@property (nonatomic) BOOL hasAuthorAvatar;
@property (nonatomic) int type;
@property (nonatomic) BOOL hasType;

+ (id)descriptor;

@end
