//
//     Generated by private class-dump
//

@class NSArray;

@protocol RTVCallObserver <NSObject>

@property (readonly, copy, nonatomic) NSArray *calls;

- (id)calls;
- (void)removeDelegate:(id)arg0;
- (void)addDelegate:(id)arg0 queue:(id)arg1;

@end
