//
//     Generated by private class-dump
//

@class NSString;

@interface RTVInteractionUserListViewCellModel : NSObject <RTVUICellModelDiffableInterface, RxPrimaryKey> {
    NSString *_title;
}

@property (readonly, copy, nonatomic) NSString *title;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)getInKey;
- (BOOL)joinDiffCalculate;
- (id)accessibilityLabel;
- (void).cxx_destruct;
- (id)title;
- (id)initWithTitle:(id)arg0;

@end
