//
//     Generated by private class-dump
//

@protocol RTVSEIMessageController <NSObject>

- (void)configWithXREnginer:(id)arg0;
- (BOOL)sendSEIMessage:(id)arg0 forKey:(id)arg1;
- (void)addMessageObserver:(id)arg0 forKey:(id)arg1;
- (void)removeMessageObserver:(id)arg0 forKey:(id)arg1;

@end
