//
//     Generated by private class-dump
//

@protocol RTVVoipPollingPullRoomInfoService <NSObject>

- (void)renderModel:(id)arg0 context:(id)arg1;
- (id)currentRunningModel;
- (void)start;
- (void)invalid;

@end
