//
//     Generated by private class-dump
//

@class NSMethodSignature, NSArray;

@interface RxInjectorInitializer : NSObject {
    BOOL _canAlloc;
    Class _type;
    SEL _selector;
    NSArray *_argumentKeys;
    NSMethodSignature *_signature;
}

@property (retain, nonatomic) Class type;
@property (nonatomic) SEL selector;
@property (nonatomic) BOOL canAlloc;
@property (retain, nonatomic) NSMethodSignature *signature;
@property (retain, nonatomic) NSArray *argumentKeys;

+ (id)initializerWithClass:(Class)arg0 selector:(SEL)arg1 argumentKeys:(id)arg2;
+ (id)initializerWithClass:(Class)arg0 selector:(SEL)arg1 argumentKeysArray:(id)arg2;
+ (id)initializerWithClass:(Class)arg0 classSelector:(SEL)arg1 argumentKeys:(id)arg2;
+ (id)initializerWithClass:(Class)arg0 classSelector:(SEL)arg1 argumentKeysArray:(id)arg2;

- (id)initWithClass:(Class)arg0 selector:(SEL)arg1 argumentKeys:(id)arg2;
- (id)initWithClass:(Class)arg0 classSelector:(SEL)arg1 argumentKeys:(id)arg2;
- (void)setCanAlloc:(BOOL)arg0;
- (id)initWithClass:(Class)arg0 selector:(SEL)arg1 argumentKeys:(id)arg2 classSelector:(BOOL)arg3;
- (BOOL)canAlloc;
- (id)nullify:(id)arg0;
- (id)keyForArgumentAtIndex:(unsigned long long)arg0;
- (id)rxPerform:(id)arg0;
- (void)setSignature:(id)arg0;
- (void)validate;
- (id)signature;
- (void).cxx_destruct;
- (Class)type;
- (id)target;
- (void)setSelector:(SEL)arg0;
- (void)setType:(Class)arg0;
- (SEL)selector;
- (unsigned long long)numberOfArguments;
- (id)argumentKeys;
- (void)setArgumentKeys:(id)arg0;

@end
