//
//     Generated by private class-dump
//

@class SECURLTrieNode;
@protocol SECURLWildcard;

@interface SECURLTrie : NSObject {
    SECURLTrieNode *_root;
    id<SECURLWildcard> _wildcardResolver;
}

- (id)initWithURLs:(id)arg0 wildcardResolver:(id)arg1;
- (id)matchPath:(id)arg0;
- (void)buildTries:(id)arg0;
- (void).cxx_destruct;
- (void)addURL:(id)arg0;
- (id)initWithURLs:(id)arg0;

@end
