//
//     Generated by private class-dump
//

@class NSMutableArray;

@interface SRIOConsumerPool : NSObject {
    unsigned long long _poolSize;
    NSMutableArray *_bufferedConsumers;
}

- (id)initWithBufferCapacity:(unsigned long long)arg0;
- (id)consumerWithScanner:(id /* block */)arg0 handler:(id /* block */)arg1 bytesNeeded:(unsigned long long)arg2 readToCurrentFrame:(BOOL)arg3 unmaskBytes:(BOOL)arg4;
- (void)returnConsumer:(id)arg0;
- (id)init;
- (void).cxx_destruct;

@end
