//
//     Generated by private class-dump
//

@class NSString, NSDictionary, NSArray, NSDate, NSMutableDictionary;
@protocol TencentLoginDelegate, TCLoginViewDelegate;

@interface TCLoginViewKit : TCWebViewKit <TCWebViewKitDelegate> {
    NSString *_accessToken;
    NSString *_openId;
    NSDate *_expirationDate;
    NSString *_encryToken;
    NSString *_payToken;
    NSDictionary *_passData;
    NSString *_appId;
    NSString *_redirectURI;
    NSArray *_permissions;
    id<TCLoginViewDelegate> _loginDelegate;
    id<TencentLoginDelegate> _newloginDelegate;
    NSString *_serial;
    NSString *_errorUrl;
    NSMutableDictionary *_loginDict;
    NSDictionary *_extraParams;
    unsigned long long _authMode;
    BOOL _isUseSafari;
    BOOL _isBrowserError;
    BOOL _isUserCancel;
    unsigned int _loginCount;
}

@property (readonly, nonatomic) NSString *accessToken;
@property (readonly, nonatomic) NSString *openId;
@property (readonly, nonatomic) NSDate *expirationDate;
@property (readonly, nonatomic) NSString *encryToken;
@property (readonly, nonatomic) NSString *payToken;
@property (readonly, nonatomic) NSDictionary *passData;
@property (retain, nonatomic) NSString *appId;
@property (retain, nonatomic) NSString *redirectURI;
@property (retain, nonatomic, setter=setPermissions:) NSArray *permissions;
@property (nonatomic) id<TCLoginViewDelegate> loginDelegate;
@property (nonatomic) id<TencentLoginDelegate> newloginDelegate;
@property (retain, nonatomic) NSString *serial;
@property (retain, nonatomic) NSString *errorUrl;
@property (retain, nonatomic) NSMutableDictionary *loginDict;
@property (retain, nonatomic) NSDictionary *extraParams;
@property (nonatomic) unsigned long long authMode;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

- (id)extraParams;
- (void)setExtraParams:(id)arg0;
- (id)openId;
- (void)setOpenId:(id)arg0;
- (void)setLoginDelegate:(id)arg0;
- (void)setLoginDict:(id)arg0;
- (void)appEnterBackground:(id)arg0;
- (void)setErrorUrl:(id)arg0;
- (BOOL)openWithExtraParams:(id)arg0;
- (id)generateUrlString:(id)arg0 params:(id)arg1;
- (void)loadReqURL:(id)arg0 webTitle:(id)arg1 delegate:(id)arg2;
- (BOOL)openWithSafariAndExtraParams:(id)arg0;
- (id)loginDict;
- (id)newloginDelegate;
- (id)getOwnBaseUrl;
- (void)openWithUrl:(id)arg0 webTitle:(id)arg1 delegate:(id)arg2;
- (id)loginDelegate;
- (void)setEncryToken:(id)arg0;
- (void)setPayToken:(id)arg0;
- (id)errorUrl;
- (void)doJsFun:(id)arg0;
- (BOOL)openWithSafari;
- (void)setNewloginDelegate:(id)arg0;
- (void)webViewKit:(id)arg0 didFinishedWithError:(id)arg1;
- (void)webViewKit:(id)arg0 didLoadWithContentError:(id)arg1;
- (void)webViewKit:(id)arg0 didLoadWithNetworkError:(id)arg1;
- (BOOL)webViewKit:(id)arg0 shouldStartLoadWithRequest:(id)arg1 navigationType:(long long)arg2;
- (BOOL)webViewKit:(id)arg0 shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientationsWithWebkit:(id)arg0;
- (BOOL)shouldAutorotateWithWebkit:(id)arg0;
- (id)initWithAppId:(id)arg0 redirectURI:(id)arg1 permissions:(id)arg2 loginDelegate:(id)arg3;
- (void)openWithAppId:(id)arg0 redirectURI:(id)arg1 permissions:(id)arg2 loginDelegate:(id)arg3;
- (BOOL)isNewQQBrowserInstall;
- (BOOL)isOldQQBrowserInstall;
- (BOOL)canHandleOpenURL:(id)arg0;
- (void)setAuthorData:(id)arg0 redirectURI:(id)arg1 permissions:(id)arg2;
- (id)encryToken;
- (id)payToken;
- (void)setAppId:(id)arg0;
- (void)cleanUp;
- (id)init;
- (id)traceID;
- (id)expirationDate;
- (void)clearData;
- (BOOL)open;
- (void)setExpirationDate:(id)arg0;
- (void)setPermissions:(id)arg0;
- (id)permissions;
- (id)serial;
- (id)accessToken;
- (void)dealloc;
- (id)appId;
- (void)setAccessToken:(id)arg0;
- (unsigned long long)authMode;
- (void)setAuthMode:(unsigned long long)arg0;
- (void)setSerial:(id)arg0;
- (id)passData;
- (void)setPassData:(id)arg0;
- (BOOL)handleOpenURL:(id)arg0;
- (id)redirectURI;
- (void)setRedirectURI:(id)arg0;
- (id)parseURLParams:(id)arg0;

@end
