//
//     Generated by private class-dump
//

@class TempoVariableZone, TempoFunction;

@interface TempoExecuteFunction : NSObject {
    BOOL _returnFlag;
    TempoFunction *_function;
    id _returnData;
    TempoVariableZone *_topZone;
}

@property (retain, nonatomic) TempoFunction *function;
@property (nonatomic) BOOL returnFlag;
@property (retain, nonatomic) id returnData;
@property (retain, nonatomic) TempoVariableZone *topZone;

- (id)topZone;
- (id)variableValueForName:(id)arg0;
- (void)pushVariableZone;
- (void)popVariableZone;
- (id)initWithFunctionDefine:(id)arg0;
- (id)topVariableZone;
- (id)variableZoneForName:(id)arg0;
- (BOOL)returnFlag;
- (void)setReturnFlag:(BOOL)arg0;
- (void)setTopZone:(id)arg0;
- (id)function;
- (void)setFunction:(id)arg0;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setReturnData:(id)arg0;
- (id)returnData;

@end
