//
//     Generated by private class-dump
//

@class NSString;

@interface TicketDetail_SaleBindingRoom : IESLivePBBaseMessage

@property (copy, nonatomic) NSString *roomId;
@property (nonatomic) int ticketExplanationCardStatus;

+ (id)descriptor;

@end
