//
//     Generated by private class-dump
//

@protocol TrackerServiceAdapter <NSObject>

- (void)registerEventV1WithKey:(id)arg0;
- (id)eventV1CategoryName;
- (void)eventV1:(id)arg0 attributes:(id)arg1;
- (void)eventV1:(id)arg0 label:(id)arg1;

@end
