//
//     Generated by private class-dump
//

@class NSMutableDictionary;

@interface TTBridgeThreadSafeMutableDictionary : NSMutableDictionary {
    NSMutableDictionary *_dict;
    struct _opaque_pthread_mutex_t { long long __sig; char __opaque[56]; } _safeThreadDictionaryMutex;
    struct _opaque_pthread_mutexattr_t { long long __sig; char __opaque[8]; } _safeThreadDictionaryMutexAttr;
}

- (id)initCommon;
- (id)init;
- (void).cxx_destruct;
- (id)copy;
- (id)keyEnumerator;
- (void)setObject:(id)arg0 forKey:(id)arg1;
- (id)initWithDictionary:(id)arg0;
- (id)allKeys;
- (id)objectForKeyedSubscript:(id)arg0;
- (id)allValues;
- (void)removeObjectForKey:(id)arg0;
- (void)setObject:(id)arg0 forKeyedSubscript:(id)arg1;
- (unsigned long long)count;
- (id)initWithCapacity:(unsigned long long)arg0;
- (id)initWithCoder:(id)arg0;
- (id)objectForKey:(id)arg0;
- (void)dealloc;
- (id)initWithObjects:(const id *)arg0 forKeys:(const id *)arg1 count:(unsigned long long)arg2;
- (void)removeAllObjects;

@end
