//
//     Generated by private class-dump
//

@class NSDictionary, NSHashTable, NSLock, NSObject;
@protocol OS_dispatch_source, OS_dispatch_queue;

@interface TTrackerPriorityTimer : NSObject {
    NSLock *locker;
    _Atomic unsigned long long interval_multiple_count;
    NSObject<OS_dispatch_source> *priority_timer;
    NSObject<OS_dispatch_queue> *base_queue;
    double base_interval;
    NSHashTable *triggerList;
    NSDictionary *settingByPriority;
}

+ (id)pluginVersion;
+ (id)sharedTimer;
+ (id)plugin;

- (void)registerTimer:(id)arg0;
- (BOOL)configureSettings:(id)arg0;
- (id)base_queue;
- (void)unregisterTimer:(id)arg0;
- (id)init;
- (void)resume;
- (void).cxx_destruct;
- (void)suspend;
- (void)notifyTimer;

@end
