//
//     Generated by private class-dump
//

@interface VEAudioDuration : IESMMObject {
    struct OpaqueAudioFileStreamID { } *_audioFileStreamID;
    BOOL _discontinuous;
    unsigned long long _processedPacketsCount;
    unsigned long long _processedPacketsSizeTotal;
    long long _dataOffset;
    BOOL _readyToProducePackets;
    BOOL _ended;
    id /* block */ _completion;
    double _packetDuration;
    unsigned long long _fileSize;
    struct AudioStreamBasicDescription { double mSampleRate; unsigned int mFormatID; unsigned int mFormatFlags; unsigned int mBytesPerPacket; unsigned int mFramesPerPacket; unsigned int mBytesPerFrame; unsigned int mChannelsPerFrame; unsigned int mBitsPerChannel; unsigned int mReserved; } _format;
}

@property (copy, nonatomic) id /* block */ completion;
@property (nonatomic) BOOL readyToProducePackets;
@property (nonatomic) double packetDuration;
@property (nonatomic) struct AudioStreamBasicDescription { double mSampleRate; unsigned int mFormatID; unsigned int mFormatFlags; unsigned int mBytesPerPacket; unsigned int mFramesPerPacket; unsigned int mBytesPerFrame; unsigned int mChannelsPerFrame; unsigned int mBitsPerChannel; unsigned int mReserved; } format;
@property (nonatomic) unsigned long long fileSize;
@property (nonatomic) BOOL ended;

- (void)getAudioDuration:(id)arg0 completion:(id /* block */)arg1;
- (void)closeAudioFileStream;
- (BOOL)readyToProducePackets;
- (void)calculatepPacketDuration;
- (void)handleAudioFileStreamProperty:(unsigned int)arg0;
- (void)handleAudioFileStreamPackets:(const void *)arg0 numberOfBytes:(unsigned int)arg1 numberOfPackets:(unsigned int)arg2 packetDescriptions:(struct AudioStreamPacketDescription { long long x0; unsigned int x1; unsigned int x2; } *)arg3;
- (void)setReadyToProducePackets:(BOOL)arg0;
- (double)packetDuration;
- (void)setPacketDuration:(double)arg0;
- (int)parseData:(id)arg0;
- (id /* block */)completion;
- (void).cxx_destruct;
- (void)setCompletion:(id /* block */)arg0;
- (unsigned long long)fileSize;
- (void)setFormat:(struct AudioStreamBasicDescription { double x0; unsigned int x1; unsigned int x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; unsigned int x7; unsigned int x8; })arg0;
- (void)setFileSize:(unsigned long long)arg0;
- (float)getDuration;
- (void)dealloc;
- (struct AudioStreamBasicDescription { double x0; unsigned int x1; unsigned int x2; unsigned int x3; unsigned int x4; unsigned int x5; unsigned int x6; unsigned int x7; unsigned int x8; })format;
- (BOOL)ended;
- (void)setEnded:(BOOL)arg0;

@end
