//
//     Generated by private class-dump
//

@interface VeLSSettingsManagerWrapper : NSObject {
    struct shared_ptr<livestrategy::ISettingsManager> { struct ISettingsManager *__ptr_; struct __shared_weak_count *__cntrl_; } _settingsManager;
}

@property (nonatomic) struct shared_ptr<livestrategy::ISettingsManager> { struct ISettingsManager *__ptr_; struct __shared_weak_count *__cntrl_; } settingsManager;

+ (id)sharedInstance;

- (void)StartPeriodicRequest;
- (void)GetLSSettings;
- (void)GetStrategySDKSettings;
- (id)GetRTMPlayer;
- (id)GetLivePlayerSettings;
- (id)GetAbrAutoSettings;
- (id)GetQuicSettings;
- (id)GetStrategyConfigByName:(id)arg0;
- (void).cxx_destruct;
- (void)setSettingsManager:(struct shared_ptr<livestrategy::ISettingsManager> { struct ISettingsManager *x0; struct __shared_weak_count *x1; })arg0;
- (struct shared_ptr<livestrategy::ISettingsManager> { struct ISettingsManager *x0; struct __shared_weak_count *x1; })settingsManager;
- (id).cxx_construct;

@end
