//
//     Generated by private class-dump
//

@class UIColor;

@interface VEPaintConfig : NSObject {
    float _strokeStep;
    float _strokeSize;
    float _featherSize;
    float _speedInfluence;
    int _type;
    UIColor *_color;
}

@property (retain, nonatomic) UIColor *color;
@property (nonatomic) float strokeStep;
@property (nonatomic) float strokeSize;
@property (nonatomic) float featherSize;
@property (nonatomic) float speedInfluence;
@property (nonatomic) int type;

- (id)paintConfigToStr;
- (float)strokeStep;
- (void)setStrokeStep:(float)arg0;
- (float)featherSize;
- (void)setFeatherSize:(float)arg0;
- (float)speedInfluence;
- (void)setSpeedInfluence:(float)arg0;
- (id)color;
- (id)init;
- (void).cxx_destruct;
- (int)type;
- (void)setType:(int)arg0;
- (void)setColor:(id)arg0;
- (float)strokeSize;
- (void)setStrokeSize:(float)arg0;

@end
