//
//     Generated by private class-dump
//

@class VideoHighlightResponse_Response;

@interface VideoHighlightResponse : IESLivePBBaseMessage

@property (retain, nonatomic) VideoHighlightResponse_Response *data_p;
@property (nonatomic) BOOL hasData_p;

+ (id)descriptor;

@end
