//
//     Generated by private class-dump
//

@protocol YataScrollViewDelegate <NSObject>

@optional

- (void)scrollViewDidScroll:(id)arg0 popupRenderObject:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg0 popupRenderObject:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg0 willDecelerate:(BOOL)arg1 popupRenderObject:(id)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg0 popupRenderObject:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg0;
- (void)scrollViewDidScroll:(id)arg0;
- (void)scrollViewDidEndDragging:(id)arg0 willDecelerate:(BOOL)arg1;
- (void)scrollViewWillBeginDragging:(id)arg0;

@end
